### PR TITLE
fix: remove usage of slices of struct pointers

### LINKED ISSUE #2494: Remove the use of slices of pointers to structs from our API
/kind cleanup
/priority critical-urgent
/milestone v0.7.0

**Describe the solution you'd like**
We use `[]*AStruct` in a number of places in our API and as a result with the latest versions of `conversion-gen` we are seeing this issue:

https://github.com/kubernetes/kubernetes/issues/98380

This can be fixed without a change to conversion-gen by changing of `[]*AStruct`  to `[]AStruct`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.6.6

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard@weave.works>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Due to a issue with conversion-gen and slices of struct pointers this changes our API to use slices of structs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2494 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
/lgtm
waiting on the e2e tests to approve.

**Comment by richardcase** [comment]
unmanaged e2e tests are passing but the eks e2e test is failing because of timeout.

**Comment by randomvariable** [comment]
@richardcase do you wanna bump test-infra?

**Comment by richardcase** [comment]
Both sets of e2e tests passed:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/2495/pull-cluster-api-provider-aws-e2e/1405517708379820032
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/2495/pull-cluster-api-provider-aws-e2e-eks/1405517708404985856

**Comment by richardcase** [comment]
> waiting on the e2e tests to approve.
@sedefsavas @randomvariable - the e2e tests have passed on this. Ready to go.

**Comment by sedefsavas** [comment]
Thanks @richardcase 
/lgtm
/approve

**Pull request merged**
