### PR TITLE
✨[0.4] feat: pass instance tags through to root volume

### LINKED ISSUE #1392: Forward port of 1394 - EC2 root volume should inherit additionalTags from instance
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Additional tags should pass through to EC2 instance root volumes. This makes analyzing resources in a shared account much simpler. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I already have this working in a branch, but wanted to allow for any discussion.

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:

Reconciles AWSCluster/AWSMachine-level tags down to EC2 instance root volumes. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1392 

/hold to let discussion close on the associated issue

Also, apologies, I did 0.4 first but I think it'll be an easy forward-port.

### CODE REVIEW

**Comment by randomvariable** [comment]
needs a `make generate`

**Comment by rudoi** [comment]
> needs a `make generate`

I've tried several times now and it's not giving me a diff... 🤔

**Comment by detiber** [comment]
> > needs a make generate

> I've tried several times now and it's not giving me a diff... thinking

Did you try rebasing? It might be related to a change that has since landed that updated generated files.

**Comment by rudoi** [comment]
i'm sure something absolutely silly is going on here but still no diff...

**Comment by ncdc** [comment]
It's this:

```
diff --git a/api/v1alpha2/zz_generated.conversion.go b/api/v1alpha2/zz_generated.conversion.go
index ae8cea0a..a29d0706 100644
--- a/api/v1alpha2/zz_generated.conversion.go
+++ b/api/v1alpha2/zz_generated.conversion.go
@@ -448,7 +448,9 @@ func autoConvert_v1alpha2_Instance_To_v1alpha1_Instance(in *Instance, out *v1alp
 	out.PublicIP = (*string)(unsafe.Pointer(in.PublicIP))
 	out.ENASupport = (*bool)(unsafe.Pointer(in.ENASupport))
 	out.EBSOptimized = (*bool)(unsafe.Pointer(in.EBSOptimized))
+	// WARNING: in.RootDeviceID requires manual conversion: does not exist in peer-type
 	out.RootDeviceSize = in.RootDeviceSize
+	// WARNING: in.RootDeviceTags requires manual conversion: does not exist in peer-type
 	// WARNING: in.NetworkInterfaces requires manual conversion: does not exist in peer-type
 	out.Tags = *(*map[string]string)(unsafe.Pointer(&in.Tags))
 	return nil
```

**Comment by rudoi** [comment]
@ncdc any thoughts on how I can get there locally? `make verify` exits 0.

**Comment by ncdc** [comment]
Try `make clean` first

**Comment by rudoi** [comment]
this is fixed up btw, RFR I think.

**Pull request merged**
