### PR TITLE
:seedling: Update to controller runtime 0.5.11

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by ncdc** [comment]
FWIW, the memory leak we fixed in controller-runtime only really occurs if you're dynamically adding a watch to a controller, and then you close/stop the cache (shared informers) associated with the that watch (e.g. when watching something from a workload cluster, **not** from the Manager's client/cache). It's fine to upgrade here, but it's not strictly required for CAPA from a memory leak perspective, I don't think.

**Comment by vincepri** [comment]
+1 to what Andy said, although we can merge this now if we want to ship CAPA with the fix earlier than CAPI

/approve

**Comment by CecileRobertMichon** [comment]
should we be doing this in CAPZ as well?

**Comment by randomvariable** [comment]
> should we be doing this in CAPZ as well?

Won't hurt.

**Pull request merged**
