### PR TITLE
✨ feat: initial EKS e2e tests

### LINKED ISSUE #1907: Create e2e tests for EKS
/kind feature

**Describe the solution you'd like**
We need create e2e tests to cover the new EKS functionality. This is to ensure that there are no regressions in functionality.

**Anything else you would like to add:**
Relates to #1534 

**Environment:**

- Cluster-api-provider-aws version: 0.5.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### LINKED ISSUE #2166: Managed machine pools fails due to missing permission
/kind bug

**What steps did you take and what happened:**
When creating a managed machine pool i encounter the following error:

`failed to describe AutoScalingGroup for nodegroup: AccessDenied: User: arn:aws:iam::123456: │
│ user/bootstrapper.cluster-api-provider-aws.sigs.k8s.io is not authorized to perform: autoscaling:DescribeAutoScalingGroups`

This causes the machine pool to be stuck in `ScalingUp` status.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:

Initial EKS e2e tests. Due to the time it takes to provision eks clusters in AWS we don't create clusters in `BeforeEach` and try
to do tests in steps. Additional tests will be added in the future via separate PRs. The tests make use of the bootstrap user credentials as the current e2e user doesn't have the required permissions.

Also includes a few additional fixes as a result of testing:
* Permissions for machine pools
* Permissions for EKS service linked roles

**Which issue(s) this PR fixes** :
Fixes #1907 
Fixes #2166

### CODE REVIEW

**Comment by richardcase** [comment]
I will add a job at a later date here: https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws

**Comment by richardcase** [comment]
Ready for review, but doing additional tests so:
/hold

**Comment by randomvariable** [comment]
Let's get a test-infra PR in, configured as a PR presubmit, and then ensure this all works before merging.

**Comment by richardcase** [comment]
> Let's get a test-infra PR in, configured as a PR presubmit, and then ensure this all works before merging.

I'll get the PR done now

**Comment by randomvariable** [comment]
it worked

/lgtm
/approve

**Pull request merged**
