### PR TITLE
:sparkles: Update cluster-api dependency as well as k8s and sonobuoy versions for testing

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
- Updates cluster-api dependency to v0.3.0
- Updates sonobuoy depenency for testing to v0.17.2
- Updated default k8s version for e2e/conformance testing to v1.17.3

/milestone v0.5.0

### CODE REVIEW

**Comment by detiber** [comment]
11/12 of the e2e tests passed, pretty sure the one that failed was a flake, and the conformance tests passed.

This should be good to go now.
/assign @randomvariable @ncdc

**Comment by randomvariable** [comment]
image

/lgtm

**Pull request merged**
