### PR TITLE
E2E tests for AlternativeGCStrategy

### LINKED ISSUE #4161: [E2E] Add e2e test for AlternativeGCStrategy feature gate
/area testing

It's the follow up work on https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4129.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by wyike**
**What type of PR is this?**
/kind support

**What this PR does / why we need it**:
Add two e2e for AlternativeGCStrategy feature
- [managed] [gc] should cleanup a cluster that has ELB/NLB load balancers using AlternativeGCStrategy
- [unmanaged] [gc] should cleanup a cluster that has ELB/NLB load balancers using AlternativeGCStrategy

They have exact same test steps with ` [managed] [gc] should cleanup a cluster that has ELB/NLB load balancers` and `[unmanaged] [gc] should cleanup a cluster that has ELB/NLB load balancers`, except that before creating workload cluster, `shared.ReconfigureDeployment` is executed to reconfigure capa deployment with `AlternativeGCStrategy` feature flag set to true and will recover capa after test is done

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4161 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Add E2E tests for AlternativeGCStrategy
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
@wyike can you please add release note for this

**Comment by wyike** [comment]
> @wyike can you please add release note for this

Added. How does it look like?

**Comment by Ankitasw** [comment]
> Added. How does it look like?

Looks good, thankyou 🙂

**Comment by Ankitasw** [comment]
/approve

cc @richardcase for another 👀 for review.

**Comment by Ankitasw** [comment]
@richardcase can you take some time to review this?

**Comment by wyike** [comment]
Hi @Ankitasw, the original commit in this PR is overwritten by accident in one force-push :( :

image


So I prepare a new commit to add the e2e tests:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4328

**Pull request merged**
