### PR TITLE
Default LeaderElectionResourceLock to leases

### PR DESCRIPTION
**Pull request by enxebre**
Controller runtime sets by default leader-election-resource-lock to ConfigMapsLeasesResourceLock so consumers can do smooth transitions.
This PR default our contorller to leases.

This mitigates overwhelming the apiserver in a large management cluster and avoid additional rbac.

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2827

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Expose leader-election-resource-lock as a flag
```

### CODE REVIEW

**Comment by enxebre** [comment]
/hold
Until solving the discussion here https://github.com/kubernetes-sigs/cluster-api/pull/5388

**Comment by randomvariable** [comment]
Doubly hold to go in after #2820  which has other changes in main.go, namely setting `RecoverPanic: true`

**Comment by randomvariable** [comment]
Just an FYI, you don't need to do :seedling: in the PRs in this repo as we use the upstream k8s release notes tool here now.

**Comment by randomvariable** [comment]
Looks like we're doing
/milestone v1.0.0

**Comment by furkatgofurov7** [comment]
@enxebre hi! Is this missing to cleanup rbac rules from leader-election-role.yml for configmaps/cm status like how it is done in similar PRs' in CAPI/CAPZ for example or those are left out in purpose?

**Pull request merged**
