### PR TITLE
⚠️ refactor: e2e test reorganisation

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:
Work on reorganizing the tests into packages with a shared package that can be used across different e2e test suite packages.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Relates #1907 

Tasks:

- [x] Split the e2e & conformance tests into packages
- [x] Create common shared test package
- [x] Data folder configurable with default
- [x] Refactor common shared package

### CODE REVIEW

**Comment by richardcase** [comment]
Issue with the flags parsing so:
/hold

**Comment by randomvariable** [comment]
/lgtm
/hold
for e2e tests

**Comment by randomvariable** [comment]
Looks like it's OK now and the test failure was a flake.

**Comment by randomvariable** [comment]
flake on spot instances.

/lgtm
/approve
/unhold

**Pull request merged**
