### PR TITLE
:sparkles: control plane load balancer subnets can be specified in spec

### LINKED ISSUE #1180: Allow specifying control plane load balancer subnets
/kind feature

**Describe the solution you'd like**
In our organization subnet creation is tightly controlled. We are given a set of subnets in our VPCs which we are permitted to use. There are also subnets we are not permitted to use.
I would like to be able to specify existing subnets by ID in the AWSCluster spec, which may not be public and may not be named or tagged by any convention (relating to CAPA anyway), for the control plane load balancer to use (machine subnets can already be specified, is my understanding).

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 0.4.1
- Kubernetes version: (use `kubectl version`): 1.15.3 / 1.15.0
- OS (e.g. from `/etc/os-release`): ubuntu 1604

### PR DESCRIPTION
**Pull request by andrewmyhre**
**What this PR does / why we need it**:
This PR allows subnets for the control plane load balancer to specified in the AWSCluster.Spec.ControlPlaneLoadBalancer struct. In environments where subnets are all private and/or cannot be created/tagged by non-privileged users it is necessary to specify the subnets to be used.

Note: in my environment I'm unable to manually test the operator behavior without specifying subnets, so I can't verify that I haven't broken those code paths.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1180

### CODE REVIEW

**Comment by ncdc** [comment]
@detiber @vincepri should we create the various issues for tasks to create the v1alpha3 API version and then have this PR go into the v1alpha3 API version?

**Comment by vincepri** [comment]
Sounds good to me

**Comment by ncdc** [comment]
@andrewmyhre could you please update this PR so the changes are against the new v1alpha3 api version? Thanks!

**Comment by andrewmyhre** [comment]
Closing in favor of #1241 for v1alpha3

**Pull request closed without merging**
