### PR TITLE
:bug: Use release branch when generating changelog

### LINKED ISSUE #4926: Release notes generation checks the wrong branch
/kind bug

**What steps did you take and what happened:**

When running the v2.4.2 release, we noticed that the release notes generated by the tool did not match what we expected based on https://github.com/kubernetes-sigs/cluster-api-provider-aws/compare/v2.4.1...v2.4.2.

Running the following invocation manually (which was pulled fromt eh Makefile) resulted in errors:

```
/hack/tools/bin/release-notes --debug --org $GH_ORG_NAME --repo $GH_REPO_NAME --start-sha $(git rev-list -n 1 ${PREVIOUS_VERSION}) --end-sha $(git rev-list -n 1 ${RELEASE_TAG}) --output $RELEASE_DIR/CHANGELOG.md --go-template go-template:$REPO_ROOT/hack/changelog.tpl --dependencies=false
WARN No subcommand specified, running "generate"
INFO Using output format: markdown
INFO Gathering release notes
DEBU Using authenticated GitHub client             file="github/github.go:212"
FATA gathering release notes: listing release notes: listing commits: GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-aws/commits?page=1&per_page=100&sha=master&since=2024-03-18T16%3A06%3A05Z&until=2024-04-11T14%3A20%3A08Z: 404 Not Found []  file="release-notes/main.go:193"
```

Looking up the flags for the tool, the following invocation worked as expected:

```
hack/tools/bin/release-notes --debug --org kubernetes-sigs --repo cluster-api-provider-aws --start-sha cbf531711d117b823c587622ba0e64b94d0fd314 --end-sha 1c230091ea3db600e08f57bde25c862b29827777 --output out/CHANGELOG.md --go-template go-template:/Users/nbrubake/projects/cluster-api-provider-aws/hack/changelog.tpl --dependencies=false --branch=release-2.4 --required-author=""
```

Within our Makefile, we'll likely need to use the `$RELEASE_BRANCH` variable to pass to the `--branch` flag.

**What did you expect to happen:**

The changelog output would match the PRs included within the two tags.

### PR DESCRIPTION
**Pull request by nrb**
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When generating release notes, the `release-note` tool would only look at the `main` branch. This was a problem when creating a release with a tag in a different branch, since the tags that the tool was comparing were not actually made against `main`.

This PR specifies the branch to reference when generating the release notes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4926

**Special notes for your reviewer**:

**Checklist**:

- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)

**Release note**:

```release-note
NONE
```

**Testing**:

Testing locally, setting `GITHUB_TOKEN` prior to invocation in order to prevent leaking.

```shell
❮ PREVIOUS_VERSION=v2.4.1 RELEASE_TAG=v2.4.2 RELEASE_BRANCH=release-2.4 make release-changelog
make -C hack/tools bin/release-notes
make[1]: `bin/release-notes' is up to date.
hack/tools/bin/release-notes --debug --org kubernetes-sigs --repo cluster-api-provider-aws --start-sha cbf531711d117b823c587622ba0e64b94d0fd314 --end-sha 1c230091ea3db600e08f57bde25c862b29827777 --output out/CHANGELOG.md --go-template go-template:/Users/nbrubake/projects/cluster-api-provider-aws/hack/changelog.tpl --dependencies=false --branch=release-2.4 --required-author=""
WARN No subcommand specified, running "generate"
INFO Using output format: markdown
INFO Gathering release notes
DEBU Using authenticated GitHub client             file="github/github.go:212"
INFO Starting to process commit 1 of 16 (6.25%): 1c230091ea3db600e08f57bde25c862b29827777  file="notes/notes.go:679"
INFO Starting to process commit 2 of 16 (12.50%): 362a226b10efbb40630643b5ebf0df3ccdb75a46  file="notes/notes.go:679"
INFO Starting to process commit 3 of 16 (18.75%): 3ee30c22c44b87c3dbc2ecb9128e235b676cba16  file="notes/notes.go:679"
INFO Starting to process commit 4 of 16 (25.00%): 08edbd7e151d265e348120e60afb53258bfd3fef  file="notes/notes.go:679"
INFO Starting to process commit 5 of 16 (31.25%): 271820658081bc4f19d26779716ad9b08fe3905e  file="notes/notes.go:679"
INFO Starting to process commit 6 of 16 (37.50%): e670328c6f96bc9906a36af33d2f252569f3739d  file="notes/notes.go:679"
INFO Starting to process commit 7 of 16 (43.75%): 90c4cd0ca574c0c6d001d7b4fb8bb84b52c8d13a  file="notes/notes.go:679"
INFO Starting to process commit 8 of 16 (50.00%): 1ca762a8988294b603eb51f36997e86f72fea7d8  file="notes/notes.go:679"
INFO Starting to process commit 9 of 16 (56.25%): 37ce4ee587519eb5c743f45d48dca59def659090  file="notes/notes.go:679"
INFO Starting to process commit 10 of 16 (62.50%): 4e23e8cdb2723c09583669ba57da82b2275ef677  file="notes/notes.go:679"
DEBU No PR found for commit 1ca762a8988294b603eb51f36997e86f72fea7d8: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU No PR found for commit 37ce4ee587519eb5c743f45d48dca59def659090: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU No PR found for commit 90c4cd0ca574c0c6d001d7b4fb8bb84b52c8d13a: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU No PR found for commit 362a226b10efbb40630643b5ebf0df3ccdb75a46: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU No PR found for commit 4e23e8cdb2723c09583669ba57da82b2275ef677: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU Got PR #4913 for commit: 1ca762a8988294b603eb51f36997e86f72fea7d8  file="notes/notes.go:782"
INFO PR #4913 seems to contain a release note      file="notes/notes.go:808"
INFO Starting to process commit 11 of 16 (68.75%): 51af40f1c636204f7af26c97d9487b1e32311a69  file="notes/notes.go:679"
DEBU No PR found for commit 51af40f1c636204f7af26c97d9487b1e32311a69: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU Got PR #4913 for commit: 37ce4ee587519eb5c743f45d48dca59def659090  file="notes/notes.go:782"
INFO PR #4913 seems to contain a release note      file="notes/notes.go:808"
INFO Starting to process commit 12 of 16 (75.00%): 58d65bf53933d5753180ba93e42e8890d3627bbe  file="notes/notes.go:679"
DEBU No PR found for commit 58d65bf53933d5753180ba93e42e8890d3627bbe: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU Got PR #4921 for commit: 362a226b10efbb40630643b5ebf0df3ccdb75a46  file="notes/notes.go:782"
INFO PR #4921 seems to contain a release note      file="notes/notes.go:808"
INFO Starting to process commit 13 of 16 (81.25%): 856e7cba3b2cb984b715701fb8bf3e8475901daf  file="notes/notes.go:679"
DEBU No PR found for commit 856e7cba3b2cb984b715701fb8bf3e8475901daf: no PR IDs found in the commit message  file="notes/notes.go:844"
DEBU Got PR #4914 for commit: 90c4cd0ca574c0c6d001d7b4fb8bb84b52c8d13a  file="notes/notes.go:782"
INFO PR #4914 contains exclusion (release-note-none)  file="notes/notes.go:791"
INFO Starting to process commit 14 of 16 (87.50%): 64b15463f44fdc02c344d8d471762caa14552728  file="notes/notes.go:679"
DEBU Got PR #4912 for commit: 271820658081bc4f19d26779716ad9b08fe3905e  file="notes/notes.go:782"
INFO PR #4912 seems to contain a release note      file="notes/notes.go:808"
INFO Starting to process commit 15 of 16 (93.75%): 557a58d1906858b44e8d130801381906f1feb528  file="notes/notes.go:679"
DEBU Got PR #4921 for commit: 1c230091ea3db600e08f57bde25c862b29827777  file="notes/notes.go:782"
INFO PR #4921 seems to contain a release note      file="notes/notes.go:808"
INFO Starting to process commit 16 of 16 (100.00%): cbf531711d117b823c587622ba0e64b94d0fd314  file="notes/notes.go:679"
DEBU Got PR #4913 for commit: 4e23e8cdb2723c09583669ba57da82b2275ef677  file="notes/notes.go:782"
INFO PR #4913 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4913 for commit: 08edbd7e151d265e348120e60afb53258bfd3fef  file="notes/notes.go:782"
INFO PR #4913 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4914 for commit: 3ee30c22c44b87c3dbc2ecb9128e235b676cba16  file="notes/notes.go:782"
INFO PR #4914 contains exclusion (release-note-none)  file="notes/notes.go:791"
DEBU Got PR #4911 for commit: e670328c6f96bc9906a36af33d2f252569f3739d  file="notes/notes.go:782"
INFO PR #4911 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4912 for commit: 58d65bf53933d5753180ba93e42e8890d3627bbe  file="notes/notes.go:782"
INFO PR #4912 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4911 for commit: 856e7cba3b2cb984b715701fb8bf3e8475901daf  file="notes/notes.go:782"
INFO PR #4911 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4912 for commit: 51af40f1c636204f7af26c97d9487b1e32311a69  file="notes/notes.go:782"
INFO PR #4912 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4846 for commit: cbf531711d117b823c587622ba0e64b94d0fd314  file="notes/notes.go:782"
INFO PR #4846 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4908 for commit: 64b15463f44fdc02c344d8d471762caa14552728  file="notes/notes.go:782"
INFO PR #4908 seems to contain a release note      file="notes/notes.go:808"
DEBU Got PR #4907 for commit: 557a58d1906858b44e8d130801381906f1feb528  file="notes/notes.go:782"
INFO PR #4907 seems to contain a release note      file="notes/notes.go:808"
INFO Checking PRs for mapped data                  file="notes/notes.go:289"
INFO finished gathering release notes in 1.471516625s  file="notes/notes.go:257"
INFO Got 7 release notes, performing rendering     file="release-notes/main.go:49"
INFO Release notes written to file: out/CHANGELOG.md  file="release-notes/main.go:150"
```

The PRs listed here match the PRs found when [comparing the v2.4.1 and v2.4.2 tags in GitHub](https://github.com/kubernetes-sigs/cluster-api-provider-aws/compare/v2.4.1...v2.4.2), namely:

 * 4907
 * 4908
 * 4911
 * 4912
 * 4913
 * 4914
 * 4921

The exception is PR 4846, which was found because the release notes tool is inclusive of the start SHA, and the GitHub comparison is not.

### CODE REVIEW

**Comment by nrb** [comment]
> The exception is PR 4846, which was found because the release notes tool is inclusive of the start SHA, and the GitHub comparison is not.

You can verify this by looking at the following information

The generated command's starting commit:

`hack/tools/bin/release-notes --debug --org kubernetes-sigs --repo cluster-api-provider-aws --start-sha cbf531711d117b823c587622ba0e64b94d0fd314 ...`

The `v2.4.1` [tag's commit SHA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commits/v2.4.1/), https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/cbf531711d117b823c587622ba0e64b94d0fd314

**Review by damdo — COMMENTED** [review]
Thanks!
/lgtm

**Pull request merged**
