### PR TITLE
Enable EventBridge feature

### PR DESCRIPTION
**Pull request by sedefsavas**
/kind failing-test

**What this PR does / why we need it**:
Reenabling EventBridge feature as boskos cleanup is merged.
https://github.com/kubernetes-sigs/boskos/pull/69
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Related to: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2240

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [X] adds or updates e2e tests

**Release note**:

```release-note
Enable EventBridgeInstanceState feature in e2e tests
```

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold
/lgtm
/approve

will merge after pass

**Comment by sedefsavas** [comment]
Tests passed.

**Pull request merged**
