### PR TITLE
:sparkles: Update cluster-api dependencies to v0.3.5

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Update cluster-api dependencies to v0.3.5

### CODE REVIEW

**Comment by detiber** [comment]
retry to see if flake:
/test pull-cluster-api-provider-aws-e2e-conformance

**Comment by vincepri** [comment]
Seems both tests failed in the same spot 🤔

**Comment by detiber** [comment]
> Seems both tests failed in the same spot

I don't think they did, the [e2e test failed](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1706/pull-cluster-api-provider-aws-e2e/1255950138262687744) a single test that is a relatively known flake and the [conformance test failed](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/1706/pull-cluster-api-provider-aws-e2e-conformance/1255950138254299136) before the conformance tests were kicked off (looks like a race condition between the webhooks being available and trying to create the cluster

**Comment by ncdc** [comment]
LGTM as well

**Pull request merged**
