### PR TITLE
[E2E] EFS CSI driver support

### LINKED ISSUE #3384: Validate and document EFS CSI driver support
/kind feature

**Describe the solution you'd like**
Add [EFS CSI driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) to defaults addons manifest so that CAPA clusters running on AWS can manage the lifecycle of [Amazon EFS](https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html) file systems.

### PR DESCRIPTION
**Pull request by Madhur97**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adding an E2E test to install and verify EFS CSI driver in a CAPA managed cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3384 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
e2e test is broken right now.
Will be fixed once this is in: https://github.com/kubernetes/test-infra/pull/26038

**Comment by Madhur97** [comment]
This PR is ready for review.

**Comment by sedefsavas** [comment]
/lgtm
/approve

We also need some documentation around this similar to external EBS CSI support and possibly publish the template as well.

**Pull request merged**
