### PR TITLE
✨ Add fine-grained service rate limiters

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
Rebase of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2033

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sedefsavas** [comment]
Did not added ratelimiter to MachinePool, it needs further investigation on how to incorporate there best.

/hold
Running e2e test.

**Comment by randomvariable** [comment]
> Did not added ratelimiter to MachinePool, it needs further investigation on how to incorporate there best.

Can you create a follow up issue if there isn't one?

**Comment by randomvariable** [comment]
can you squash these commits?

**Comment by sedefsavas** [comment]
Scale tests that are on this PR (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2034) are not passing due to docker rate limits:

`Failed to pull image "calico/cni:v3.13.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/calico/cni:v3.13.2": failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/calico/cni/manifests/sha256:bbf7e3ac3f80d0a356a6c27b095bd313d1106f8ed84f85850816ed79295843c1: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

But this something we need to worry in that PR.

**Comment by sedefsavas** [comment]
I will create the rebased test PR once this is merged.

**Comment by randomvariable** [comment]
On the scale test issue, we should probably bump Calico to the latest version. Going to assume that they've maybe got a new public registry that doesn't get hit by the limits?

**Pull request merged**
