### PR TITLE
Fixes trustPolicy reconcilation after failed attempt

### LINKED ISSUE #3900: EKS: OIDC Trust policy configMap never gets created if it has failed in the first attempt
/kind bug

**What steps did you take and what happened:**
During reconciling OIDC provider, https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/oidc.go#L45, first the OIDC provider is created and the the trust policy configMap is created. In case there is failure during trust policy creation, in next reconcile it never gets retried again because of this condition check: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/oidc.go#L46

**What did you expect to happen:**
reconcileTrustPolicy should happen even after a failed attempt

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by snehala27**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
 Fixes trustPolicy reconcilation after failed attempt
  - Check for scope.ControlPlane.Status.OIDCProvider.ARN is only applicable for provider ARN and not for trustPolicy
  - Set scope.ControlPlane.Status.OIDCProvider.TrustPolicy only after trust policy configMap is created

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3900 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by snehala27** [comment]
> Hello! Thank you for your contribution! Would you mind covering your changes with unit tests, please? :) thank you!

Sure!

**Comment by Ankitasw** [comment]
@snehala27 would you be able to continue with the PR?

**Comment by snehala27** [comment]
> @snehala27 would you be able to continue with the PR?

Yes. Working on it

**Comment by Ankitasw** [comment]
@snehala27 do you need any help to continue with this PR?

**Pull request closed without merging**
