### PR TITLE
Bump envsubst in /hack/tools

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area release

**What this PR does / why we need it**:
This PR bumps github.com/a8m/envsubst from 1.3.0 to 1.4.2 in /hack/tools

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4062 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
@Skarlso @richardcase can we merge this?

**Comment by Ankitasw** [comment]
PR is ready for review. Can I get 👀 for review?

**Comment by richardcase** [comment]
Seems good to me, just running some e2e incase there is any weirdness with the new versions when it substitutes the the variables.

When the pass feel free to unhold

/hold
/test pull-cluster-api-provider-aws-e2e
/test pull-cluster-api-provider-aws-e2e-eks

**Pull request merged**
