### PR TITLE
✨  Add validation and tests for io2 volume type.

### LINKED ISSUE #1886: Support io2 volumes
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Webhooks validate iops are set for io1 disk types, but not io2.
We should add the same validation for io2.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
See 
https://aws.amazon.com/blogs/aws/new-ebs-volume-type-io2-more-iops-gib-higher-durability/

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/good-first-issue
/help
/priority backlog

### PR DESCRIPTION
**Pull request by ffahri**
Signed-off-by: Fahri Yardımcı
#1886

**What this PR does / why we need it**:
This PR adds validation and tests for supporting io2 volume type in webhooks

**Which issue(s) this PR fixes** :
Fixes #1886

### CODE REVIEW

**Comment by ffahri** [comment]
cla done

**Comment by randomvariable** [comment]
lgtm, but it looks like we need to bump the AWS SDK for Go version to v1.34.10 for this to work in practice.
Mind updated go.mod, running `make modules` and `make generate`?

**Comment by ffahri** [comment]
I think it also helps this issue 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1887

**Comment by ffahri** [comment]
@randomvariable updated go mod and runned these command

**Comment by randomvariable** [comment]
Thanks, yup, it helps with #1887.

/ok-to-test

**Pull request merged**
