### PR TITLE
Delete broken symlinks committed by `dep`

### LINKED ISSUE #601: Gazelle warning
/kind bug

**What steps did you take and what happened:**
During any Bazel build there is a warning:

```
gazelle: open /Users/akutz/Projects/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/kubernetes/BUILD.bazel: no such file or directory
```

**Anything else you would like to add:**
https://github.com/kubernetes/kubernetes/blob/master/BUILD.bazel is a symlink...

**Environment:**

/milestone Next
/priority important-longterm
/help

### PR DESCRIPTION
**Pull request by liztio**
**What this PR does / why we need it**:

Workaround for https://github.com/golang/dep/issues/1564
Suggested by https://github.com/golang/dep/issues/1564#issuecomment-422366984

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #601

**Special notes for your reviewer**:

Please confirm this makefile works as intended on OSX!

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chuckha** [comment]
/approve

Works on OS X.

thanks for this fix, what was the reason for deleting the symlinks vs the `# gazelle:exclude vendor/k8s.io/kubernetes` option?

**Comment by vincepri** [comment]
Nice job @liztio !

**Comment by liztio** [comment]
@chuckha honestly someone in the issue said it probably wasn't the right way to do it, and I tended to agree. We don't exclude anything else in the vendor repo from Gazelle, and so it seemed like it might lead to weird glitches down the line.

**Pull request merged**
