### PR TITLE
updating deprecated ENI_CONFIG_LABEL_DEF value

### PR DESCRIPTION
**Pull request by luthermonson**
**What type of PR is this?**
/kind bug
Since 1.17 this label is now [deprecated](https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone). Switching the env to the new [label](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion).

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
Hmmm won't this negatively affect existing environments?

**Comment by luthermonson** [comment]
you would prefer if it's already set to leave it as is and only do this in new instances?

**Comment by luthermonson** [comment]
thought about it some more...

1st thought is this is actually [custom networking configuration](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) and it's turned on by default and it's probably safer to lock some of this stuff behind some boolean gate. there are also more env vars that are not implemented that im looking into.

2nd thought, eks is all experimental and this would be an easy release note + label update for anyone wanting to bump capa versions.

**Comment by Skarlso** [comment]
Ah sorry I missed your answer. Eks is experimental that's true. However, it is quite in use.

So we must be vigilant in changing things that might affect existing clusters.

**Comment by Skarlso** [comment]
For example, suppose you do this and run this on an existing cluster. In that case, I think it would reconcile the DaemonSet with the new environment property, which probably would trigger the recycling of the pods to apply the new environment property, which is an unexpected behaviour when doing a cluster API update.

Either that is fine to do and an accepted behaviour and well documented, OR, we don't do anything if the old value exists, but when creating a new cluster, we use the new value. And after a while, we can remove the check for the old value.

WDYT? @sedefsavas any objects or correction on my thinking? :)

**Comment by Skarlso** [comment]
Oh! Also, I believe this will create two values with the same name.

Because the environment property list allows for that, unfortunately. It doesn't de-duplicate normally.

We should test this behaviour.

**Comment by Skarlso** [comment]
When testing I actually discovered a different bug that the environment property changes weren't being applied correctly:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3677

**Comment by Skarlso** [comment]
Also related, the values CAN have duplicate entries: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3678

So this change will not update a value but duplicate it.

**Comment by luthermonson** [comment]
closing for a bigger PR with more stuff

**Pull request closed without merging**
