### PR TITLE
:bug: Accept empty string SSHKeyName in AWSCluster & AWSMachine validation webhooks

### LINKED ISSUE #2306: Validation webhook forbids empty string SSH key value
/kind bug

**What steps did you take and what happened:**
I created an AWSCluster with `spec.sshkeyName` set to empty string:

```shell
kubectl create -f- <<<EOF
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: minimal
spec:
  region: us-west-2
  sshKeyName: ""
EOF
```

```shell
Error from server (AWSCluster.infrastructure.cluster.x-k8s.io "minimal" is invalid: sshKey: Invalid value: "": Name is invalid. Must be specified in ASCII and must not start or end in whitespace): error when creating "STDIN": admission webhook "validation.awscluster.infrastructure.cluster.x-k8s.io" denied the request: AWSCluster.infrastructure.cluster.x-k8s.io "minimal" is invalid: sshKey: Invalid value: "": Name is invalid. Must be specified in ASCII and must not start or end in whitespace
```

**What did you expect to happen:**
I expected the AWSCluster object to pass validation.

**Anything else you would like to add:**
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1621 added support for an empty string SSH key value 
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1978 forbid the empty string SSH key value in the validation webhook
- I propose adding a test for the empty string SSH key value, and to modify the validation webhook code so that the test passes.

**Environment:**

- Cluster-api-provider-aws version: v0.6.4
- Kubernetes version: (use `kubectl version`): Client Version: v1.20.4, Server Version: v1.20.2
- OS (e.g. from `/etc/os-release`): Fedora 33

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Makes the AWSCluster & AWSMachine validation webhooks accept an empty string for `SSHKeyName`. That value is supported by the API.
 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2306 

**Special notes for your reviewer**:
- The webhook test files have slightly different sets of SSHKeyName validation tests. The SSHKeyName field is common to both AWSCluster and AWSMachine, so I think there should be one set of tests for the field. I can do this in a follow-up PR. WDYT?
- The first two commits add tests; they are expected to fail. The third commit adds the fix.
- 
**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix the AWSCluster & AWSMachine validation webhooks, so that they accept an empty string for the `SSHKeyName` field.
```

### CODE REVIEW

**Comment by randomvariable** [comment]
thanks!

**Comment by dlipovetsky** [comment]
```
api/v1alpha3/webhooks.go:35: File is not `gofmt`-ed with `-s` (gofmt)
```

Sorry, a lint (gofmt) issue. Will fix and force-push. Ironically, it's complaining about a missing newline at the end of the file. Meanwhile, the same commit fixed the imports :joy:

**Comment by dlipovetsky** [comment]
@randomvariable Thanks for the review! I hope this makes it into the next release :smile:

**Comment by sedefsavas** [comment]
/lgtm

Also @dlipovetsky  +1 to have a single set of tests.

**Comment by dlipovetsky** [comment]
Thanks for the review @sedefsavas!

**Pull request merged**
