### PR TITLE
:docs: fix typos in eks commands

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
**What this PR does / why we need it**:
fixes a couple of typos in commands related to EKS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by randomvariable** [comment]
Actually, yup thanks for this.

/lgtm
/approve

**Comment by richardcase** [comment]
Good spot @kkeshavamurthy, thank you

**Comment by richardcase** [comment]
@randomvariable @kkeshavamurthy  -  Just as a fyi, we also have some pending docs updates in #2030

**Pull request merged**
