### PR TITLE
:seedling: Align golangci-lint with upstream Cluster API

### PR DESCRIPTION
**Pull request by vincepri**
**What type of PR is this?**

**What this PR does / why we need it**:

This PR adds a golangci-lint GitHub action, which gives inline feedback on the PR, and aligns the linter with upstream cluster-api.

/kind cleanup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nrb — APPROVED** [review]
/lgtm

**Comment by damdo** [comment]
Nice one!
/lgtm
Thank you

Since we are touching a lot of code, even if its an innocent refactor, let's give the E2Es a spin.

/test pull-cluster-api-provider-aws-e2e
/test pull-cluster-api-provider-aws-e2e-eks

**Comment by damdo** [comment]
Looks like E2Es timed out.
I've seen those timeouts in other PRs we should probably look into them.

/test pull-cluster-api-provider-aws-e2e

**Pull request merged**
