### PR TITLE
:running: go.mod: Bump AWS SDK to v1.25.16

### PR DESCRIPTION
**Pull request by randomvariable**
Of interest to CAPA are the following:
* Support for M5n, M5dn, R5n, R5dn, A1.metal & G4 instances
* Updates to region and endpoint data
* Updates to the default retryer:
  * Configurable retry behaviours
  * Calculated jitter for delay
* Support for client-side metrics
* Support for assuming role via the Kubernetes service account token

### CODE REVIEW

**Comment by detiber** [comment]
> Support for assuming role via the Kubernetes service account token

Is there any more information on this? I tried to track it down in the release notes but didn't see anything.

/approve

**Comment by aaroniscode** [comment]
> > Support for assuming role via the Kubernetes service account token
> 
> Is there any more information on this? I tried to track it down in the release notes but didn't see anything.

@detiber The new Amazon feature IAM Roles for Service accounts makes use of this. Some info here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by randomvariable** [comment]
@detiber:
> Is there any more information on this? I tried to track it down in the release notes but didn't see anything.
Under https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v1210-2019-07-18, it's the unassuming
> Adds support for assuming an role via the Web Identity Token. Allows for OIDC token files to be used by specifying the token path through the AWS_WEB_IDENTITY_TOKEN_FILE, and AWS_ROLE_ARN environment variables.

Instructions on use are at https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Pull request merged**
