### PR TITLE
Clean up internet-facing loadbalancer scheme logic

### LINKED ISSUE #3673: Clean up internet-facing loadbalancer scheme logic
To fix a casing issue (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2768), we had some custom logic implemented [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2801).

With v1beta2 API version, we no longer need this custom logic as users were not allowed to use the incorrect LB scheme (Internet-facing) in v1beta1.

/triage accepted
/priority important-soon
/milestone v2.x
/assign

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
To fix a casing issue (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2768), we had some custom logic implemented https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2801.

With v1beta2 API version, we no longer need this custom logic as users were not allowed to use the incorrect LB scheme (Internet-facing) in v1beta1.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3673

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [X] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
Need to look at the test failure locally

**Comment by dlipovetsky** [comment]
Thanks!

The apidiff failure is expected.

/lgtm

**Comment by Ankitasw** [comment]
Test passing locally so
/retest

**Pull request merged**
