### PR TITLE
Add v1alpha3 to v1alpha4 upgrade e2e test

### LINKED ISSUE #2388: Add v1alpha3 to v1alpha4 upgrade e2e test
Add an e2e test for v1alpha3 to v1alpha4 upgrade similar to what core cluster-api is adding [here](https://github.com/kubernetes-sigs/cluster-api/pull/3708) and run a basic scale test to make sure it is functional.

https://github.com/kubernetes-sigs/cluster-api/pull/3708

/help
/good-first-issue
/milestone v0.7.x

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind regression

**What this PR does / why we need it**:
The upgrade path from v1alpha3 to v1alpha4 has to be tested in E2E, hence this PR.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2388 

**Checklist**:
- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [X] adds or updates e2e tests

**Release note**:
```release-note
Add v1alpha3 to v1alpha4 upgrade test
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
@randomvariable the failure in e2e is related to [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2763) issue which needs fix, now its failing more frequently(as i checked in local)

**Comment by sedefsavas** [comment]
Let's wait until https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2763 is fixed to add more tests.
/hold

**Comment by sedefsavas** [comment]
Since, we know the reason why multitenancy test is failing:
/hold cancel

/approve
/lgtm

**Pull request merged**
