### PR TITLE
feat: add support for taints for managed machine pools (backport)

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This adds support for specifying taints on the `AWSManagedMachinePool` that will translate into taints being set on the nodes of the the EKS node group that is created.

It also supports updating the taints for a node group.

This is a backport of #2405 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Relates #2399

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits

**Release note**:

```release-note
Taints supported on EKS node groups created via AWSManagedMachinePool 
```

### CODE REVIEW

**Comment by richardcase** [comment]
Whilst additional testing:

/hold

**Comment by sedefsavas** [comment]
Is this also good to go @richardcase ?

**Comment by richardcase** [comment]
> Is this also good to go @richardcase ?

Yes all good to go @sedefsavas

**Pull request merged**
