### PR TITLE
[WIP] Refactor e2e test

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Refactor the e2e tests a bit

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by detiber** [comment]
/assign @chuckha 
Trying to get this a bit closer to something that will also work with v1alpha2

**Comment by chuckha** [comment]
This is looking pretty good, what's left to do that makes this a WIP?

**Comment by detiber** [comment]
> This is looking pretty good, what's left to do that makes this a WIP?

I'm still (albeit slowly) testing some local changes that I want to add

**Comment by ncdc** [comment]
This work is now in master - no need to backport to 0.3.x.
/close

**Pull request closed without merging**
