### PR TITLE
Revert "Merge pull request #3467 from phoban01/fix-awsmachinepool-spec typo"

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
The change in #3467 should have been made to v1beta2, but was made to v1beta1 by mistake.

Thanks to @pydctw for spotting the mistake!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by richardcase** [comment]
As well as the v1beta1 revert it's probably worth reapplying the change in v1beta2 at the same time. Wdyt?

And thank you @pydctw  for spotting this mistake.

**Comment by Skarlso** [comment]
OMG. 🤦

**Comment by Skarlso** [comment]
What's up with the tests? I can't see any logs or errors?

**Comment by Ankitasw** [comment]
again something to do with prow i guess.

**Comment by Ankitasw** [comment]
@dlipovetsky retest label not working, i think you might have to make a new commit 😓

**Comment by dlipovetsky** [comment]
> As well as the v1beta1 revert it's probably worth reapplying the change in v1beta2 at the same time. Wdyt?

I will add a commit for v1beta1 to this PR.

**Comment by dlipovetsky** [comment]
Nevermind, this was merged. I'll open a separate PR with the v1beta2 change.

**Comment by Ankitasw** [comment]
Yeah I was under the impression that you would open a separate PR 😓 sorry

**Pull request merged**
