### PR TITLE
add capi categories

### PR DESCRIPTION
**Pull request by mytunguyen**
**What this PR does / why we need it**:
Add capi categories so that we can do kubectl get cluster-api

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by chuckha** [comment]
ohh nice, should we be doing this with all CRDs on all providers?

**Comment by chuckha** [comment]
/approve

Based on the other PRs it looks like a yes!

Thanks for doing this!

**Comment by vincepri** [comment]
Thanks for getting this done @mytunguyen !

**Pull request merged**
