### PR TITLE
✨ feat: graduate the garbage collection feature

### LINKED ISSUE #4397: Graduate the garbage Collection feature
/kind feature

**Describe the solution you'd like**
We introduced GC in v1.5.0 in Aug 2022. I propose that we graduate this feature and enable it by default.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This moves the "garbage collection" feature out of experimental & to beta and as such it will be enabled by default. The doesn't move the alternative strategy out of alpha as we don't have enough testing to cover it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4397 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
action required
The garbage collection feature will be enabled by default. If you don't want to use this feature then you will need to explicitly disable it. Please see the documentation for instructions.
```

### CODE REVIEW

**Comment by richardcase** [comment]
I need to pick this up again.

/milestone v2.7.0

**Comment by damdo** [comment]
Hey @richardcase are you likely to pick it up in the coming days? Or should we take it out of v2.7.0?

**Comment by richardcase** [comment]
> Hey @richardcase are you likely to pick it up in the coming days? Or should we take it out of v2.7.0?

Not likely i the coming days i'm afraid. To much still outstanding with the AMI stuff. Yes lets move to v2.8.0

/milestone v2.8.0

**Comment by richardcase** [comment]
I'm going to re-create this:

/close

**Pull request closed without merging**
