### PR TITLE
Upgrade to use latest Kind version v0.12.0

### PR DESCRIPTION
**Pull request by shivi28**
**What type of PR is this?**
/area release

**What this PR does / why we need it**:
This updates to make use of latest kind v0.12.0 version 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Upgrade to use latest Kind version v0.12.0
```

### CODE REVIEW

**Comment by pydctw** [comment]
I don't see `hack/ensure-kind.sh` is used in our codebase.

Shouldn't it be referenced from ci scripts?
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/scripts/ci-e2e.sh#L33
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/scripts/ci-e2e-eks.sh#L33

**Comment by shivi28** [comment]
Nice observation @pydctw. Thanks for bringing this.
Even the `hack/ensure-kubectl.sh` is not used anywhere. 
I will make these changes and add it in above files as per your suggestion.

**Comment by Ankitasw** [comment]
Hey @shivi28, thanks for the PR :tada:
It would also be great if we take care of updating the kind version in go.mod in hack/tools, wdyt?

**Comment by shivi28** [comment]
> Hey @shivi28, thanks for the PR 🎉 It would also be great if we take care of updating the kind version in go.mod in hack/tools, wdyt?

I think this could be handled by this [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3305). If there is no specific reason to close this [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3305) then I think you can reopen it

**Comment by dlipovetsky** [comment]
+1 to keeping related changes to the same PR. I'm not sure if we have permission to add commits to existing PRs in this repo; if we do, then adding commits to the dependabot PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3305 is an option.

**Comment by Ankitasw** [comment]
> I'm not sure if we have permission to add commits to existing PRs in this repo; if we do, then adding commits to the dependabot PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3305 is an option.

Atleast when I tried, I have no permission to do so. I think maintainers have that rights to amend to dependabot PR but I m not super sure.

**Comment by pydctw** [comment]
> Nice observation @pydctw. Thanks for bringing this. Even the `hack/ensure-kubectl.sh` is not used anywhere. I will make these changes and add it in above files as per your suggestion.

Looks good to me. Thanks for also adding ensure-kubectl.sh to CI scripts.

**Pull request merged**
