### PR TITLE
🐛 fix: bastion reconcilation and connection error when using `eks` flavor

### LINKED ISSUE #1956: Creating a bastion with the `eks` flavor fails
/kind bug

**What steps did you take and what happened:**
Create a kind cluster, init the aws and eks-bootstrap providers. Render the `eks` flavour (i.e. cluster-template-eks.yaml) and then add fields to enable the bastion. For example the **AWSManagedControlPlane** definition should look like this:

```yaml
kind: AWSManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
metadata:
  name: "capi-managed-test-control-plane"
spec:
  region: "eu-west-2"
  sshKeyName: "capi-management-2"
  version: "v1.17.0"
  bastion:
    enabled: true
```

When this is applied reconciliation of the **AWSManagedControlPlane** fails with the following error:

```bash
[manager] E0919 04:35:36.278342       8 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile bastion host for AWSManagedControlPlane default/capi-managed-test-control-plane: failed to run instance: MissingParameter: When specifying a security group you must specify a group id for each item\n\tstatus code: 400, request id: a22fa765-cdaf-4de6-9993-8ae99b0565d4" "controller"="awsmanagedcontrolplane" "name"="capi-managed-test-control-plane" "namespace"="default"
```

**What did you expect to happen:**
A would expect the reconciliation to be successful and the bastion instance to be created.

**Anything else you would like to add:**
Found as part of investigating #1954 

**Environment:**

- Cluster-api-provider-aws version: 0.6.0
- Kubernetes version: (use `kubectl version`): 1.17

### LINKED ISSUE #1958: AWSCluster defaults/validation are not applied in the managed side
/kind bug

**What steps did you take and what happened:**
The defaults/validation that are done as part of the [AWSCluster webhook](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/api/v1alpha3/awscluster_webhook.go) aren't applied to the managed/eks side of the provider. For example if you enable a bastion in the **AWSManagedControlPlane** spec then the default for the AllowedCIDRBlocks isn't set and so you can't SSH to the bastion. 

**What did you expect to happen:**
Most of the same defaults and validation should apply to both umanaged/managed sides of the provider, especially for the network service.

**Anything else you would like to add:**
Found as part of investigating #1954 

**Environment:**

- Cluster-api-provider-aws version: 0.6.0

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:
The bastion was being reconciled before the security groups and this based the bastion reconciliation to fail. The reconciliation order has been updated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1956
Fixes #1958

### CODE REVIEW

**Comment by richardcase** [comment]
Changing back to WIP to include other bastion related fixes

**Comment by randomvariable** [comment]
I assume this will need to be rebased on #1949

**Comment by richardcase** [comment]
> I assume this will need to be rebased on #1949

Yes it will....thanks for approving the refactor.

**Pull request merged**
