### PR TITLE
:bug: Delete VPC endpoints only if s3 bucket is enabled

### PR DESCRIPTION
**Pull request by vincepri**
**What type of PR is this?**

**What this PR does / why we need it**:

/kind bug

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by damdo** [comment]
cc. @richardcase @dlipovetsky

**Comment by dkoshkin** [comment]
Does this make sense to backport to v2.3? Sometimes it may be difficult to change IAM policies in larger enterprises, and this fix would avoid the need for that.

**Pull request merged**
