### PR TITLE
bugfix: Fix log level for a couple of message of log messages

### LINKED ISSUE #3454: Some log messages are misleading and probably need to be moved to a lower level
/kind bug

**What steps did you take and what happened:**
`awsmachine_controller.go:763]  "msg"="Deleting unneeded entry from AWS S3"  "secretPrefix"=""`
and
`awsmachine_controller.go:432]  "msg"="Reconciling AWSMachine"`

occur with great frequency in the logs, and neither provides much information or insight into what's going on.  Additionally, CAPA is not actually deleting anything from AWS S3, and so might lead to a misleading action that doesn't actually occur.

**What did you expect to happen:**

I believe we would be best served by moving these out of `INFO` and into debug.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: `v1.4.1`
- Kubernetes version: (use `kubectl version`): `v1.23.4`
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by tasdikrahman**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixes #3454

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by shivi28** [comment]
In the issue #3454 we were discussing on handling
```
We should not log this unless ignition is used.
awsmachine_controller.go:763] "msg"="Deleting unneeded entry from AWS S3" "secretPrefix"=""
```
Are we not handling this scenario in this PR only? May be add [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controllers/awsmachine_controller.go#L763) line after [this](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controllers/awsmachine_controller.go#L774).

Otherwise changes lgtm.

**Comment by tasdikrahman** [comment]
Hello @shivi28 , I tried incorporating your changes, please have a look

**Comment by sedefsavas** [comment]
/approve

cc @voor for review.

**Pull request merged**
