### PR TITLE
🏃 Automate creating a cluster with name having period symbol

### PR DESCRIPTION
**Pull request by sirao**
Added automation to test cluster creation where cluster name
contains symbol '.'

Executed tests locally and tests succeeded.

### CODE REVIEW

**Comment by vincepri** [comment]
LGTM

/assign @detiber

**Comment by ncdc** [comment]
I'm curious what is special about the `.` that we need to test it in a full e2e test?

**Comment by sirao** [comment]
> I'm curious what is special about the `.` that we need to test it in a full e2e test?

Earlier, when special characters given in cluster name, LoadBalancer was not provisioned.

**Comment by ncdc** [comment]
Thanks!

/approve

**Pull request merged**
