### PR TITLE
[release-2.2] [E2E] Fix E2E pipeline failures

### LINKED ISSUE #4550: [release-2.2] Blocking e2e tests failing
/kind bug

**What steps did you take and what happened:**

Due to there being not being the required PR checks on the `release-2.2` branch some issues have been introduced. #4547 fixed 2 of the issues but we still have an problem with the blocking e2e tests on the branch.

Fom [this example run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/4547/pull-cluster-api-provider-aws-e2e-blocking-release-2-2/1710294379597402112):

```
msg: "failed to find releases tagged with a valid semantic version number",
```

**What did you expect to happen:**

I expect the test to pass on the branch

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind failing-test
/kind support

**What this PR does / why we need it**:
This PR adds python3-requests package installation which is breaking right now in the pip installation in CI.
It also fixes the semantic version of latest aws infrastructure provider.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4550

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
@Ankitasw - how come `--break-system-packages` is needed?

**Comment by Ankitasw** [comment]
It was a guess work based on the error message
```
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
```

Fix given in #4564 makes more sense to me, I will change it.

**Comment by Ankitasw** [comment]
cc @Skarlso @richardcase to take a final look

**Pull request merged**
