### PR TITLE
Adding tags to OIDC providers

### PR DESCRIPTION
**Pull request by vishu2498**
**What type of PR is this?** /kind feature

**What this PR does / why we need it**: Currently while creating an EKS cluster, its respective OIDC provider gets created and reconciled. However it didn't have the same tags as of the cluster. This PR adds the code for the OIDC provider to also have same tags as of cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

Proof of OIDC getting tagged:
Pasted Graphic

### CODE REVIEW

**Comment by vishu2498** [comment]
@Skarlso Can you please check and merge this PR?

**Comment by Skarlso** [comment]
/test pull-cluster-api-provider-aws-e2e-eks
/lgtm
/approve
/hold

until tests pass

**Pull request merged**
