### PR TITLE
Scope down RBAC permissions for CAPA resources

### LINKED ISSUE #2335: Scope down RBAC permissions
/kind cleanup

```
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=awsclusters,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=awsclusters/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=clusters;clusters/status,verbs=get;list;watch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=awsclusterroleprincipals;awsclusterstaticprincipals,verbs=get;update;patch;list;watch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=awsclustercontrollerprincipals,verbs=get;list;watch;create;update;patch
```

We should review these permissions. Don't need create permissions on these, and also make sure we're using status resources.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area security
/kind cleanup

**What this PR does / why we need it**:
This PR cleans up some of the unused permissions from RBAC for the CAPA resources.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2335 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
This PR is ready for review

**Comment by Ankitasw** [comment]
cc @richardcase for review.

**Comment by richardcase** [comment]
This is great, thanks @Ankitasw 

/approve

**Pull request merged**
