### PR TITLE
:seedling: Bump CAPI to v1.7.0

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**
/kind support

**What this PR does / why we need it**:

CAPI v1.7.0 is out now, so this PRs bumps the CAPI version used by CAPG with the new released one.

Bumps CAPI to v1.7.x based on https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.6-to-v1.7.md

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds or updates e2e tests

**Release note**:
```release-note
Bump CAPI to v1.7.0
```

### CODE REVIEW

**Comment by nrb** [comment]
/retitle :seedling: WIP: Bump CAPI to v1.7.x

**Comment by damdo** [comment]
Early timeout

/test pull-cluster-api-provider-aws-e2e

**Comment by damdo** [comment]
/unhold

Ready for labelling
cc. @richardcase

**Comment by richardcase** [comment]
Thanks @damdo . This looks good from my side and the e2e tests are passing so:

/lgtm
/approve

**Pull request merged**
