### PR TITLE
Promote Skarlso to reviewer

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
This PR adds @Skarlso to CAPA reviewers.

@Skarlso has been actively contributing to CAPA for a while, working on the IPv6 support at the moment and willing to continue to contribute more with reviews. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
thank you! :) <3

**Comment by richardcase** [comment]
A big +1 from me. Consistent contributions and tackling a very big change in adding IPv6 support.

**Comment by pydctw** [comment]
A big +1 from me also. Congrats @Skarlso 🎉

**Comment by dlipovetsky** [comment]
+1. Thanks for your contributions, @Skarlso!

**Comment by richardcase** [comment]
From the office hours mazy consensus until Monday 1st August when we will merge.

**Comment by Ankitasw** [comment]
+💯 Thanks for the contributions @Skarlso 🎉

**Pull request merged**
