### PR TITLE
fix: awsmachinepool use subnet filters

### PR DESCRIPTION
**Pull request by calvix**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
implements  was subnet lookup specified by filters in `AWSMachinePool.Spec.Subnets`

The previous implementation only worked with IDs, but now users can specify filters to select specific subnets that will be used for the machinepool.

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2609

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Add implementation of subnets filters for AWSMachinePool CR
```

### CODE REVIEW

**Comment by randomvariable** [comment]
I'd prefer for this to be implemented everywhere there is a Subnet currently using a AWSResourceReference, rather than having this very ad hoc implementation in this one specific CRD. It doesn't really fix the API issue we have.

I'll try and include this in the API cleanup.

**Comment by calvix** [comment]
> I'd prefer for this to be implemented everywhere there is a Subnet currently using a AWSResourceReference, rather than having this very ad hoc implementation in this one specific CRD. It doesn't really fix the API issue we have.
> 
> I'll try and include this in the API cleanup.

As far as I know, the only other resource that has reference to the subnet is AWSMachine and the machine controller already has the implementation for the filters (I used it as a template for this) 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/327e9b8a0a81d05ede3a9f61c30fef2947fa05ef/pkg/cloud/services/ec2/instances.go#L293-L320

**Comment by randomvariable** [comment]
In which case, can we dedupe the code and have it in a single plac?

**Comment by sedefsavas** [comment]
@calvix Can we try to implement a common method for all other subnets to use as @randomvariable pointed in the comment above?
We cannot have an API change but I think if we at least implement a common logic to handle filter field, it will be straightforward to fix the api in the v1beta2 release.

**Comment by AverageMarcus** [comment]
@sedefsavas @randomvariable Do you have any suggestions for how best to refactor this in a non-API-changing way? 

The inconsistencies with `AWSResourceReference` have been [long-standing](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2087) and not yet addressed in any of the API changes so would hate to have this blocked on that.

`AWAMachinePool` and `AWSMachine` are (as far as I can see) the only two types that use `AWSResourceReference` for defining subnets. The former as a slice, the later as a single pointer, so the logic between the two isn't exactly the same so I'm not sure a single function even makes sense for this.

**Comment by calvix** [comment]
@sedefsavas @randomvariable  I also think the logic between the two isn't exactly the same so I'm not sure a single function even makes sense for this. Unless you have some good suggestions on how to do that.

**Comment by shivi28** [comment]
Thank you so much @calvix for raising this PR and doing initial research/discussion to resolve #2609. 🎉 

And due to priority reasons, I also have raised a [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3255) to implement the remaining logic and feeling happy to add you as a co-author :)

**Comment by Ankitasw** [comment]
/close
in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3255

**Comment by calvix** [comment]
thanks for sorting it out :)

**Pull request closed without merging**
