### PR TITLE
:bug: wait for lb dns name to propagate before resolving

### LINKED ISSUE #5032: Load Balancer DNS resolution takes too long
/kind bug

**What steps did you take and what happened:**

This issue was discovered by @jianlinliu, @gpei, and @yunjiang29.

As the load balancer reconciliation currently stands, CAPA tries to check for LB DNS name resolution right after the load balancer is created. The DNS name resolution success is necessary for CAPA to deem the LB as ready [1].

DNS name propagation can usually take a few minutes. If we try to resolve the name too soon, we might get:

```
$ nslookup -debug lb.notvalid.address.com
Server:		127.0.0.53
Address:	127.0.0.53#53

------------
    QUESTIONS:
	lb.notvalid.address.com, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  address.com
	origin = ns-93.awsdns-11.com
	mail addr = awsdns-hostmaster.amazon.com
	serial = 1
	refresh = 7200
	retry = 900
	expire = 1209600
	minimum = 86400
	ttl = 600
    ADDITIONAL RECORDS:
------------
** server can't find lb.notvalid.address.com: NXDOMAIN
```
and the name resolution will keep failing with the cached answer for the next TTL=600s=10min.

We have observed in some systems that the TTL for LB DNS in the `us-gov-west-1` region could be as high as 900s.

```
$ dig jialiu-735f8ebd8bc9a14e.elb.us-gov-west-1.amazonaws.com; <<>> DiG 9.11.36-RedHat-9.11.36-5.el8_7.2 <<>> jialiu-735f8ebd8bc9a14e.elb.us-gov-west-1.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 27112
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1220
; COOKIE: 2caaa84d7bd004acf1e8a4aa667508daacf8365c3d922552 (good)
;; QUESTION SECTION:
;jialiu-735f8ebd8bc9a14e.elb.us-gov-west-1.amazonaws.com. IN A;; AUTHORITY SECTION:
elb.us-gov-west-1.amazonaws.com. 900 IN    SOA    ns-1151.awsdns-15.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60;; Query time: 12 msec
;; SERVER: 10.11.5.160#53(10.11.5.160)
;; WHEN: Fri Jun 21 01:00:10 EDT 2024
;; MSG SIZE  rcvd: 194
```

[1] https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controllers/awscluster_controller.go#L291-L298

**What did you expect to happen:**

To get around this problem, maybe we can wait after the LB is created until the resolution is most likely to succeed (around `2min`) before attempting the first DNS resolution. This would decrease the chance of waiting too long for the LB name to resolve due to high TTLs.

**Anything else you would like to add:**

PR to follow soon.

**Environment:**

- Cluster-api-provider-aws version: master @ 7ab0780c89fe321df2a9bebc232dd2c9b2670db4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by r4f4**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Instead of trying to resolve the primary LB DNS name right after its creation, wait for it to propagate so the resolution is most likely to succeed.

This fixes an issue where the first "no such host" cached dns response with high TTL would make CAPA spin for minutes (as high as 15!) waiting for the DNS name to resolve even though it had already propagated a few minutes after the first attempt.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5032 

**Special notes for your reviewer**:

I couldn't find a more elegant way to solve this other than a sleep after the LB is created. I wanted to add a `retryAfterDuration` [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controllers/awscluster_controller.go#L290) right after the DNS name is set and before the name resolution is attempted but it would involve somehow saving state of the timestamp in between reconcile loops.
 
**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fixed possible long wait times for primary Load Balancer DNS name resolution due to high TTL values returned in some hosts when the name resolution is attempted before the LB reaches the active state.
```

### CODE REVIEW

**Comment by r4f4** [comment]
[Openshift e2e tests](https://github.com/openshift/installer/pull/8648) show no regressions for cases with low TTL.

For example in [this run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8648/pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn/1804504744715096064/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1719066916.log) the DNS name is resolved right after the wait is done:
```
time="2024-06-22T13:57:30Z" level=debug msg="I0622 13:57:30.384416     354 loadbalancer.go:70] \"Reconciling load balancers\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\""
[...]
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.237999     354 loadbalancer.go:128] \"Created new network load balancer for apiserver\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.238015     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
[...]
time="2024-06-22T13:57:46Z" level=debug msg="I0622 13:57:46.238804     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:58:01Z" level=debug msg="I0622 13:58:01.238765     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:58:16Z" level=debug msg="I0622 13:58:16.238794     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:58:31Z" level=debug msg="I0622 13:58:31.238326     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:58:46Z" level=debug msg="I0622 13:58:46.238639     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:59:01Z" level=debug msg="I0622 13:59:01.238991     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:59:16Z" level=debug msg="I0622 13:59:16.238665     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:59:31Z" level=debug msg="I0622 13:59:31.238731     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:59:31Z" level=debug msg="I0622 13:59:31.327379     354 loadbalancer.go:1723] \"creating target group\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" group=<"
[...]
time="2024-06-22T13:59:32Z" level=debug msg="I0622 13:59:32.391053     354 awscluster_controller.go:291] \"Looking up IP address for DNS\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" dns=\"ci-op-kjphm6tx-2d061-qplhx-int-dd788fa810aeb43e.elb.us-east-1.amazonaws.com\""
time="2024-06-22T13:59:32Z" level=debug msg="I0622 13:59:32.617668     354 s3.go:256] \"Created bucket\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" bucket_name=\"openshift-bootstrap-data-ci-op-kjphm6tx-2d061-qplhx\""
```
and we can see that the secondary LB is reconciling while we wait for the dns name:
```
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.237959     354 loadbalancer.go:448] \"Created network load balancer\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" dns-name=\"ci-op-kjphm6tx-2d061-qplhx-int-dd788fa810aeb43e.elb.us-east-1.amazonaws.com\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.237988     354 loadbalancer.go:451] \"applying load balancer DNS to result\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" dns=\"ci-op-kjphm6tx-2d061-qplhx-int-dd788fa810aeb43e.elb.us-east-1.amazonaws.com\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.237999     354 loadbalancer.go:128] \"Created new network load balancer for apiserver\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.238015     354 loadbalancer.go:134] \"Waiting for network load balancer dns name to propagate\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-int\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.784769     354 loadbalancer.go:448] \"Created network load balancer\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" dns-name=\"ci-op-kjphm6tx-2d061-qplhx-ext-e309fac33c3c5cb9.elb.us-east-1.amazonaws.com\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.784798     354 loadbalancer.go:451] \"applying load balancer DNS to result\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" dns=\"ci-op-kjphm6tx-2d061-qplhx-ext-e309fac33c3c5cb9.elb.us-east-1.amazonaws.com\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.784809     354 loadbalancer.go:128] \"Created new network load balancer for apiserver\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" api-server-lb-name=\"ci-op-kjphm6tx-2d061-qplhx-ext\""
time="2024-06-22T13:57:31Z" level=debug msg="I0622 13:57:31.857784     354 loadbalancer.go:1723] \"creating target group\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-kjphm6tx-2d061-qplhx\" reconcileID=\"d8375aca-40d9-44e0-bebf-281438fc4afe\" cluster=\"openshift-cluster-api-guests/ci-op-kjphm6tx-2d061-qplhx\" group=<"
```

**Comment by AndiDog** [comment]
/lgtm

Can you please reword the changelog entry – "a possible issue" is too vague.

**Comment by r4f4** [comment]
> Can you please reword the changelog entry – "a possible issue" is too vague.

Done.

**Comment by r4f4** [comment]
@AndiDog but I think the solution in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5093 is preferable, since it uses the AWS SDK to check if the LB is active and it removes the DNS name check altogether.

**Comment by AndiDog** [comment]
Indeed, let's try and get https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5093 working.

For this PR: I don't think we should add an unconditional `sleep` in order to fix bad DNS caching configuration, unless this uses a standard DNS setup. I haven't observed this issue before, and we run CAPA on EC2 instances with the default AWS DNS server (AFAIK).

**Pull request closed without merging**
