### PR TITLE
Avoid infinite APIEndpoints

### LINKED ISSUE #880: Duplicate entries on status.apiEndpoints
/kind bug

**What steps did you take and what happened:**

While debugging an unrelated CAPA issue I noticed we have a few cluster objects that have many duplicates in the `.status.apiEndpoints` field. So far I believe this is only cosmetic.

```
$ kubectl get -n 4d95faba9cb7ee388671ac3cef6ee79b39c25f15 cluster dth-2-2 -o json | jq -r '.status.apiEndpoints[] | .host' | wc -l
    1600
$ kubectl get -n 4d95faba9cb7ee388671ac3cef6ee79b39c25f15 cluster dth-2-2 -o json | jq -r '.status.apiEndpoints[] | .host' | sort | uniq -c
   1
1599 <REMOVED>.us-west-2.elb.amazonaws.com
```

Sanitized and truncated cluster object is below. If need be, I can provide the whole object.

```
apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: "2019-07-08T19:08:06Z"
  finalizers:
  - foregroundDeletion
  - cluster.cluster.k8s.io
  generation: 3
  name: dth-2-2
  namespace: 4d95faba9cb7ee388671ac3cef6ee79b39c25f15
  resourceVersion: "23730540"
  selfLink: /apis/cluster.k8s.io/v1alpha1/namespaces/4d95faba9cb7ee388671ac3cef6ee79b39c25f15/clusters/dth-2-2
  uid: b7b20f50-a1b3-11e9-b818-0674078ea66e
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  providerSpec:
    value:
      caKeyPair:
        cert: NOPE
        key: NOPE
      clusterConfiguration:
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction,PodSecurityPolicy
        certificatesDir: ""
        controlPlaneEndpoint: ""
        controllerManager: {}
        dns:
          type: ""
        etcd: {}
        imageRepository: ""
        kubernetesVersion: ""
        networking:
          dnsDomain: ""
          podSubnet: ""
          serviceSubnet: ""
        scheduler: {}
      etcdCAKeyPair:
        cert: NOPE
        key: NOPE
      frontProxyCAKeyPair:
        cert: NOPE
        key: NOPE
      metadata:
        creationTimestamp: null
      networkSpec:
        subnets:
        - availabilityZone: us-west-2a
          cidrBlock: 10.0.0.0/24
          id: subnet-NOPE
          isPublic: false
          routeTableId: rtb-NOPE
          tags:
            Name: dth-2-2-subnet-private
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: private
        - availabilityZone: us-west-2a
          cidrBlock: 10.0.1.0/24
          id: subnet-NOPE
          isPublic: true
          natGatewayId: nat-NOPE
          routeTableId: rtb-NOPE
          tags:
            Name: dth-2-2-subnet-public
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: public
        vpc:
          cidrBlock: 10.0.0.0/16
          id: vpc-NOPE
          internetGatewayId: igw-NOPE
          tags:
            Name: dth-2-2-vpc
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: common
      region: us-west-2
      saKeyPair:
        cert: NOPE
        key: NOPE
      sshKeyName: a-keypair
status:
  apiEndpoints:
  - host: ""
    port: 6443
  - host: NOPE.us-west-2.elb.amazonaws.com
    port: 6443
  - host: NOPE.us-west-2.elb.amazonaws.com
    port: 6443

<REMOVED FOR BREVITY>

  providerStatus:
    bastion:
      ebsOptimized: false
      enaSupport: true
      id: i-NOPE
      imageId: ami-DEADBEEF
      instanceState: running
      keyName: a-keypair
      privateIp: 10.0.1.245
      publicIp: NOPE
      securityGroupIds:
      - sg-NOPE
      subnetId: subnet-NOPE
      tags:
        Name: dth-2-2-bastion
        sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
        sigs.k8s.io/cluster-api-provider-aws/role: bastion
      type: t2.micro
    metadata:
      creationTimestamp: null
    network:
      apiServerElb:
        attributes:
          idleTimeout: 600000000000
        dnsName: dth-2-2-apiserver-NOPE.us-west-2.elb.amazonaws.com
        name: dth-2-2-apiserver
        scheme: internet-facing
        securityGroupIds:
        - sg-NOPE
        subnetIds:
        - subnet-NOPE
      securityGroups:
        bastion:
          id: sg-NOPE
          ingressRule:
          - cidrBlocks:
            - 0.0.0.0/0
            description: SSH
            fromPort: 22
            protocol: tcp
            sourceSecurityGroupIds: null
            toPort: 22
          name: dth-2-2-bastion
          tags:
            Name: dth-2-2-bastion
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: bastion
        controlplane:
          id: sg-NOPE
          ingressRule:
          - cidrBlocks:
            - 0.0.0.0/0
            description: Kubernetes API
            fromPort: 6443
            protocol: tcp
            sourceSecurityGroupIds: null
            toPort: 6443
          - cidrBlocks: null
            description: SSH
            fromPort: 22
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            toPort: 22
          - cidrBlocks: null
            description: etcd
            fromPort: 2379
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            toPort: 2379
          - cidrBlocks: null
            description: etcd peer
            fromPort: 2380
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            toPort: 2380
          - cidrBlocks: null
            description: bgp (calico)
            fromPort: 179
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            - sg-NOPE
            toPort: 179
          - cidrBlocks: null
            description: IP-in-IP (calico)
            fromPort: 0
            protocol: "4"
            sourceSecurityGroupIds:
            - sg-NOPE
            - sg-NOPE
            toPort: 0
          name: dth-2-2-controlplane
          tags:
            Name: dth-2-2-controlplane
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: controlplane
        lb:
          id: sg-NOPE
          ingressRule: null
          name: dth-2-2-lb
          tags:
            Name: dth-2-2-lb
            kubernetes.io/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: lb
        node:
          id: sg-04614a5ebe79d9f1c
          ingressRule:
          - cidrBlocks:
            - 0.0.0.0/0
            description: Node Port Services
            fromPort: 30000
            protocol: tcp
            sourceSecurityGroupIds: null
            toPort: 32767
          - cidrBlocks: null
            description: SSH
            fromPort: 22
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            toPort: 22
          - cidrBlocks: null
            description: Kubelet API
            fromPort: 10250
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            - sg-NOPE
            toPort: 10250
          - cidrBlocks: null
            description: bgp (calico)
            fromPort: 179
            protocol: tcp
            sourceSecurityGroupIds:
            - sg-NOPE
            - sg-NOPE
            toPort: 179
          - cidrBlocks: null
            description: IP-in-IP (calico)
            fromPort: 0
            protocol: "4"
            sourceSecurityGroupIds:
            - sg-NOPE
            - sg-NOPE
            toPort: 0
          name: dth-2-2-node
          tags:
            Name: dth-2-2-node
            sigs.k8s.io/cluster-api-provider-aws/cluster/dth-2-2: owned
            sigs.k8s.io/cluster-api-provider-aws/role: node

```

**Environment:**

- Cluster-api-provider-aws version: 0.3.1
- Kubernetes version: (use `kubectl version`): 1.12.5

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR fixes an issue where the first reconciliation loop assigns APIEndpoints.Host to an empty string because the ELB might not be ready, and it'll start appending after that. The logic here changes to always have a single APIEndpoint and update if needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #880

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ncdc** [comment]
Release note?

/lgtm

**Comment by vincepri** [comment]
@ncdc We don't have the plugin to gen the release notes, so we'll have to type the manually anyways. I'd like to start using it if we can

**Comment by ncdc** [comment]
@vincepri true, but it's a good habit to have, even if we don't have the plugin.

Can you do the backport PR to 0.3?

**Pull request merged**
