### PR TITLE
[wip] :running: Attempt to run e2e tests in parallel

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Use ginkgo command line tool to run e2e tests in parallel

### CODE REVIEW

**Comment by detiber** [comment]
TODO: need to move the cloud formation template setup/teardown from BeforeSuite/AfterSuite into SynchronizedBeforeSuite/SyncronizedAfterSuite

**Comment by detiber** [comment]
TODO: identify tests that must be run in parallel (i.e. ones that check behavior with quota exhaustion)

**Comment by detiber** [comment]
TODO: pass access key through the []byte interface for SerializedBeforeSuite

**Comment by randomvariable** [comment]
running up against the VPC limit test. maybe need to run that one on its own somehow, or rethink what we're actually trying to test there.

**Comment by jayunit100** [comment]
Definetly looks like alot of infra related breakage here.  just getting up to speed.

```
• Failure [0.006 seconds]
functional tests
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:105
  multiple workload clusters
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:277
    in same namespace
skipped 16 lines unfold_more
creating namespace "test-iifo73"
STEP: Deleting the Clusters
Deleting Cluster /
• Failure [0.006 seconds]
functional tests
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:105
  multiple workload clusters
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:277
    in same namespace
skipped 17 lines unfold_more
STEP: Deleting the Clusters
Deleting Cluster test-fyu2lw/test-pinq0k
Deleting Cluster /
• Failure [270.086 seconds]
functional tests
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:105
  multiple workload clusters
  /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:277
    in different namespaces
    /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:278
      should delete both clusters [It]
      /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/aws_test.go:293
      Expected success, but got an error:
      
```

**Comment by jayunit100** [comment]
So the reason this was failing, seems to be as follows:
- `Before` is being called, correctly before `It`
- However, alas, Before is non-blocking :) which means that the call to `createNamespace` which is inherently going to return in a non-deterministic amount of time, may not finish by the time that the `It` clauses are triggered. 

The solution is to block i.e. have the call to BeforeEach write to a channel, or else, just call the logic in BeforeEach every time we run a test, since its really something that can easily just be recalled at any time (mostly stateless and random)

**Comment by jayunit100** [comment]
concurrency issues w/ the namespaces is fixed, but tests still failing.
im going to bounce the build again make sure its not a flake.

**Comment by detiber** [comment]
Closing in favor of the work that @jayunit100 is doing
/close

**Pull request closed without merging**
