### PR TITLE
:seedling: Align dependabot config with upstream cluster-api

### PR DESCRIPTION
**Pull request by vincepri**
**What type of PR is this?**

**What this PR does / why we need it**:

/kind cleanup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm
Thanks!

**Comment by nrb** [comment]
Not that it's needed, but also

/lgtm

**Comment by vincepri** [comment]
need another lgtm 😄 added `release-note-none` as well, so we don't have to manually modify the PR description

**Pull request merged**
