### PR TITLE
[Release-1.5] Removed io/ioutil import

### PR DESCRIPTION
**Pull request by AverageMarcus**
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Linting currently fails on any backported PRs due to the use of `io/ioutil` 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

See failing test on this PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3988/

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
FWIW `/ok-to-test` -> you don't need this. :)

/lgtm

**Comment by AverageMarcus** [comment]
> FWIW /ok-to-test -> you don't need this. :)

I didn't think I did but wasn't 100% sure as the label wasn't there. 🤷

**Pull request merged**
