### PR TITLE
fix error validating message

### PR DESCRIPTION
**Pull request by zirain**
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
fix error validating message of AWSCluster.Spec.NetworkSpec.VPC.ID

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
/ok-to-test

Hello. :) Nice catch, thanks! :)

**Comment by zirain** [comment]
@Skarlso what need I do to make this PR forward?

**Comment by Skarlso** [comment]
Hello. It's a code freeze right now because our testing infrastructure isn't in a nice shape. As soon as it's lifted this and others can be merged.

**Comment by zirain** [comment]
got it, thanks!

**Pull request merged**
