### PR TITLE
DNM: e2e-eks: debug EKS invalid awsmanagedmachinepool spec.roleName

### PR DESCRIPTION
**Pull request by damdo**
Debug EKS e2e issue:
```
[managed] [general] [ipv6] EKS cluster tests [It] should create a cluster and add nodes
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/shared/common.go:231
  [FAILED] Unexpected error:
      <errors.aggregate | len:1, cap:1>: 
      admission webhook "validation.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io" denied the request: AWSManagedMachinePool.infrastructure.cluster.x-k8s.io "eks-nodes-14zug4-pool-0" is invalid: spec.roleName: Invalid value: "": field is immutable
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5093/pull-cluster-api-provider-aws-e2e-eks/1849186934245560320

/hold

### CODE REVIEW

**Comment by damdo** [comment]
It looks like EKS E2Es are permafailing with https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5179/pull-cluster-api-provider-aws-e2e-eks/1849350227388010496

/cc. @kubernetes-sigs/cluster-api-provider-aws-maintainers

**Comment by richardcase** [comment]
@damdo - it would be worth rebase and running the eks e2e to check it solves the issue yiu where seeing.

**Comment by damdo** [comment]
Cool done, let's see

**Comment by richardcase** [comment]
The main thing is that the EKS e2e are passing on this.

There is still some flakiness in the non-EKS e2e. So if that fails I wouldn't worry 😁

**Comment by richardcase** [comment]
And thank you @damdo for the rebase and testing it again.

**Comment by damdo** [comment]
> The main thing is that the EKS e2e are passing on this.
There is still some flakiness in the non-EKS e2e. So if that fails I wouldn't worry 😁

Yeah indeed. Ah yes I was trying to make sure they were only flakes. Makes sense to me, closing this as it served it purpose 👍

**Pull request closed without merging**
