### PR TITLE
feat: add support for EKS addon configuration

### LINKED ISSUE #4226: Support EKS Addons custom configuration
/kind feature

**Describe the solution you'd like**
EKS addons now support custom configuration. ref: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks#CreateAddonInput 

**Anything else you would like to add:**
 For our use case, we need to modify env vars that are part of the VPC CNI in order to support eni/pod security groups.  

**Environment:**

- Cluster-api-provider-aws version: 2.0.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by synthe102**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

This change allows to configure EKS Addons directly from CAPA.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Closes #4226 by adding support for EKS addon configuration.

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
feat: add support for EKS addon configuration
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
Hey @synthe102 , thanks for adding this support.
It would be good to add the configuration in EKS E2E tests so that its tested in CI as well.

**Comment by synthe102** [comment]
> Hey @synthe102 , thanks for adding this support. It would be good to add the configuration in EKS E2E tests so that its tested in CI as well.

Ok ! I'll write a test for that 👍

**Comment by synthe102** [comment]
> > Ok ! I'll write a test for that 👍
> 
> Thankyou 🙂 i think you dont have to write whole test, just the existing add-on test in EKS could have additional configurations added in manifests.

Hey !
I extended the addon test suite to check if an addon config matches the supplied configuration only if the configuration is provided.
The suite ran successfully when I tested it.

**Pull request merged**
