### PR TITLE
Fix go1.19 linting errors

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What type of PR is this?**

**What this PR does / why we need it**:

With https://github.com/kubernetes/test-infra/pull/26920 our test image has been changed to go1.19-rc2. Therefore, we have to fix some linters and deprecations to make the linter happy again (analogues to https://github.com/kubernetes/kubernetes/pull/111254).

Failed test as example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3609/pull-cluster-api-provider-aws-test/1552246150055071744

Regarding the `ioutil` deprecation, please see https://github.com/go-critic/go-critic/issues/1019

```
❯ docker run -ti --entrypoint bash gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220726-61b7bafca6-master
[...]
root@a4f4d8285e82:/workspace# go version
go version go1.19rc2 linux/amd64
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Replaced all boilderplates with

```bash
grep -rl 'http://www.apache.org/licenses/LICENSE-2.0' | grep -E '\.go$' | while read file; do
  sed -ri 's#^    (http://www.apache.org/licenses/LICENSE-2.0)#\t\1#' $file
done
```

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by tobiasgiese** [comment]
> I see that even the generated files needed to change, let's see if `make verify` will pass.

You are right, I have to replace the `hack/boilerplate/boilerplate.go.txt` as well! Good catch 🙂

**Comment by richardcase** [comment]
Why are we changing all the licence headers as part of this?

**Comment by richardcase** [comment]
Thanks @tobiasgiese, I wish we'd followed the gofmt formatting rules earlier :rofl: 

From my side:

/lgtm

For approval:

/assign sedefsavas

**Pull request merged**
