### PR TITLE
Added files to fix broken links mentioned in issue #3453 and #3575

### PR DESCRIPTION
**Pull request by MaheshMoholkar**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Some doc files were being shared between this and cluster-api repository. So many links were broken due to relative paths used in the docs. I have added those files from cluster-api in this repository.
This PR fixed issues #3453 and #3575 
**Special notes for your reviewer**:
Let me know if there are any more changes expected.
**Checklist**:

- [ ] squashed commits
- [x ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by oscr** [comment]
@Mahesh1822 I'm not in the review team so take my opinion with a grain of salt. But I don't think it's a good solution to copy the whole CAPI book. It would require massive amounts of work to keep it in sync with CAPI. 

I suggest to either just link to the CAPI book Quick Start instead of embedding it, or copying just the Quick Start and updating it. But it's @dthorsen or @pydctw call

**Comment by Mahesh1822** [comment]
@oscr Yeah i thought I would keep it updated on regular basis. No worries I will just link it to the CAPI book.

**Comment by Ankitasw** [comment]
@Mahesh1822 thanks for the PR
You might want to just add the links to these docs and not the content from the docs, it will cause the duplication and makes docs huge.

**Comment by Mahesh1822** [comment]
@ Ankitasw yeah i did the changes yesterday, now it just has links to these docs.

**Comment by Ankitasw** [comment]
> @ Ankitasw yeah i did the changes yesterday, now it just has links to these docs.

I still see you old changes only, with whole content, and not the link.

**Comment by Mahesh1822** [comment]
I reverted back the changes and just copied getting-started.html file and replaced all link to CAPI book.

**Comment by Mahesh1822** [comment]
> > @ Ankitasw yeah i did the changes yesterday, now it just has links to these docs.
> 
> I still see your old changes only, with whole content, and not the link.
Untitled

**Comment by Ankitasw** [comment]
> I reverted back the changes and just copied getting-started.html file and replaced all link to CAPI book.

This is not expected here, we only want to mention and fix broken links, no need of pasting whole content from Cluster API book, as it will duplicate the content, would it be possible for you to fix the broken links only and not add new contents?

**Comment by Mahesh1822** [comment]
I don't know how I can fix broken links bcoz they are present in cluster-api repo. To fix them I had to at least copy getting-started file. Let me know what to do or I will just close the PR.

**Pull request closed without merging**
