### PR TITLE
✨ Add natgatewayips as source for ingress rules

### PR DESCRIPTION
**Pull request by alexander-demicev**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR will allow using nat gateway IPs as sources in ingress rules. In my setup, I need machines to be able to connect to the load balancer through a certain port and I would like the load balancer to only accept traffic for this port from my machines. From the load balancer point of view the connection is made from nat gateway IPs so the CAPA API has to have a setting for this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Add natgatewayips as source for ingress rules
```

### CODE REVIEW

**Comment by alexander-demicev** [comment]
@nrb @damdo folks, can I get a review? all tests are passing

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm
/hold

to give reviewers in the repo chance to take a look

**Review by damdo — COMMENTED** [review]
Thanks Alex
/lgtm
/unhold

**Pull request merged**
