### PR TITLE
fix: malformed s3 arn due to incorrect string formatting

### PR DESCRIPTION
**Pull request by Skarlso**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes a problem introduced by merging https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4010

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix incorrect s3 bucket ARN formatting.
```

### CODE REVIEW

**Review by wilderk — APPROVED** [review]

**Comment by Skarlso** [comment]
Test failure is the remediation test. The one that was failing is fixed.

**Review by luthermonson — APPROVED** [review]
/lgtm

**Pull request merged**
