### PR TITLE
 🌱 Remove unused allow additional roles feature flag related code

### PR DESCRIPTION
**Pull request by Evalle**
**What this PR does / why we need it**:
- Removes unused allow additional roles feature flag related code

**Which issue(s) this PR fixes**
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2001

### CODE REVIEW

**Comment by Evalle** [comment]
@richardcase also, may I ask you to add "hacktoberfest-accepted" label to this PR? If it's not a big deal, of course. Thx!

**Comment by Evalle** [comment]
Thanks @randomvariable, appreciated!

**Review by arghya88 — COMMENTED** [review]
/lgtm

**Comment by Evalle** [comment]
Hey folks, could please re-review, there was a merge conflict, thanks!
@arghya88 @richardcase

**Pull request merged**
