### PR TITLE
✨Fine tune e2e-conformance and ci-conformance.sh

### PR DESCRIPTION
**Pull request by dims**
- pass through params from CI through ci-conformance.sh to the
  e2e-conformance.sh
- Add checks for mandatory AWS env vars
- Add more logs to what we are dumping already

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
@dims this lgtm, but you mention "Add a loop to process arguments in e2e-conformance.sh" in the description and I don't see that in the actual changes proposed.

**Comment by dims** [comment]
Thanks, removed that line from description :)

**Pull request merged**
