### PR TITLE
Replace all AWS SDK calls with their WithContext analogs

### LINKED ISSUE #4504: Pass context from Reconcile functions to AWS requests
/kind feature

**Describe the solution you'd like**
Currently we do not transfer the Context further at the time of reconciliation. This makes it difficult to map Reconcile function calls to requests to AWS, which limits our ability to monitor the operation of CAPA in runtime.

It would be nice to to pass through Context top-down, so we can use it in OpenTelemetry to generate more detailed traces.

Working items:
- [ ] Migrate AWS Reconcile function calls to their WithContext equivalents (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4490)
- [ ] Change `context.TODO()` values to real contexts.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Fedosin**
**What type of PR is this?**
/kind support

**What this PR does / why we need it**:
This is the first PR in a series.

Now we don't pass context from `Reconcile` functions to AWS SDK calls, which limits our ability to trace requests using OpenTelemetry. To improve this we want to start passing context from top to bottom.

In this PR we just replace AWS SDK calls with their `WithContext` analogs, so that they can accept a context parameter. In the following PRs we are going to start passing context from `Reconcile` to the SDK calls.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partially-Fixes #4504

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by Ankitasw — COMMENTED** [review]
We are not passing the context top down still. all the contexts are TODO, so it still not serve the purpose that is stated in the PR

**Comment by Fedosin** [comment]
@Ankitasw yeah, you are right, the description is a bit confusing. I updated it to make it more explicit that in this PR we just replace SDK calls, and all work about passing contexts will be done in the following PRs.

**Comment by nrb** [comment]
Given that this is the first step in a series of work, replacing the calls with their context-aware equivalents and `context.TODO()` seems reasonable to me. Skimming the changes, this PR appears to be fairly low risk, though I did not dig into the test changes yet.

**Comment by Ankitasw** [comment]
@Fedosin if this is going to be a series of PR, can we have a consolidated issue created with the task list?

**Comment by Fedosin** [comment]
Thanks folks! I created an issue for this work: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4504

**Comment by Ankitasw** [comment]
@Fedosin thanks @Fedosin , if you have a plan of work, could you mention all the work items in above issue?

**Comment by nrb** [comment]
Not an official reviewer, but I did another pass focusing on the tests, and this appears to pretty much be straight replacements like I mentioned before.

There are some functions that are expanded to receive `requestOptions`, but again this PR looks pretty low risk.

LGTM aside from some tracking requests on the issue.

**Pull request merged**
