### PR TITLE
Add Cluster Upgrade tests based on ClusterClass

### PR DESCRIPTION
**Pull request by pydctw**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add Cluster Upgrade tests based on ClusterClass

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #3346 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
As per the discussion on [slack thread](https://kubernetes.slack.com/archives/CD6U2V71N/p1653503446220579), hold until office hours.

For example, here, we don't need to 2 varieties, just HA cluster upgrade with workers provides good coverage all. 
This will reduce the time to get test signal as well.

/hold

**Comment by sedefsavas** [comment]
/hold cancel

let's get this merged, then we can consolidate.

/test ?

**Comment by pydctw** [comment]
> let's get this merged, then we can consolidate.

Consolidated two tests to one: upgrade with HA control + workers while rebasing.

**Comment by pydctw** [comment]
Test passed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3472/pull-cluster-api-provider-aws-e2e-clusterclass/1557827318334885888

/hold cancel

**Pull request merged**
