### PR TITLE
Bump Cluster API version in CAPA, e2e eks and test config

### LINKED ISSUE #3112: Update cluster-api to 1.1.0-rc.0
We should bump cluster-api and cluster-api-test modules and update e2e test config.

### PR DESCRIPTION
**Pull request by shivi28**
**What type of PR is this?**
/kind support

**What this PR does / why we need it**:
This PR bumps CAPI version from `v1.1.0-beta.1` to `v1.1.0-rc.0` in CAPA, e2e test config, eks e2e test config.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3112 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Bump Cluster API version to v1.1.0-rc.0 in CAPA 
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
/lgtm
/approve

/hold

Let's run both eks and unmanaged e2e tests on this one and then feel free to remove hold.

**Comment by shivi28** [comment]
> @shivi28: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-cluster-api-provider-aws-e2e	[c5fd764](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/c5fd764e802eef3601160dbc9f112d5c861be4d7)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3129/pull-cluster-api-provider-aws-e2e/1488783505281257472)	false	`/test pull-cluster-api-provider-aws-e2e`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=cluster-api-provider-aws&pr=3129). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Ashivi28). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is:issue+is:open) when you hit one in your PR.

checking in local

**Comment by sedefsavas** [comment]
Closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3135

**Pull request closed without merging**
