### PR TITLE
🐛 [0.4] Fix IMAGE_ID issue in examples

### LINKED ISSUE #1300: in release-0.4 branch make create-cluster-management fails
/kind bug

**What steps did you take and what happened:**
in branch `release-0.4` running `make create-cluster-management` produces the following error:

```unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
Makefile:310: recipe for target 'create-cluster-management' failed
make: *** [create-cluster-management] Error 1
```

**What did you expect to happen:**
`make create-cluster-management` to successfully create a development Kubernetes cluster on AWS in a KIND management cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: release-0.4
- Kubernetes version: (use `kubectl version`):  `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): ubuntu

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Remove the ${IMAGE_ID} placeholder from the examples, as it's only used
for e2e conformance testing, and it's broken for example usage.

Use kustomize patches to handle the IMAGE_ID for e2e testing instead.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1300

### CODE REVIEW

**Comment by ncdc** [comment]
I'd like to run the e2e conformance test to make sure this doesn't break provisioning

**Comment by ncdc** [comment]
Looking good so far:
```
[16:05:16] Total machines : 5 / Running : 0 .. waiting for 10 seconds
+ sleep 10
+ attempt=4
+ true
++ kind get kubeconfig-path --name=clusterapi
+ kubectl get machines --kubeconfig=/root/.kube/kind-config-clusterapi
NAME                          PROVIDERID                    PHASE
test1-controlplane-0          aws:////i-0cf44f81b75e43549   provisioned
```

**Comment by ncdc** [comment]
All 5 machines are running and the conformance tests have started

**Comment by ncdc** [comment]
@dims does this look ok to you?

**Comment by dims** [comment]
@ncdc yes it does! thanks.

/lgtm

feel free to remove hold when appropriate

**Pull request merged**
