### PR TITLE
fix: remove unsupported remediation e2e test

### PR DESCRIPTION
**Pull request by Skarlso**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Remove unsupported remediation e2e test.
```

### CODE REVIEW

**Comment by richardcase** [comment]
Would be good to get @Ankitasw thoughts on this. 

To get green:

/lgtm
/approve

**Comment by Ankitasw** [comment]
Hey @Skarlso , wanted to understand how this is an unsupported test? I think only unsupported test for machine remediation is kcp remediation test which has not been included in this test.

**Comment by Skarlso** [comment]
@Ankitasw I thought based on this conversation we are going to ignore this test: https://kubernetes.slack.com/archives/C8TSNPY4T/p1680525266510109

As it requires a lot of fiddling on our part and there is no real benefit to it.

**Comment by Ankitasw** [comment]
That was kcp remediation test which i added in my capi bump PR, i removed that test already in that PR, so this is the actual md remediation test that remains same.

**Comment by Skarlso** [comment]
@Ankitasw okay. So then we need to understand why this test isn't working, or the remediation isn't working in CAPA. :/

**Comment by richardcase** [comment]
@Ankitasw @Skarlso - do we need this change?

**Comment by Skarlso** [comment]
I guess not then.

**Pull request closed without merging**
