### PR TITLE
[PROPOSAL]  add luther as reviewer

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

It's proposed that we make @luthermonson a reviewer of CAPA. Please indicate agreement by `lgtm`, comment or 👍 

This will be open for 1 week for consensue (and until after the next office hours call). With a view to merge 8th March 2023

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Add Luther as a reviewer
```

/cc @Ankitasw @Skarlso @dlipovetsky

### CODE REVIEW

**Comment by richardcase** [comment]
Until we have consensus:

/hold

**Comment by Skarlso** [comment]
/lgtm

:)

**Comment by Ankitasw** [comment]
💯 from my side. Luther has been contributing significantly to CAPA.

**Comment by luthermonson** [comment]
thanks everyone, appreciate the opportunity to help

**Pull request merged**
