### PR TITLE
Adding tags to AWS Network Interfaces

### LINKED ISSUE #3839: EC2 ENIs are not being tagged
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Create a MachineDeplyoment with the following AWSMachineTemplate

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: example
spec:
  template:
    spec:
      additionalTags:
        creator: test@test.com
      instanceType: t3.medium
      sshKeyName: ""
**What did you expect to happen:**

I expect the ENIs to be tagged with the additionalTags value

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v1.5.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by vishu2498**
**What type of PR is this?** /kind feature

**What this PR does / why we need it**: While and after creation of ec2 instances, the network interfaces attached to those ec2 instances didn't have any tags. This PR adds the similar tags of the ec2 instance to the attached network interface.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3839 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by vishu2498** [comment]
Hi @richardcase and @sedefsavas .
Can you help review this PR?

**Comment by Skarlso** [comment]
Interesting approach.
/ok-to-test

Please include a manual test to see if this thing works. There was a problem getting all network interfaces since many things created them. But eventually, I guess they should end up on an instance. So I believe this might be a good enough approach for most scenarios.

**Comment by Skarlso** [comment]
/assign

Also, related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3839

**Comment by Skarlso** [comment]
@vishu2498 Can you pleas take a look at the failing test? :) I'm keen on getting this one in. :)

**Comment by vishu2498** [comment]
Hey @Skarlso . The tests are fixed. Can you please check and merge?

**Comment by Skarlso** [comment]
Looks okay! Can you please include an output of a manual run with a screenshot of the tags that have been applied to the ENI? Thanks!

Also this is post creation so I guess it won't affect issues like enis need to have certain tags upon creation. But that's fine. That's a different problem altogether.

**Comment by vishu2498** [comment]
@Skarlso These are the tags that got applied to ENI. Attaching tags of both EC2 instance and ENI:

Screenshot 2022-12-28 at 5 09 07 PM
Screenshot 2022-12-28 at 5 09 31 PM

**Comment by Skarlso** [comment]
/lgtm
/approve
/hold
until tests

**Comment by Skarlso** [comment]
@Ankitasw Looks like the dump didn't work. :(

```

  [PANICKED] Test Panicked
  In [SynchronizedAfterSuite] at: /usr/local/go/src/runtime/panic.go:260 @ 12/28/22 16:36:06.716
  runtime error: invalid memory address or nil pointer dereference
  Full Stack Trace
    sigs.k8s.io/cluster-api-provider-aws/v2/test/e2e/shared.DumpEKSClusters({0x3348198?, 0xc00005c140?}, 0xc00062a160)
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/shared/aws.go:862 +0x3f
    sigs.k8s.io/cluster-api-provider-aws/v2/test/e2e/shared.Node1AfterSuite(0xc00062a160)
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/shared/suite.go:267 +0x65
    sigs.k8s.io/cluster-api-provider-aws/v2/test/e2e/suites/unmanaged.glob..func10()
    	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/unmanaged/unmanaged_suite_test.go:59 +0x25 
```

**Pull request merged**
