### PR TITLE
Switch dep to use release-0.1 branch instead of version

### LINKED ISSUE #415: Binary for automating HA cluster creation
/kind feature

**Describe the solution you'd like**

Automate the manual process that was defined for #414 

This can be built into clusterawsadm or provided as a separate binary.

/priority important-soon

### PR DESCRIPTION
**Pull request by sfzylad**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #415 

**Special notes for your reviewer**:

**Note**: This PR doesn't solve #415, so please do not close it.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
@sfzylad I don't see the updated vendor files in this PR

**Comment by sfzylad** [comment]
> @sfzylad I don't see the updated vendor files in this PR

@detiber Right, I amended my commit. Sorry for the confusion.

**Pull request merged**
