### PR TITLE
[PROPOSAL] Reviewer and maintainer changes

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR makes the following changes:

- @cnmcavoy moves to reviewer
- @nrb moves to reviewer
- @faiq moves to reviewer
- @vincepri moves from emeritus to maintainer
- @shivi28 moves to emeritus reviewer
- @dthorsen moves to emeritus reviewer
- @pydctw moves to emeritus reviewer
- Updates the owner alias with changes in CAPI / SIG cluster lifecycle leads

> For anyone moving to emeritus, if you feel you want to move back to reviewer in th efuture feel free to reach out to any of the maintainers to discuss.

**Release note**:

```release-note
Maintainer and reviewer changes.
```

### CODE REVIEW

**Comment by enxebre** [comment]
+1

**Comment by Skarlso** [comment]
+1

**Comment by Ankitasw** [comment]
Huge +1 from my side!!!

**Comment by richardcase** [comment]
@enxebre @Skarlso @Ankitasw - Thanks for your +1 on moving @cnmcavoy to reviewer. The PR has now been updated with some additional changes:

- @nrb moves to reviewer
- @faiq moves to reviewer
- @vincepri moves from emeritus to maintainer

Feel free to leave comments on these additional proposed changes.

**Comment by dlipovetsky** [comment]
+1

**Comment by richardcase** [comment]
After lazy concensus:

/unhold
/approve

**Pull request merged**
