### PR TITLE
chore: updated header verify to support go 1.17 build contraints

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Go 1.17 introduces a new format for build constrants, see the following:

https://golang.org/doc/go1.17
https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

And files formatted using `go fmt` will be changed to use the new
format. For example in our e2e test files:

```go
//go:build e2e
// +build e2e
```

This change updates the header verification to strip out the new build
constraint tag.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
Until we update to 1.17:

/hold

**Comment by randomvariable** [comment]
I think we'll bump the Go version in v1beta1 (take a look at Vince's email to sig cluster lifecycle)

**Comment by randomvariable** [comment]
Update on this. This will happen when we go to v1

**Comment by randomvariable** [comment]
Actually think this is ok to merge, as long as it still builds on Go 1.16. `make verify` will still catch generated files created with a too new Go release.

/lgtm
/approve

**Pull request merged**
