### PR TITLE
[release-1.5] Manual cherry pick of linter fixes (#3617 and #3623)

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
This fails because CC and regular cluster tests are using same identity names in e2e tests. This is a known issue. We did not change it because we will not run those tests in the same job.

**Comment by richardcase** [comment]
> This fails because CC and regular cluster tests are using same identity names in e2e tests. This is a known issue. We did not change it because we will not run those tests in the same job.

So we are good to approve this?

**Comment by sedefsavas** [comment]
Yes, this is good to go @richardcase

**Comment by tobiasgiese** [comment]
/lgtm

thanks @sedefsavas! 🙂

**Pull request merged**
