### PR TITLE
🏃 enable <unused> linter rule and fix related issues

### LINKED ISSUE #1537: cleanup: enable `unused` linter
After #1535, we updated the golangci-lint to the latest version and matched the upstream Cluster API format for the linter, it seems there were a bunch of linters missing.

- Head over to [.golanci-lint.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/.golangci.yml) in the root of this repository.
- Remove the linter from the `linters.disable` list.
- Run `make lint-full`.
- Fix the reported errors with the suggestions.
- Submit a PR with the changes.

Feel free to reach out at any time if you need guidance or help.

/kind cleanup
/help
/good-first-issue
/milestone Next
/priority backlog

### PR DESCRIPTION
**Pull request by ernestas2k**
**What this PR does / why we need it**:
Enabled 'unused' linter rule and fixes these violations. Since the only violation is in `cmd/release/' and this functionality is not used, this pull request removes the directory and associated release documentation.

**Which issue(s) this PR fixes**
Fixes #1537

### CODE REVIEW

**Comment by chuckha** [comment]
/ok-to-test

@ernestas2k please follow the bot instructions for signing the CNCF CLA

**Comment by ernestas2k** [comment]
I signed it

**Comment by chuckha** [comment]
/approve

/assign @detiber @vincepri @ncdc 
for lgtm

**Comment by detiber** [comment]
lgtm, but I haven't done releases for a few go rounds. Not sure if @ncdc or @vincepri have been using this.

**Comment by ncdc** [comment]
I have not been using this release tool, but I think it would make more sense to split its removal into a standalone PR?

**Comment by detiber** [comment]
> I have not been using this release tool, but I think it would make more sense to split its removal into a standalone PR?

The release tool is the only thing blocking the use of the `unused` linter

**Comment by ncdc** [comment]
Heh, just read the comment at the top. Never mind!

**Pull request merged**
