### PR TITLE
:sparkles: Add support for updating outdated managed routes

### LINKED ISSUE #1413: Machine phase stuck in "provisioned" after NAT gateway reconcilation
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Created a workload cluster with a single ControlPlane and a MachineDeployment with 2 replicas
2. Manually deleted the NAT Gateway of the cluster
3. Tried to create a new MachineDeployment within the same cluster

**What happened**:
1. A new NAT gateway gets created
2. New EC2 instances created and running
3. The machines are stuck in "provisioned" phase.
4. Hence not able to see the new nodes as part of the workload cluster

**What did you expect to happen:**
1. New NAT gateway gets created
2. All the machines of the new MachineDeployment in "running" phase

**Environment:**

- Cluster-api-provider-aws version: 0.4.7
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.10

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1413

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold
pending second approval
/lgtm

Just wondering, there's quite a bit of nesting going on there, if there's a way to make it easier to read, particularly [this conditional](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1421/files#diff-d72086144e2d4e57e6102205cbdf4d4bR80-R82).

**Comment by vincepri** [comment]
We can refactor it later if there is a need. It looks ugly, but I think the comment captures what we're trying to do, wdyt?

**Comment by randomvariable** [comment]
Yup, more of a nit.

**Pull request merged**
