### PR TITLE
:running: Update project maintainers and reviewers

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

Waiting for a few other folks to see if they want to step up.
/hold

### CODE REVIEW

**Comment by vincepri** [comment]
Got confirmation from all parties that this change is ok

**Comment by ncdc** [comment]
Do you want to merge this now, or keep waiting?

**Comment by detiber** [comment]
> Do you want to merge this now, or keep waiting?

Have we given this sufficient time/visibility for community review? I don't believe it was discussed at the weekly meeting last week, and I don't think we made an announcement on the mailing list.

**Comment by ncdc** [comment]
I don't know (hence the question). It looks like it's just about promoting @rudoi from reviewer to maintainer, and adding @randomvariable as a maintainer (the removals have all been acked, according to @vincepri).

**Comment by vincepri** [comment]
I've confirmed with all the parties, I'm ok waiting but next week is also KubeCon. I'd rather just merge it if we have consensus.

**Comment by detiber** [comment]
> I've confirmed with all the parties, I'm ok waiting but next week is also KubeCon. I'd rather just merge it if we have consensus.

Confirming with all parties is fine, but without broader awareness in the community can we truly say we have consensus (or rather lazy consensus, since that is our standard)?

We can't expect all community members to watch all issues for the repo.

**Comment by vincepri** [comment]
@detiber I'm ok either way, I'll leave it up to you.

**Comment by rudoi** [comment]
I think we should give it the full week. I can't think of any real benefit to merging early, even with the conf next week.

**Comment by rudoi** [comment]
what about now? :D

**Comment by ncdc** [comment]
This has been open for 18 days. I'm saying we have lazy consensus.
/lgtm

**Pull request merged**
