### PR TITLE
add identity ref support for fargate controller

### PR DESCRIPTION
**Pull request by jzhoucliqr**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Add identity reference provider support for fargate controller

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
I think we should backport this. WDYT @richardcase?

**Comment by richardcase** [comment]
> I think we should backport this. WDYT @richardcase?

@sedefsavas  - yes i agree we should backport this.

**Comment by richardcase** [comment]
Thanks for this change @jzhoucliqr, this looks good so:

/lgtm

**Comment by sedefsavas** [comment]
@jzhoucliqr Could you backport this to release0.6 branch?

**Comment by jzhoucliqr** [comment]
> @jzhoucliqr Could you backport this to release0.6 branch?

Done. Thanks.

**Pull request merged**
