### PR TITLE
Test conformance with ci releases on HA control plane

### PR DESCRIPTION
**Pull request by sedefsavas**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
We can merge this and make conformance tests run on a HA cluster after this issue is resolved:
https://kubernetes.slack.com/archives/CEX9HENG7/p1655475223796599

**Comment by Ankitasw** [comment]
I think this is in CAPI v1.2.2.  @sedefsavas do you want to continue the PR?

**Pull request closed without merging**
