### PR TITLE
:seedling: Update awsmachinetemplate_webhook.go, fix typo

### PR DESCRIPTION
**Pull request by guettli**
fix typo from VSphere.

**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix typo in awsmachinetemplate_webhook logs
```

### CODE REVIEW

**Comment by richardcase** [comment]
Thanks for this @guettli . Could you add a release notes block to the PR description?

**Review by AndiDog — COMMENTED** [review]
/lgtm

**Comment by guettli** [comment]
> Thanks for this @guettli . Could you add a release notes block to the PR description?

I don't think this should be in the release notes. 

I am unsure what you want exactly. Maybe it is better if you take the PR, adapt it the way you want it to be and then merge it.

**Pull request merged**
