### PR TITLE
🏃Add automation to test cluster creation with name length more than 22 characters

### PR DESCRIPTION
**Pull request by sirao**
Added automation to test creating cluster with name more than 22 characters.

Verifies that Cluster provisioned and control plane initialized

### CODE REVIEW

**Comment by ncdc** [comment]
Is this meant to replace #1374?

**Comment by sirao** [comment]
> Is this meant to replace #1374?

@ncdc Yes. This is to replace #1374

**Comment by detiber** [comment]
/lgtm
/approve
Failing e2e tests are not related to this job and are known to be somewhat flaky.

**Pull request merged**
