### PR TITLE
fix: managed machine pool correct min/max size

### LINKED ISSUE #2318: Managed machine pool doesn't correct min/max size
/kind bug
/area provider/eks
/help
/milestone v0.6.5

**What steps did you take and what happened:**
1. create a EKS cluster with a managed machine pool and set the min (2) and max size (3) of the **AWSManagedMachinePool** and the replicas (2) on the **MachinePool**
2. Wait for the cluster and node group to be ready
3. Go to the AWS console and edit the node group and change the max size to 5
4. Watch the nodegroup to see if its max size is changed back to 3

**What did you expect to happen:**
I would expect CAPA to detect that the nodegroup has a max size (5) that is different to the declared max size (3) ands perform an update on the nodegroup to bring in down to a maxsize of 3. I would also like to see an error and event raised on the **AWSManagedMachinePool** indicating that this had been changed externally.

**Anything else you would like to add:**
[This is the existing logic](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/5d3c76211239b3700d1f69a36c7819f94c5b2609/pkg/cloud/services/eks/nodegroup.go#L342:L349) that needs to be changed.

We must have action required release note as this is a behaviour change that users need to be made aware of.

Sample definitions if needed:

```yaml
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: "wkp-mgmt01-pool-0"
spec:
  clusterName: "wkp-mgmt01"
  replicas: 2
  template:
    spec:
      clusterName: "wkp-mgmt01"
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        name: "wkp-mgmt01-pool-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSManagedMachinePool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedMachinePool
metadata:
  name: "wkp-mgmt01-pool-0"
spec:
  scaling:
    minSize: 2
    maxSize: 3
```

**Environment:**

- Cluster-api-provider-aws version: 0.6.4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard@weave.works>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
If a user edits the min/max size of a EKS node pool manually in the AWS console the controller will make sure that this is changed back to match the min/max size defined in AWSManagedMachinePool

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2318 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
EKS Nodepool min/max will be updated to match the AWSManagedMachinePool spec, overriding changes to min/max made via the AWS Console, CLI, or SDK.
```

### CODE REVIEW

**Comment by dlipovetsky** [comment]
New logic lgtm

nit: The nodepool can be changed via console, CLI, or SDK, so the release note could be more generic, e.g.:
```
EKS Nodepool min/max will be updated to match the MachinePool Spec, overriding changes to min/max made via the AWS Console, CLI, or SDK.
```

**Comment by richardcase** [comment]
@dlipovetsky - thanks for the suggestion on the release note.

**Comment by richardcase** [comment]
@sedefsavas - as discussed on the office hours it would be good to backport this.

**Pull request merged**
