### PR TITLE
bug: add rules to access eks-contoller private endpoint

### LINKED ISSUE #2465: Private EKS cluster SG forbids by default API access from outside of cluster
/kind bug

**What steps did you take and what happened:**
If you create EKS cluster with:
```yaml
  endpointAccess:
    public: false
    private: true
```
Than default security group setup is done in this way:
* Controll plane primary SG:
  * Ingress
    * All Traffic from self (reference to same SG id)
  * Egress
    * All Traffic to 0.0.0.0/0 
* Controll plane secondary SG:
  * Ingress
    * Port 22 TCP from SG of bastion 
* Nodegroup:
  * uses same  SG as Controll plane primary SG

**What did you expect to happen:**
This works for public cluster to an extent but is still weird setup. If you have private cluster it basically means noone except cluster itself can talk to API. Coupled with another bug which is `networkSpec: {  securityGroupOverrides: }` is not working for EKS which will be raised as different bug makes really private cluster completely unusable.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
```sh
$ kubectl get deploy -n capa-system capa-controller-manager -o yaml | grep cluster-api-aws-controller
        image: gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller:v0.6.6
```
- Kubernetes version: (use `kubectl version`): 
```sh
$ kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:39569
KubeDNS is running at https://127.0.0.1:39569/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
- OS (e.g. from `/etc/os-release`): 
```sh
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

### PR DESCRIPTION
**Pull request by paulcarlton-ww**
Add suuport for allowing access to private API endpoint from the
bastion host and also from specified security groups.

Fixes issue #2465

Signed-off-by: paulcarlton-ww <paul.carlton@weave.works>

**What type of PR is this?**

**What this PR does / why we need it**:

Without this feature the management cluster cannot access the API of a tenant cluster with only a private endpoint. Tenant cluster API access is required to complete provisioning.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #2465

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Adds new fields to the `AWSManagedControlPlane` `endpointAccess` element to allow access to a private API endpoint 

endpointAccess:
    public: false
    private: true
    bastionAccess: true
    additionalSecurityGroups:
    - "..."
Note that the use of additionalSecurityGroups to add security groups that allow management cluster access to the tenant's private API may require the creation of a VPC peering connection, see #2484
```

### CODE REVIEW

**Comment by paulcarlton-ww** [comment]
This supersedes #2514 which seems to have got hundreds of changes on now, possibly an error in my rebasing?

**Comment by paulcarlton-ww** [comment]
WIP: need to add conversion functions

**Comment by paulcarlton-ww** [comment]
need to add some unit tests and do some functional testing

**Comment by sedefsavas** [comment]
> need to add some unit tests and do some functional testing

@paulcarlton-ww is this PR ready to review?

**Comment by paulcarlton-ww** [comment]
Yes, but I haven’t tested the new functionality explicitly and probably won’t get time to progress it now

**Comment by randomvariable** [comment]
API needs a bit of a looking at here, as there's now growing drift between the EC2 and EKS APIs which then share the same code. Can we look at making this consistent using networkSpec?

**Comment by richardcase** [comment]
@paulcarlton-ww - do you think you'll have time to look at this again? Or shall we close it?

**Comment by richardcase** [comment]
Chatted with @paulcarlton-ww on slack and he would like to keep this open and potentially come back to it in the next few weeks.

**Pull request closed without merging**
