### PR TITLE
Fix cluster-api-provider-last-applied-tags-on-volumes to recalculate the value on each reconcile

### LINKED ISSUE #4530: AWSMachine metadata can exceed safe sizes due to cluster-api-provider-aws-last-applied-tags values
/kind bug

**What steps did you take and what happened:**
AWSMachine annotation values for `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` seem to accumulate and never be cleared or reset when volumes are removed for a machine. This results in problems for longer-lived awsmachines, especially if they are used in a context with frequent volume churn (Gitlab CI), because this annotation value can become excessively large. We have several dozen AWSMachines where this value exceeds 20k length:
```
kubectl --cluster awscmhinfra2 -n capi-awscmhinfra2 get -o json awsmachine | jq -r '.items[] | select(.metadata.annotations | to_entries | any(.value | length > 20000)) | .metadata.name' | wc -l
28
```

Today we noticed three cases where the value exceeded 250k length, which prevented the resources from being converted to older versions by the conversion webhook:

```
kubectl get awsmachine.v1beta1.infrastructure.cluster.x-k8s.io worker-private-m6-mixed-az1-0a772868-9b8lf -oyaml -n capi-awscmhinfra2

Error from server: conversion webhook for infrastructure.cluster.x-k8s.io/v1beta2, Kind=AWSMachine returned invalid metadata: metadata.annotation: Too long: must have at most 262144 bytes
```

**What did you expect to happen:**
The number of elements stored in the `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` should match the number of volumes the corresponding `node` resource for the match has attached. On one of the problematic AWSMachine resources, there were 1907 distinct volumes ids saved in the annotation values, but only 2 volumes present on the node.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 2.2.1
- Kubernetes version: (use `kubectl version`):  1.24.14
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.6 LTS

### PR DESCRIPTION
**Pull request by cnmcavoy**
**What type of PR is this?**
/bug

**What this PR does / why we need it**: Fixes an issue with the value of the `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` annotation growing to an unbounded size, due to re-use of it's previous state. We only need to persist information about volumes currently attached, so recomputing and clearing the annotation value is sufficient.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4530

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fixed a bug with the `sigs.k8s.io/cluster-api-provider-aws-last-applied-tags` annotation that could cause excessive metadata values on AWSMachines. 
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
@cnmcavoy off-topic, would be good if you applied for membership of kubernetes-sigs org. Just noticed that you are not 😅 since you have made significant contributions in CAPA, it would be good to be added as a member.

**Comment by Ankitasw** [comment]
/lgtm
/approve

Good find @cnmcavoy 👍

**Comment by cnmcavoy** [comment]
> @cnmcavoy off-topic, would be good if you applied for membership of kubernetes-sigs org. Just noticed that you are not 😅 since you have made significant contributions in CAPA, it would be good to be added as a member.

https://github.com/kubernetes/org/issues/4474 :sweat_smile:

**Comment by Ankitasw** [comment]
@cnmcavoy oopsie 😅

**Pull request merged**
