### PR TITLE
OWNERS: Move randomvariable to emeritus

### PR DESCRIPTION
**Pull request by randomvariable**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

With regret, I will be stepping away from Cluster API and won't be around to review PRs, so need to take myself out of the loop.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
Sad days :sob: 

Thank you @randomvariable for all your help and guidance over the last couple of years we've worked together on CAPA. You will be missed.  Stay in touch.

**Comment by Ankitasw** [comment]
Thankyou @randomvariable for all your guidance and help around CAPI/CAPA . You would hop on a call anytime I face a small issue which made you a lot reachable and helpful 😢  Going to miss you around.

**Comment by randomvariable** [comment]
> Thank you @randomvariable for all your help and guidance over the last couple of years we've worked together on CAPA. You will be missed. Stay in touch.

Thanks, it's been a pleasure! I'll still be in the Slacks. 

Also, I'll stick around in the k/org memberships to help with transition, image promotion for a while by request of @sedefsavas .

**Pull request merged**
