### PR TITLE
docs: Make getting started requirements easier to understand

### LINKED ISSUE #944: Documentation Clarity
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
It would help either there is a requirement.sh that handles the requirements automatically or if the steps could be explained further what is expected to be done.

    Linux or MacOS (Windows isn't supported at the moment):
Does it mean a Linux VM on AWS ?
    A set of AWS credentials sufficient to bootstrap the cluster (see bootstrapping-aws-identity-and-access-management-with-cloudformation).
    An AWS IAM role to give to the Cluster API control plane. - How this needs to be done ?
    KIND >= v0.1
how to simply this installation steps , could there be a quick install script to quickly do this ?
    gettext (with envsubst in your PATH)
How this is done ?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by dlipovetsky**
Fixes #944

### CODE REVIEW

**Comment by dlipovetsky** [comment]
image

I don't understand why GitHub thinks someone else authored this...

**Comment by detiber** [comment]
@dlipovetsky lgtm, did you want to try to resolve the attribution issue?

**Comment by dlipovetsky** [comment]
@detiber Yeah. I sent GitHub support an email :laughing:

**Comment by dlipovetsky** [comment]
I have no idea what I did to my local repo, but for some reason the commit author wasn't me:
```
$ git log                                                  
commit 9722e72f6a4feb03c5408d6d51ef225c45d38be6 (HEAD -> fix-docs, origin/fix-docs)
Author: Sn0rt <wangguohao.2009@gmail.com>      
Date:   Fri Aug 2 20:57:54 2019 +0800
                                                                                                                   
    docs: Make getting started requirements easier to understand                                                   
                                                                                                                   
    Fixes: #944              
                                                                                                                   
    Signed-off-by: Daniel Lipovetsky <daniel@platform9.com>  
```

I fixed by overwriting the commit.

**Pull request merged**
