### PR TITLE
WIP: ISSUE-2414: Enable additional linters

### LINKED ISSUE #2414: Enable additional linters
Core cluster-api repo is enabling some additional linters, it'd be good for consistency to enable same linters.

https://github.com/kubernetes-sigs/cluster-api/issues/4622

/help
/good-first-issue
/milestone 0.7.x

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Enable additional linters

**Which issue(s) this PR fixes**
Fixes #2414

**Checklist**:
- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
@Evalle - looks like the additional linters have caused the tests to fail.

**Comment by Evalle** [comment]
@richardcase thanks for checking! I marked it as WIP for now, my issue is that the default branch has been changed to `main` I didn't fetch all the changes. Let me fix that.

**Comment by Evalle** [comment]
Too many conflicts, gonna close this one and create a separate.

**Pull request closed without merging**
