### PR TITLE
[WIP] ✨ Ipv6 support for aws v0.4

### PR DESCRIPTION
**Pull request by aojea**
**What this PR does / why we need it**:

Allows to create IPv6 clusters on aws

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by ncdc** [comment]
@aojea thanks for your PR. Would you be willing to retarget this against master? We aren't adding new features to v0.4.x.

**Comment by aojea** [comment]
> @aojea thanks for your PR. Would you be willing to retarget this against master? We aren't adding new features to v0.4.x.

hi @ncdc , I was talking with @dims and @timothysc during the kubecon and they suggested me to test the changes first in this branch and then backport it to master.
This PR is just to check that the e2e tests work, is this ok or should I try master directly?  :man_shrugging:

**Comment by ncdc** [comment]
If it’s just for testing, this is fine.

On Nov 22, 2019, at 6:06 PM, Antonio Ojea <notifications@github.com> wrote:

﻿

@aojea<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faojea&data=02%7C01%7Cgoldsteina%40vmware.com%7Cfc78b223b8d94d7c6dc908d76fa0a695%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637100608090665077&sdata=KNNhbVKDDJIZO%2FRrv%2F47bor5uIVVewwIHgoeqDCSI4Y%3D&reserved=0> thanks for your PR. Would you be willing to retarget this against master? We aren't adding new features to v0.4.x.

hi @ncdc<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fncdc&data=02%7C01%7Cgoldsteina%40vmware.com%7Cfc78b223b8d94d7c6dc908d76fa0a695%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637100608090675066&sdata=MePWGWknSrYlPu9IXJxSltTnH1hv0xG2QgAjaJpMV9I%3D&reserved=0> , I was talking with @dims<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdims&data=02%7C01%7Cgoldsteina%40vmware.com%7Cfc78b223b8d94d7c6dc908d76fa0a695%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637100608090685061&sdata=efgeLSPAjsQ7KRJ7OJS9oPQ9MKhSFR5e%2Fl81VNkX6ho%3D&reserved=0> and @timothysc<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimothysc&data=02%7C01%7Cgoldsteina%40vmware.com%7Cfc78b223b8d94d7c6dc908d76fa0a695%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637100608090695058&sdata=jAe5Rh2Umbj2poQ5RuawQtqTae96%2F5y1eWXyM4ari1I%3D&reserved=0> during the kubecon and they suggested me to test the changes first in this branch and then backport it to master.
This PR is just to check that the e2e tests work, is this ok or should I try master directly? 🤷‍♂

**Comment by detiber** [comment]
@aojea we're not looking to add any additional significant features for v0.4.x, closing this and we can target v0.5.x or Next when ready to pick this back up
/close

**Comment by aojea** [comment]
yeah, sorry for not updating the status ... hope I could have more time :(

**Comment by detiber** [comment]
No worries :)

**Pull request closed without merging**
