### PR TITLE
Add new on-demand and spot allocation strategies

### LINKED ISSUE #4160: Support more instance allocation strategies
/kind feature

**Describe the solution you'd like**

Support all the instance allocation strategies defined in https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-mixed-instances-groups.html#allocation-strategies

Specifically, would love to have `price-capacity-optimized` for spot instance and `lowest-price` for on-demand instances 🎉

### PR DESCRIPTION
**Pull request by Fedosin**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

This PR adds support for new instance allocation strategies: `lowest-price` on-demand strategy, `capacity-optimized-prioritized` and `price-capacity-optimized` spot strategies.

More info: https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-mixed-instances-groups.html#allocation-strategies

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4160 

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [X] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Added support for new instance allocation strategies: lowest-price on-demand strategy, capacity-optimized-prioritized and price-capacity-optimized spot strategies.
```

### CODE REVIEW

**Comment by Skarlso** [comment]
I can run the EKS test on this. The changes look okay, but we obviously don't have any e2e tests for spot instances.

/test pull-cluster-api-provider-aws-e2e-eks

**Comment by Skarlso** [comment]
Can you also add a test in exp/controllers/awsmachinepool_controller_test.go please? Shouldn't be too hard. :) Thanks!

**Comment by Fedosin** [comment]
Sure, I added a small test in exp/controllers/awsmachinepool_controller_test.go. PTAL :)

**Pull request merged**
