### PR TITLE
fix: make kpromo version consistent

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This change makes the versions of kpromo to consistently be v4.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits

**Release note**:

```release-note
Make kpromo versioned consistent
```

### CODE REVIEW

**Comment by Skarlso** [comment]
🤞

**Comment by richardcase** [comment]
@Ankitasw @Skarlso - checks are better on this PR :)

**Pull request merged**
