### PR TITLE
Use crds

### LINKED ISSUE #252: Generate CRDs with kubebuilder
/kind feature

**Describe the solution you'd like**
Instead of copy/pasting CRDs from the gcp project we should generate them ourselves

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): @

### PR DESCRIPTION
**Pull request by chuckha**
**What this PR does / why we need it**:
This PR uses the new CRD types and removes the old ones.

/hold

The hold is here so I can get feedback while I do some manual testing.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #252 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
I think this is fine, as it aligns with the GCP provider. Can you update the example yamls, changing the providerConfig apiVersion in the yamls as you go along though?

**Comment by chuckha** [comment]
@randomvariable oh that needs a regen. good catch!

**Comment by chuckha** [comment]
/hold cancel

unblock @vincepri

**Comment by vincepri** [comment]
Merging this in for now to unblock CRDs.

/lgtm

**Pull request merged**
