### PR TITLE
📖 Added how to develop locally using Tilt for EKS Control Plane

### PR DESCRIPTION
**Pull request by kenichi-shibata**
For EKS Control Plane development

**What this PR does / why we need it**:
Documentation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

Can't find an issue

### CODE REVIEW

**Comment by richardcase** [comment]
@kenichi-shibata - Would you be able to add an entry for this new topic in the [SUMMARY.md](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/book/src/SUMMARY.md)?

**Comment by kenichi-shibata** [comment]
> @kenichi-shibata - Would you be able to add an entry for this new topic in the [SUMMARY.md](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/book/src/SUMMARY.md)?

i can what's your suggestion for a title?

**Comment by randomvariable** [comment]
This is great, thanks!
lgtm, but could you squash these commits?

**Comment by kenichi-shibata** [comment]
@randomvariable done

**Pull request merged**
