### PR TITLE
✨Add support to specify static credentials in a Secret

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
/hold

### CODE REVIEW

**Comment by detiber** [comment]
@vincepri Is the goal for this some type of multi-tenancy, or just alternative credentials to be used?

Let me know when this is ready for review.

**Comment by vincepri** [comment]
It's an alternative to the webhook refactoring I posted upstream, it's mostly to show that there is a viable alternative to the multi-tenancy approach we have taken today with namespaces

**Comment by detiber** [comment]
> It's an alternative to the webhook refactoring I posted upstream, it's mostly to show that there is a viable alternative to the multi-tenancy approach we have taken today with namespaces

There is a potential problem here in that we would need some mechanism in place to prevent users from one tenant from using the credentials owned by another tenant.

**Comment by vincepri** [comment]
@detiber The namespace separation still applies, given that we're not using an ObjectReference, the secret must live in the Cluster's own namespace

**Comment by randomvariable** [comment]
Don't think this is quite right.

For multi-tenant AWS accounts, role assumption would be the primary practice, and this method can't support that (lack of rotation and support of session tokens).

We should start with the user stories and AWS best practice and work from there.

**Comment by vincepri** [comment]
@randomvariable As I mentioned this isn't supposed to go in, but rather show that there is an easy path forward. What you mentioned about role assumption or token is also a problem with today's file credentials.

**Comment by randomvariable** [comment]
> What you mentioned about role assumption or token is also a problem with today's file credentials.

Role assumption can be set today using https://docs.aws.amazon.com/cli/latest/topic/config-vars.html, and is in use.

In addition, we have the default credential provider chain best described in the Java docs at https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html

as has been discussed previously in #201

**Comment by vincepri** [comment]
Nice, forgot we had those. 

Did you want to open an issue outlining the use cases and possible solutions or want me to?

**Comment by randomvariable** [comment]
> Did you want to open an issue outlining the use cases and possible solutions or want me to?
Yup, I can do that.

**Comment by randomvariable** [comment]
Created https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1552

**Comment by vincepri** [comment]
Closing now that we decided to split webhooks out

/close

**Pull request closed without merging**
