### PR TITLE
:running: Update cluster-api release used for e2e/conformance tests

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
- Updates the CAPI version used for conformance and e2e tests

### CODE REVIEW

**Comment by ncdc** [comment]
Do you want to wait on the e2e before merging?

**Comment by detiber** [comment]
> Do you want to wait on the e2e before merging?

It looks like at least one of the previously failed tests has already succeeded (was failing on validation of KubeadmConfig.Spec.ClusterConfiguration.Networking.PodSubnet being required).

**Comment by ncdc** [comment]
Ok, let's merge it. Will probably want to adjust to 0.3.3 soon after it's out too.
/lgtm

**Pull request merged**
