### PR TITLE
feat(release): update image promotion to use kpromo

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

The release process has been updated to use `kpromo` for handling the image promotion instead of the manual process we had.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation

**Release note**:

```release-note
Change the release process to use **kpromo**
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
@richardcase uhmmm merge conflict 🤦‍♀️

**Comment by richardcase** [comment]
> @richardcase uhmmm merge conflict woman_facepalming

I'll do it manually.

**Pull request merged**
