### PR TITLE
[PROPOSAL] move fiunchinho to reviewer

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind support

**What this PR does / why we need it**:

This changes makes the following maintainer & reviewer changes:

- @fiunchinho moves to reviewer
- @Skarlso moves from maintainer to emeritus

@Skarlso - thank you for your contributions and dedication to CAPA, the project is better for it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
@fiunchinho moves to reviewer and @Skarlso moves to emeritus maintainer
```

### CODE REVIEW

**Comment by Skarlso** [comment]
/lgtm

<3

**Comment by richardcase** [comment]
Looks like some weord formatting has been applied, so until thats fixed:

/hold

**Comment by richardcase** [comment]
Turns out vscode was deciding it should reformat the files.

**Pull request merged**
