### PR TITLE
fix: eks e2e test failing as subnet name was used

### LINKED ISSUE #4574: [E2E] EKS tests are failing
/kind bug

**What steps did you take and what happened:**

Looking at testgrid the different EKS have been consistently failing since 3/4th October. For example:
- [EKS main](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#pr-e2e-eks-main)
- [EKS gc](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#pr-e2e-eks-gc-main)

Looking at some of the logs for the failures we see errors like this:

```
I1011 03:29:27.276687       1 recorder.go:104] "events: Failed to initiate creation of a new EKS control plane: InvalidParameterException: The subnet ID 'eks-extresgc-384bwp-subnet-public-us-west-2a' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnetID.NotFound
```

Looking at the logs some more for the reconciliation of the subnets we see this for mentioned subnet:

```
    {
        "id": "eks-extresgc-384bwp-subnet-public-us-west-2a",
        "resourceID": "subnet-0b94dc61d85f0193d",
        "cidrBlock": "10.0.0.0/20",
        "availabilityZone": "us-west-2a",
        "isPublic": true,
        "routeTableId": "rtb-00a1670a0816f30c6",
        "natGatewayId": "nat-0f38df4fc916ed6c4",
        "tags": {
            "Name": "eks-extresgc-384bwp-subnet-public-us-west-2a",
            "kubernetes.io/cluster/eks-extresgc-o755gy_eks-extresgc-384bwp-control-plane": "shared",
            "kubernetes.io/role/elb": "1",
            "sigs.k8s.io/cluster-api-provider-aws/cluster/eks-extresgc-384bwp": "owned",
            "sigs.k8s.io/cluster-api-provider-aws/role": "public"
        }
    },
```

We should be passing **subnet-0b94dc61d85f0193d** and not **eks-extresgc-384bwp-subnet-public-us-west-2a** when creating the EKS cluster. 

Looking at the code [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/cluster.go#L281) we can see that it is passing the **ID** and not the value for **ResourceID**.

**ResourceID** is a new field introduced as part of #4474. We need to update the EKS code to use the REsourceID

**What did you expect to happen:**

The EKS e2e to not fail

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind bug
/kind regression

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4574 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits

**Release note**:

```release-note
Fix issue with EKE e2e tests due to a issue when specifying which subnets to use.
```

### CODE REVIEW

**Comment by richardcase** [comment]
I'll get the failing tests fixed today

**Comment by richardcase** [comment]
Running the e2e again:

/test pull-cluster-api-provider-aws-e2e-eks
/test pull-cluster-api-provider-aws-e2e-eks-testing
/test pull-cluster-api-provider-aws-e2e-eks-gc

**Comment by richardcase** [comment]
Lets also check the non-EKS e2e:

/test pull-cluster-api-provider-aws-e2e

**Comment by richardcase** [comment]
EKS and non-EKS tests passing

**Review by AndiDog — COMMENTED** [review]
/lgtm

**Pull request merged**
