### PR TITLE
Update getting started guide

### PR DESCRIPTION
**Pull request by sethp-nr**
**What this PR does / why we need it**: Addresses the difficulties we ran into during our attempt to trial the project.

**Special notes for your reviewer**:

We noticed a few details that appear to have desynchronized from the current state of the project, but by far the biggest time sinks were around minikube and the SSH key (we didn't think to look at the logs until very late, sadly).

The minikube issue has been reported upstream here: https://github.com/kubernetes/minikube/issues/3284

### CODE REVIEW

**Comment by sethp-nr** [comment]
hi @k8s-ci-robot I believe I've signed the CLA.

**Comment by detiber** [comment]
@sethp-nr these changes look good, are you working on completing the CLA process?

**Comment by sethp-nr** [comment]
@detiber Yes, I'm attempting to get my employer to sign. I regret to report that I doubt this will be a quick process.

**Comment by detiber** [comment]
@sethp-nr no worries, thanks for the update!

**Comment by sethp-nr** [comment]
I have good news: We're in the home stretch on our end with the CLA.

I've been tracking some of the changes in the project, but once that's finalized I'll take another pass and see what from this change set still might make sense. Thanks for your patience!

**Comment by vincepri** [comment]
@sethp-nr Any updates on the CLA?

**Comment by sethp-nr** [comment]
Good news: It's been signed (and it looks like the bot is happy 🎉).

I took an editing pass over my changes to the doc & we tried to run through it all again. We found a few problems that I detailed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/341/commits/00883aebc6af3937eb205271cde8bef2b88696fc .

**Comment by vincepri** [comment]
@sethp-nr Nice work there! I'll go ahead and merge this in, it looks great. Usually we should split changes that shouldn't be in the same PR, but given this has been open for a while, it's ok :) 

/lgtm

**Comment by sethp-nr** [comment]
Yeah, that makes sense – I'm happy to pull out the security group & clusterawsadm stuff into separate PRs if you'd prefer. Now that we've got a CLA in place, it shouldn't take three weeks to merge those changes 😬

**Comment by vincepri** [comment]
@sethp-nr all good! Let's go ahead and merge these changes. And very good job in getting this done!

/approve

**Pull request merged**
