### PR TITLE
add option for disabling instance refresh

### PR DESCRIPTION
**Pull request by harveyxia**
**What type of PR is this?**

/kind feature
/kind api-change

**What this PR does / why we need it**:

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3447

**Special notes for your reviewer**:

I was hoping for guidance/feedback on the following:

1. API representation—I added a new `AWSMachinePool.spec.disableInstanceRefresh` boolean field. This preserves existing behavior, which is to perform instance refresh when new launch templates are detected. Users that require disabling instance refresh will explicitly specify this field as `false`.
2. Testing—I was sure how best to test this change, there doesn't appear to be any existing test coverage of `ReconcileLaunchTemplate`'s  `runPostLaunchTemplateUpdateOperation` ([link](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/88edf3bf605600f9bb2355d815df175434ce9d82/exp/controllers/awsmachinepool_controller.go#L251)).

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
I think disabling instance refresh can go under RefreshPreferences logically as @mweibel mentioned in the issue:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/e53fce703aaa8ffce6913cb96d24f1f37e355ef2/exp/api/v1beta1/awsmachinepool_types.go#L92

@mweibel any thoughts?

**Comment by sedefsavas** [comment]
/hold
until https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3720 is merged.

**Comment by mweibel** [comment]
Makes sense! I'd rename it to just `Disabled` since `RefreshPreferences.DisableInstanceRefresh` is a little redundant, but that's a detail.

**Comment by harveyxia** [comment]
@sedefsavas this should be good to review now

**Comment by sedefsavas** [comment]
We need conversion for the new field. 
An example of how to add conversion [here](https://github.com/kubernetes-sigs/cluster-api/pull/5608/files#diff-0c677a0915e60fa67c24ef3d0bcf0be9388f0f1ccc48942cb311ae0adf5b6e83) 

I don't know how Fuzzy conversion test did not catch this though, any ideas @richardcase?

**Comment by harveyxia** [comment]
@sedefsavas Gentle bump, any chance I could get a review? Thank you!

**Comment by richardcase** [comment]
@harveyxia - thanks for this change. Would you be able to rebase it?

**Comment by harveyxia** [comment]
@richardcase should be good to go now, thanks!

**Comment by richardcase** [comment]
Thanks for this @harveyxia 👍

/lgtm 
/approve

**Pull request merged**
