### PR TITLE
Test flavors small improvements

### PR DESCRIPTION
**Pull request by invidian**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Just some small stuff found along the way.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
Sure it's fine, but has this been tested on both MacOS and Linux?

**Comment by invidian** [comment]
>Sure it's fine, but has this been tested on both MacOS and Linux? (I only have Linux to test with)

Tested on MacOS 12.0.1 with `grep -v -E '(foo|bar)'` and it works fine if that's what you mean.

**Comment by sedefsavas** [comment]
Works for MacOs.
/lgtm
/approve

**Pull request merged**
