### PR TITLE
chore: Bump CAPI to v1.3.4

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area release
/kind support

**What this PR does / why we need it**:
This PR bumps CAPI to v1.3.4

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Bump CAPI version to v1.3.4
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
PR is ready for review.

**Comment by dlipovetsky** [comment]
Thank you @Ankitasw!

/lgtm

**Pull request merged**
