### PR TITLE
:warning: align flag names to upstream k8s

### LINKED ISSUE #2123: Align flag names with upstream Kubernetes components
cluster-api repo made these changes to the flag names: https://github.com/kubernetes-sigs/cluster-api/pull/3934

We should adopt these here as well to be consistent with it.

/milestone v0.7.0
/help

### PR DESCRIPTION
**Pull request by kkeshavamurthy**
**What this PR does / why we need it**:
Align flags with upstream k8s 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2123

### CODE REVIEW

**Comment by sedefsavas** [comment]
This is a breaking change, the name should have the warning icon: ⚠️:warning:.

**Comment by sedefsavas** [comment]
/milestone v0.7.0
/hold
until we merge v1alpha4 types to the master branch.

**Comment by MarcusNoble** [comment]
To avoid the breaking change (for now) we could [alias the flags](https://github.com/spf13/pflag#mutating-or-normalizing-flag-names) and set the current, non-matching to [deprecated](https://github.com/spf13/pflag#deprecating-a-flag-or-its-shorthand).

**Comment by richardcase** [comment]
This should work now

/milestone v0.7.0

**Comment by randomvariable** [comment]
rebasing onto the release-0.7 branch

/unhold

**Pull request merged**
