### PR TITLE
Make logging for creating/deleting AWS resources consistent

### LINKED ISSUE #3143: Make logging for creating/deleting AWS resources consistent
While reviewing e2e test output, I noticed that logging for AWS resource creation/deletion is inconsistent. Some has only creation log while others (e.g. security groups) don't have any logging.

For example, CAPA log shows that there are creation logs for subnet, IGW and NGW (note that NGW log format could be consistent) while there are more logs for deletion.

```
I0203 17:46:13.141806      61 subnets.go:360] controller/awscluster "msg"="created subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "az"="us-west-1a" "cidr"="10.0.0.0/19" "id"="subnet-0db9b5aaa9d04648f" "public"=true
I0203 17:46:13.696397      61 subnets.go:360] controller/awscluster "msg"="created subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "az"="us-west-1a" "cidr"="10.0.64.0/18" "id"="subnet-06be222a28b37f939" "public"=false
I0203 17:46:14.171571      61 subnets.go:360] controller/awscluster "msg"="created subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "az"="us-west-1c" "cidr"="10.0.32.0/19" "id"="subnet-03259b1fd68553458" "public"=true
I0203 17:46:14.836421      61 subnets.go:360] controller/awscluster "msg"="created subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "az"="us-west-1c" "cidr"="10.0.128.0/18" "id"="subnet-0631cc3821aaff6df" "public"=false
I0203 17:46:15.505004      61 gateways.go:133] controller/awscluster "msg"="Created internet gateway for VPC" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "vpc-id"="vpc-0b96711048cce1221"
...
I0203 17:47:47.610187      61 natgateways.go:264] controller/awscluster "msg"="NAT gateway for subnet is now available" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "nat-gateway-id"="nat-010581bb86c376774" "subnet-id"="subnet-03259b1fd68553458"
...
I0203 18:00:47.144617      61 routetables.go:195] controller/awscluster "msg"="Deleted association between route table and subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-054109ab5193ae254" "subnet-id"="subnet-0db9b5aaa9d04648f"
I0203 18:00:47.256422      61 routetables.go:204] controller/awscluster "msg"="Deleted route table" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-054109ab5193ae254"
I0203 18:00:47.456331      61 routetables.go:195] controller/awscluster "msg"="Deleted association between route table and subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-07276406fe1cfffd5" "subnet-id"="subnet-0631cc3821aaff6df"
I0203 18:00:47.574764      61 routetables.go:204] controller/awscluster "msg"="Deleted route table" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-07276406fe1cfffd5"
I0203 18:00:47.836439      61 routetables.go:195] controller/awscluster "msg"="Deleted association between route table and subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-0e97e451b8a4b0f3a" "subnet-id"="subnet-06be222a28b37f939"
I0203 18:00:47.936686      61 routetables.go:204] controller/awscluster "msg"="Deleted route table" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-0e97e451b8a4b0f3a"
I0203 18:00:48.123060      61 routetables.go:195] controller/awscluster "msg"="Deleted association between route table and subnet" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-01e08a3091f446ce9" "subnet-id"="subnet-03259b1fd68553458"
I0203 18:00:48.244579      61 routetables.go:204] controller/awscluster "msg"="Deleted route table" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "route-table-id"="rtb-01e08a3091f446ce9"
I0203 18:00:48.595773      61 natgateways.go:277] controller/awscluster "msg"="Deleted NAT gateway in VPC" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "nat-gateway-id"="nat-0d0eb80f31b3d6fed" "vpc-id"="vpc-0b96711048cce1221"
I0203 18:00:48.693270      61 natgateways.go:277] controller/awscluster "msg"="Deleted NAT gateway in VPC" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "nat-gateway-id"="nat-010581bb86c376774" "vpc-id"="vpc-0b96711048cce1221"
I0203 18:01:59.113222      61 eips.go:143] controller/awscluster "msg"="released ElasticIP" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "allocation-id"="eipalloc-054b75354308a7858" "eip"="54.151.34.33"
I0203 18:01:59.744465      61 eips.go:143] controller/awscluster "msg"="released ElasticIP" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "allocation-id"="eipalloc-0066f6d7e4af359a6" "eip"="54.241.80.115"
I0203 18:02:00.130824      61 gateways.go:104] controller/awscluster "msg"="Detached internet gateway from VPC" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "internet-gateway-id"="igw-0cfe904cb514b5ab1" "vpc-id"="vpc-0b96711048cce1221"
I0203 18:02:00.262275      61 gateways.go:116] controller/awscluster "msg"="Deleted internet gateway in VPC" "cluster"="quick-start-4j8dyg" "name"="quick-start-4j8dyg" "namespace"="quick-start-c63w4e" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" "internet-gateway-id"="igw-0cfe904cb514b5ab1" "vpc-id"="vpc-0b96711048cce1221"
I0203 18:02:02.248113      61 awsinstancestate_controller.go:83] controllers/AWSInstanceStateController "msg"="cluster not found, removing queue URL"  "cluster"="quick-start-4j8dyg"
```

This is due to some resources miss the log statement while other resources use different log level, `s.scope.Info` vs. `s.scope.V(2).Info()`.  

### What do you expect?
CAPA should have consistent log output for AWS resources creation/deletion.

### PR DESCRIPTION
**Pull request by pydctw**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Make logging for creating/deleting AWS resources consistent. See #3143 for a detailed description.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3143 

**Special notes for your reviewer**:
Added missing logs, formatted some logs and moved unimportant logs to level 2.

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:
```release-note
Make logging for AWS resources creation/deletion consistent
```

### CODE REVIEW

**Comment by pydctw** [comment]
Will add updated log out when e2e test is finished.

**Comment by sedefsavas** [comment]
I think there is a systematic way you have in mind in this PR: logging as info() only at the end of a method and logging v2.info() elsewhere.
Unless we document this logic and agree on what to be consistent about during reviews, we will not have consistency.

Do you want to track this or maybe add documentation as part of this PR?

**Comment by Ankitasw** [comment]
This is really good observation, as I have recently got feedback that the logs are inconsistent. As @sedefsavas mentioned, I also think we should have documentation in place so that if we add  new services/behavior, then this documentation might help follow consistency.
Also, do we have any guidelines on what to put for v(2) logs and what to put for other levels like ,v(4),v(6) etc?

**Comment by pydctw** [comment]
> I think there is a systematic way you have in mind in this PR: logging as info() only at the end of a method and logging v2.info() elsewhere.

I actually didn't have any systematic way in mind 🙂 What I did was 
* Add a missing creation log at the same log level as the existing deletion log
* Add a missing creation/deletion or adjust the log level for resources with same level of importance (subnet, sg, and etc)
* Thought `Deleted association between route table and subnet` and `Detached internet gateway from VPC` are not that important for users so moved the log level to V(2).

But 100% agree that it will be great to have a guidance on what log level to use across the repo. Will open an issue for discussion. Thank you for the suggestion, @sedefsavas and @Ankitasw.

**Comment by pydctw** [comment]
Created an issue for consistent logging as a follow up: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3152

**Comment by sedefsavas** [comment]
> I actually didn't have any systematic way in mind 🙂 What I did was

I looked too hard for seeing consistency then =)

/lgtm
/approve

**Pull request merged**
