### PR TITLE
WIP test: added dumping of pod info from workload clusters

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard.case@outlook.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Added the dumping of pod information from the workload clusters.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
I wanted to help out and fix these minor issues, but I can't push to the branch. :D Sorry Richard. :)

**Comment by richardcase** [comment]
@Ankitasw @Skarlso - is it worth me fixing this up?

**Comment by Skarlso** [comment]
I definitely think so yeah. During my many hours of debugging it would have been nice to see the cluster state.

**Comment by Ankitasw** [comment]
> I definitely think so yeah. During my many hours of debugging it would have been nice to see the cluster state.

I second this thought 👍

**Pull request closed without merging**
