### PR TITLE
chore: bump capi to 1.2.5

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard.case@outlook.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Bumps CAPI to 1.2.5 as part of the 2.0.0 release

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
I guess we should also bump controller-runtime with this bump.

**Comment by richardcase** [comment]
> I guess we should also bump controller-runtime to 0.13.1 and gomega to 0.24.x with this bump.

I don't think we should upgrade controller-runtime as part of this, we are inline with CAPI 1.2.5 with the version we have. Plus, it's bumping a minor version number and this may require changes.

Let's keep this as a pure capi version bump (and indirect deps)

**Pull request merged**
