### PR TITLE
PROPOSAL: move Daniel to maintainer

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard.case@suse.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This change will move to Daniel from review to maintainer. Daniel has been a long term user and contributor to CAPA. He provides thoughtful and insightful reviews. 

Holding for lazy consensus until after the office hours on 31st October 2022

/hold

### CODE REVIEW

**Comment by Skarlso** [comment]
Absolutely +1 from me! :)

**Comment by pydctw** [comment]
@dlipovetsky have submitted many important PRs and one of the best reviewers in CAPA. Big +1 from me.
/lgtm

**Comment by Ankitasw** [comment]
+1 from my side ❤️

**Comment by richardcase** [comment]
As we have consensus:

/approve
/unhold

**Comment by dlipovetsky** [comment]
Thanks, all!

**Pull request merged**
