### PR TITLE
🐛: securitygroup: fix comparison of ingress rules sets.

### LINKED ISSUE #5023: Ingress rules reconciliation is not comparing equivalent sets
/kind bug

**What steps did you take and what happened:**

When reconciling Security Group ingress rules, CAPA is comparing sets that are not equivalent. That happens because in [this commit](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/42eafcd4ff1e4a294620dddb77b098acc460f4ca
) the ingress rules from the SDK are duplicated to not contain both a `sourceSecurityGroupID` and `cidr blocks`. However, when deriving the [desired rules set](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/securitygroup/securitygroups.go#L163) the rules are [generated with sourceSGs and cidrBlocks containing multiple items](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/securitygroup/securitygroups.go#L534).

This results in sets that are always different and rules will be [revoked](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/securitygroup/securitygroups.go#L168) and [authorized](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/securitygroup/securitygroups.go#L182) in every reconcile loop.

**What did you expect to happen:**

Equivalent sets are compared.

**Anything else you would like to add:**

Here is an example in Openshift where the rules are continuously revoked/authorized: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8545/pull-ci-openshift-installer-master-e2e-aws-ovn-fips/1801221043054972928/artifacts/e2e-aws-ovn-fips/ipi-install-install/artifacts/.openshift_install-1718286343.log

```
time="2024-06-13T12:47:33Z" level=debug msg="I0613 12:47:33.242557     325 recorder.go:104] \"Revoked security group ingress rules [protocol=tcp/range=[6443-6443]/description=Kubernetes API protocol=tcp/range=[6443-6443]/description=Kubernetes API protocol=tcp/range=[6443-6443]/description=Kubernetes API protocol=udp/range=[6081-6081]/description=Port 6081 (UDP) for geneve protocol=udp/range=[6081-6081]/description=Port 6081 (UDP) for geneve protocol=udp/range=[9000-9999]/description=Port 9000-9999 for node ports (UDP) protocol=udp/range=[9000-9999]/description=Port 9000-9999 for node ports (UDP) protocol=tcp/range=[10257-10257]/description=controller-manager protocol=tcp/range=[10257-10257]/description=controller-manager protocol=tcp/range=[22623-22623]/description=MCS traffic from cluster network protocol=tcp/range=[22623-22623]/description=MCS traffic from cluster network protocol=udp/range=[30000-32767]/description=Service node ports (UDP) protocol=udp/range=[30000-32767]/description=Service node ports (UDP) protocol=udp/range=[4789-4789]/description=Port 4789 (UDP) for VXLAN protocol=udp/range=[4789-4789]/description=Port 4789 (UDP) for VXLAN protocol=icmp/range=[-1--1]/description=ICMP protocol=icmp/range=[-1--1]/description=ICMP protocol=tcp/range=[10259-10259]/description=kube-scheduler protocol=tcp/range=[10259-10259]/description=kube-scheduler protocol=tcp/range=[30000-32767]/description=Service node ports (TCP) protocol=tcp/range=[30000-32767]/description=Service node ports (TCP) protocol=tcp/range=[22-22]/description=Port 22 (TCP) protocol=tcp/range=[22-22]/description=Port 22 (TCP) protocol=tcp/range=[9000-9999]/description=Port 9000-9999 for node ports (TCP) protocol=tcp/range=[9000-9999]/description=Port 9000-9999 for node ports (TCP) protocol=50/range=[0-0]/description=ESP protocol=50/range=[0-0]/description=ESP protocol=tcp/range=[6441-6442]/description=Port 6441-6442 (TCP) for ovndb protocol=tcp/range=[6441-6442]/description=Port 6441-6442 (TCP) for ovndb protocol=udp/range=[4500-4500]/description=Port 4500 (UDP) for IKE NAT protocol=udp/range=[4500-4500]/description=Port 4500 (UDP) for IKE NAT protocol=udp/range=[500-500]/description=Port 500 (UDP) for IKE protocol=udp/range=[500-500]/description=Port 500 (UDP) for IKE] for SecurityGroup \\\"sg-0156151301759f178\\\"\" logger=\"events\" type=\"Normal\" object={\"kind\":\"AWSCluster\",\"namespace\":\"openshift-cluster-api-guests\",\"name\":\"ci-op-ivvhn8jx-281c5-qh925\",\"uid\":\"4979c842-0b95-43af-a304-a0d0f12fc6e7\",\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta2\",\"resourceVersion\":\"378\"} reason=\"SuccessfulRevokeSecurityGroupIngressRules\""
time="2024-06-13T12:47:33Z" level=debug msg="I0613 12:47:33.572338     325 securitygroups.go:193] \"Authorized ingress rules in security group\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-ivvhn8jx-281c5-qh925\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-ivvhn8jx-281c5-qh925\" reconcileID=\"9c713630-1132-44e5-bf46-6005b9c49e31\" cluster=\"openshift-cluster-api-guests/ci-op-ivvhn8jx-281c5-qh925\" authorized-ingress-rules=[{\"description\":\"ICMP\",\"protocol\":\"icmp\",\"fromPort\":-1,\"toPort\":-1,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 22 (TCP)\",\"protocol\":\"tcp\",\"fromPort\":22,\"toPort\":22,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 4789 (UDP) for VXLAN\",\"protocol\":\"udp\",\"fromPort\":4789,\"toPort\":4789,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 6081 (UDP) for geneve\",\"protocol\":\"udp\",\"fromPort\":6081,\"toPort\":6081,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 500 (UDP) for IKE\",\"protocol\":\"udp\",\"fromPort\":500,\"toPort\":500,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 4500 (UDP) for IKE NAT\",\"protocol\":\"udp\",\"fromPort\":4500,\"toPort\":4500,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"ESP\",\"protocol\":\"50\",\"fromPort\":-1,\"toPort\":-1,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 6441-6442 (TCP) for ovndb\",\"protocol\":\"tcp\",\"fromPort\":6441,\"toPort\":6442,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 9000-9999 for node ports (TCP)\",\"protocol\":\"tcp\",\"fromPort\":9000,\"toPort\":9999,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Port 9000-9999 for node ports (UDP)\",\"protocol\":\"udp\",\"fromPort\":9000,\"toPort\":9999,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Service node ports (TCP)\",\"protocol\":\"tcp\",\"fromPort\":30000,\"toPort\":32767,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Service node ports (UDP)\",\"protocol\":\"udp\",\"fromPort\":30000,\"toPort\":32767,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"Kubernetes API\",\"protocol\":\"tcp\",\"fromPort\":6443,\"toPort\":6443,\"sourceSecurityGroupIds\":[\"sg-01220615d4fe14896\",\"sg-0156151301759f178\",\"sg-030767034bf574232\"]},{\"description\":\"MCS traffic from cluster network\",\"protocol\":\"tcp\",\"fromPort\":22623,\"toPort\":22623,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"],\"sourceSecurityGroupRoles\":[\"node\",\"controlplane\"]},{\"description\":\"controller-manager\",\"protocol\":\"tcp\",\"fromPort\":10257,\"toPort\":10257,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"],\"sourceSecurityGroupRoles\":[\"controlplane\",\"node\"]},{\"description\":\"kube-scheduler\",\"protocol\":\"tcp\",\"fromPort\":10259,\"toPort\":10259,\"sourceSecurityGroupIds\":[\"sg-0156151301759f178\",\"sg-030767034bf574232\"],\"sourceSecurityGroupRoles\":[\"controlplane\",\"node\"]}] security-group-id=\"sg-0156151301759f178\""
```
Notice here the difference in `sourceSecurityGroupIds` as well as the presence of `sourceSecurityGroupRoles` in the `want` group.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by r4f4**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

We are comparing sets that are not compatible, so rules will always be revoked and authorized during reconciliation. We need to expand the rules from the spec so there is one rule for each item in cidrBlock/sourceSecurityGroupIds.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5023 

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix comparison of ingress rules during Security Group reconciliation to avoid unnecessary revokes and authorizes.
```

### CODE REVIEW

**Review by mtulio — COMMENTED** [review]
overall LGTM, very good fix/improvement in the provision phase. 🎉 

Do you think we are covered in the [`ReconcileSecurityGroups`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/securitygroup/securitygroups_test.go)  or would be hard to reproduce in new case as revoke is in the same function, and/or would be nice to create a test dedicated to exercise `expandIngressRules()`?

**Comment by r4f4** [comment]
> Do you think we are covered in the [`ReconcileSecurityGroups`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/securitygroup/securitygroups_test.go) or would be hard to reproduce in new case as revoke is in the same function, and/or would be nice to create a test dedicated to exercise `expandIngressRules()`?

Good call. I can, at a minimum, add unit tests for the `expandIngressRules()` function. Will do that while I wait for CI results.

**Comment by r4f4** [comment]
Updated: add a few fixes and unit tests.

**Comment by r4f4** [comment]
Openshift CI results are all green! https://github.com/openshift/installer/pull/8596. Looking at the logs, the only rule being revoked is the one we explicitely removed from the cluster spec:
```
time="2024-06-13T21:27:14Z" level=debug msg="I0613 21:27:14.705844     356 securitygroups.go:181] \"Revoked ingress rules from security group\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-x5n2dn57-2d061-fxccx\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-x5n2dn57-2d061-fxccx\" reconcileID=\"1eebbaa2-4a91-478f-91df-6d0cf652d71c\" cluster=\"openshift-cluster-api-guests/ci-op-x5n2dn57-2d061-fxccx\" revoked-ingress-rules=[{\"description\":\"Bootstrap SSH Access\",\"protocol\":\"tcp\",\"fromPort\":22,\"toPort\":22,\"cidrBlocks\":[\"0.0.0.0/0\"]}] security-group-id=\"sg-0193bb8269722f9e3\""
time="2024-06-13T21:27:14Z" level=debug msg="I0613 21:27:14.705926     356 securitygroups.go:150] \"second pass security group reconciliation\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-x5n2dn57-2d061-fxccx\" namespace=\"openshift-cluster-api-guests\" reconcileID=\"1eebbaa2-4a91-478f-91df-6d0cf652d71c\" cluster=\"openshift-cluster-api-guests/ci-op-x5n2dn57-2d061-fxccx\" group-id=\"sg-06d4855d6bc549b25\" name=\"ci-op-x5n2dn57-2d061-fxccx-lb\" role=\"lb\""
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8596/pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn/1801355744365252608/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1718314761.log

**Comment by r4f4** [comment]
@damdo would you mind enabling tests on this PR?

**Comment by r4f4** [comment]
/cc @alexander-demicev 
I see you've recently changed this code. WDYT of this fix?

**Comment by r4f4** [comment]
@mtulio following your suggestion, I've added a unit test to check that we are not revoking ingress rules unnecessarily.

**Comment by r4f4** [comment]
`aws-e2e` failure doesn't seem to be cause by the PR changes:
```
   Should've eventually succeeded creating an AWS CloudFormation stack
  Expected
      <bool>: false
  to be true
  In [SynchronizedBeforeSuite] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/shared/suite.go:147 @ 06/20/24 17:24:37.437 
```

/test pull-cluster-api-provider-aws-e2e

**Comment by r4f4** [comment]
`aws-e2e`: the 2 e2e failures don't look related to the PR changes but will retest again to be sure.

## Test from this PR
In the [log of this PR](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5024/pull-cluster-api-provider-aws-e2e/1803843946229534720/artifacts/clusters/clusterctl-upgrade-p5kbnk/logs/capa-system/capa-controller-manager/capa-controller-manager-9bcf6d68f-4pv5v/manager.log) no revokes until the cluster is deleted.

## Test from another PR
Looking at an [old test log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5004/pull-cluster-api-provider-aws-e2e/1800546943219273728/artifacts/clusters/self-hosted-70i0jt/logs/capa-system/capa-controller-manager/capa-controller-manager-9bcf6d68f-ncmbf/manager.log):

```
I0611 16:19:08.741022       1 securitygroups.go:179] "Revoked ingress rules from security group" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="self-hosted-yr5v5v/self-hosted-70i0jt-klt6x" namespace="self-hosted-yr5v5v" name="self-hosted-70i0jt-klt6x" reconcileID="df380180-8af8-45d2-a1c0-fd7d1108558e" cluster="self-hosted-yr5v5v/self-hosted-70i0jt" revoked-ingress-rules=[{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-04c31b37099612208"]},{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-02a4d2faaf7102a28"]},{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-0799511b5638468a1"]},{"description":"bgp (calico)","protocol":"tcp","fromPort":179,"toPort":179,"sourceSecurityGroupIds":["sg-02a4d2faaf7102a28"]},{"description":"bgp (calico)","protocol":"tcp","fromPort":179,"toPort":179,"sourceSecurityGroupIds":["sg-0799511b5638468a1"]},{"description":"IP-in-IP (calico)","protocol":"4","fromPort":0,"toPort":0,"sourceSecurityGroupIds":["sg-02a4d2faaf7102a28"]},{"description":"IP-in-IP (calico)","protocol":"4","fromPort":0,"toPort":0,"sourceSecurityGroupIds":["sg-0799511b5638468a1"]}] security-group-id="sg-02a4d2faaf7102a28"
I0611 16:19:09.000272       1 securitygroups.go:193] "Authorized ingress rules in security group" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="self-hosted-yr5v5v/self-hosted-70i0jt-klt6x" namespace="self-hosted-yr5v5v" name="self-hosted-70i0jt-klt6x" reconcileID="df380180-8af8-45d2-a1c0-fd7d1108558e" cluster="self-hosted-yr5v5v/self-hosted-70i0jt" authorized-ingress-rules=[{"description":"bgp (calico)","protocol":"tcp","fromPort":179,"toPort":179,"sourceSecurityGroupIds":["sg-02a4d2faaf7102a28","sg-0799511b5638468a1"]},{"description":"IP-in-IP (calico)","protocol":"4","fromPort":-1,"toPort":65535,"sourceSecurityGroupIds":["sg-02a4d2faaf7102a28","sg-0799511b5638468a1"]},{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-04c31b37099612208","sg-02a4d2faaf7102a28","sg-0799511b5638468a1"]}] security-group-id="sg-02a4d2faaf7102a28"
```
So the following rules are being revoked:
```
[{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-04c31b37099612208"]},{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-02a4d2faaf7102a28"]},{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-0799511b5638468a1"]}
```
Then being authorized as:
```
{"description":"Kubernetes API","protocol":"tcp","fromPort":6443,"toPort":6443,"sourceSecurityGroupIds":["sg-04c31b37099612208","sg-02a4d2faaf7102a28","sg-0799511b5638468a1"]}
```

**Comment by r4f4** [comment]
/assign @nrb 

Tests look good. This is ready for review.

**Review by alexander-demicev — COMMENTED** [review]
Thanks taking care of this
/lgtm

**Comment by richardcase** [comment]
Thanks @r4f4 

/approve

**Pull request merged**
