### PR TITLE
Fix apidiff target

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- Fix apidiff target

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
API diff job works https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#pr-apidiff-main&show-stale-tests=

Which OS are you using?

**Comment by Prajyot-Parab** [comment]
> API diff job works https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#pr-apidiff-main&show-stale-tests=
> 
> Which OS are you using?

`Darwin Prajyots-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64`

**Comment by Prajyot-Parab** [comment]
> > API diff job works https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#pr-apidiff-main&show-stale-tests=
> > Which OS are you using?
> 
> ```
> Darwin Prajyots-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
> ```
> 
>  ```
> prajyotparab@Prajyots-MacBook-Pro cluster-api-provider-aws % make apidiff
> bash: -c: line 1: syntax error: unexpected end of file
> make: *** [apidiff] Error 2
> ```

@sedefsavas also checked on a linux VM just now, changes working fine there as well.

**Comment by Skarlso** [comment]
Oh wow, nice catch. I wonder how the job works. That's definitely a syntax error.

**Comment by Prajyot-Parab** [comment]
> Oh wow, nice catch. I wonder how the job works. That's definitely a syntax error.

I guess because job is running only on linux platform so its working fine, I observed issue on my Mac (Darwin).

**Comment by Ankitasw** [comment]
cc @richardcase for final approval.

**Comment by Ankitasw** [comment]
cc @sedefsavas

**Pull request merged**
