### PR TITLE
🌱 chore: update owners

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This updates the owners (and aliases) to reduce unecessary notifcations and review requests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by damdo** [comment]
Was this a request in one of the community meetings?

**Comment by richardcase** [comment]
> Was this a request in one of the community meetings?

It was mainly from a slack message that got me thinking. Perhaps a better option is keeping SCL leads & CAPI maintainers but remove CAPI reviewers? The idea being to reduce the notifications and unecessay assigments of PRs to people.

**Comment by richardcase** [comment]
A good topic for next weeks office hours?

**Comment by richardcase** [comment]
Until its been discussed:

/hold

**Review by AndiDog — COMMENTED** [review]
Since I can't join today's office hours:

/lgtm

**Pull request merged**
