### PR TITLE
[WIP] Add `create-ha-cluster` clusterawsadm subcommand

### LINKED ISSUE #415: Binary for automating HA cluster creation
/kind feature

**Describe the solution you'd like**

Automate the manual process that was defined for #414 

This can be built into clusterawsadm or provided as a separate binary.

/priority important-soon

### PR DESCRIPTION
**Pull request by sfzylad**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #415 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
@sfzylad this PR will likely be blocked until the pivot phase exists in `clusterctl` (https://github.com/kubernetes-sigs/cluster-api/issues/554).

**Comment by ncdc** [comment]
We'll want adequate time to test this and the v1alpha1 release is at the end of this week. Given that we have documentation on how to create a multi-node control plane, I'm comfortable deferring this until after the release.

/milestone Next

**Comment by sfzylad** [comment]
This PR is no longer valid. Because this has been implemented in CAPI, #720 has been created instead to solve this problem.

**Pull request closed without merging**
