### PR TITLE
✨ Add ability to customize APIServer LB listener port

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #1057

### CODE REVIEW

**Comment by vincepri** [comment]
@detiber @ncdc This should be good to go

**Comment by ncdc** [comment]
#1057 sounds like it's asking for both not hard-coding 6443 and the ability to add additional listeners to the ELB. Do we need to get clarification if both things are needed, as this PR only addresses the hard-coding issue?

**Comment by vincepri** [comment]
I dropped the `Fixes ...` so we can get at least this functionality in, I'll circle back with the person that opened the issue to see if this fits or we need more functionality as well

**Pull request merged**
