### PR TITLE
[E2E] Fix failing MHC test affected due to ebs-csi-driver version update

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area testing
/kind failing-test

**What this PR does / why we need it**:
This PR fixes the ebs-csi-driver properties due which the MHC tests are failing in the CI.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow up of #4147 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
Fix failing MHC test affected due to ebs-csi-driver version update
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
Hey @sbueringer , need a little help here.
The machine remediation tests are failing continuously in the CI, but passes locally.
I see that the MD is yet to be remediated and the test is timed out, you can see the status of machine as "deleting" [here](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/4173/pull-cluster-api-provider-aws-e2e/1640741285742514176/artifacts/clusters/bootstrap/resources/mhc-remediation-8hj7d1/Machine/mhc-remediation-yu39vw-md-0-7cb55b4f9b-v55pm.yaml), but the test fails before that. Could you please help check this issue? Is it possible to increase the remediation timeout at CAPI level?

cc @Skarlso @richardcase

**Comment by killianmuldoon** [comment]
Given this is a consistent failure rather than a flake I'm not sure if a timeout change is going to fix it. There's a lot of errors in the logs related to the PodDisruptionBudget - that's where I'd look first. Maybe updating Calico would solve the issue?

**Comment by killianmuldoon** [comment]
I've opened https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4176 to update Calico - probably a good idea anyway as some of the APIVersions used in the old file are no longer served. 

I've triggered the tests on that PR. I'm not certain, but the root cause may be the PodDisruptionBudget for Calico not being created meaning that node draining for MHC nodes isn't working so the machines can't be remediated.

**Comment by sbueringer** [comment]
@killianmuldoon @Ankitasw  How was the issue resolved? Is there any further follow-up required?

**Comment by Ankitasw** [comment]
I think we are good with this, thanks for following up @sbueringer

**Pull request merged**
