### PR TITLE
Drop unwanted SGs when calling attachSecurityGroupsToNetworkInterface

### PR DESCRIPTION
**Pull request by enxebre**
Before this, attachSecurityGroupsToNetworkInterface was re-applying existing SGs not specified in user intent. It's up to the caller to choose the right list of SG ids as in https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3ebf018bbfc5345fbd9d9598ea9392b2a349ed6c/controllers/awsmachine_security_groups.go#L57-L64 so then attachSecurityGroupsToNetworkInterface just applies what is given.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4361

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
attachSecurityGroupsToNetworkInterface do not re-apply existing security groups which are not specified by the user intent
```

### CODE REVIEW

**Comment by enxebre** [comment]
```
#7 [internal] load metadata for docker.io/library/golang:1.19.5
#7 ERROR: failed to copy: httpReadSeeker: failed open: content at https://mirror.gcr.io/v2/library/golang/manifests/sha256:572f68065ea605e0bd7ab42aa036462318e680a15db0f41a0cadcd06affdabdb?ns=docker.io not found: not found
```

**Comment by richardcase** [comment]
@enxebre - this probably needs a rebase so that it picks up the change to the Dockerfile that uses a public ECR registry for the golang image.

**Comment by enxebre** [comment]
thanks Richard! rebased.

**Comment by richardcase** [comment]
All the tests passed, so:

/approve
/lgtm

**Pull request merged**
