### PR TITLE
chore: set status.ready when machine is running

### LINKED ISSUE #1032: Status.Ready is never set on AWSMachines
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- spun up CAPI/CAPA/CABPK
- applied some YAML for controlplane
- infrastructure is provisioned, everything seems cool
- applied some YAML for a worker node

The node doesn't join because InfrastructureReady is not set on the controlplane Machine. Did some digging and found that CAPA never sets Status.Ready, which is what CAPI looks for. 

**What did you expect to happen:**
- worker node joins and everything is great

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:
Sets `.Status.Ready` to true when instance is running.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1032 

**Special notes for your reviewer**:
Is there anywhere in here we need to set it to false or is that too spicy?

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by rudoi** [comment]
@vincepri looking for some tips on adding a test for this. It doesn't look like we have any existing testing for the machinescope-related functions? Also the controller tests don't seem set up to work with mock AWS interfaces or stuff like that yet, so I'm just wondering what the most effective approach would be.

**Comment by vincepri** [comment]
Let's open up an issue to tackle unit testing the controller instead?

**Comment by rudoi** [comment]
> Let's open up an issue to tackle unit testing the controller instead?

https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1035

**Pull request merged**
