### PR TITLE
[E2E] Fix machine remediation tests

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind failing-test
/kind support

**What this PR does / why we need it**:
This PR updates the version of aws ebs csi driver which resolves the MD tests failures.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow up of #4173 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
Fix machine remediation tests
```

### CODE REVIEW

**Comment by Skarlso** [comment]
Oh wow really nice job.

/lgtm

**Comment by Ankitasw** [comment]
Urghhh, I ll check why other tests are failing.

**Comment by Skarlso** [comment]
@Ankitasw Where is this yaml coming from?

**Comment by Skarlso** [comment]
I'm only asking so I understand what these changes are and where they are coming from. :)

**Comment by Ankitasw** [comment]
Hey I took it from aws ebs csi driver repo templates.

**Comment by Skarlso** [comment]
Cool okay. So all we needed was an updated ebs csi deployment?

**Comment by Ankitasw** [comment]
Yes thats right 😊 i just updated the ebs driver to latest version and updated manifest.

**Comment by Ankitasw** [comment]
Looks like tests are still failing 🙁 i tried it locally and it worked.

**Comment by Skarlso** [comment]
Damn. Would love to have a cluster context right about now to see what's up. :/

**Comment by Ankitasw** [comment]
This is not required anymore

**Pull request closed without merging**
