### PR TITLE
Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
Hey @naveensrinivasan, thanks for the PR 🎉 .
It would be helpful if you could open an issue so that we can discuss your views with the community.

**Comment by naveensrinivasan** [comment]
Is there a reason why we can't do it here?

**Comment by Ankitasw** [comment]
> Thanks,Is there a reason why we can't do it here?

I am not super sure about this, so wanted other community members comments on this, we generally follow the practice to open an issue if you have any ideas/enhancements/bugs, and then once the issue is triaged, we raise PR for the same.

**Comment by richardcase** [comment]
Thanks @naveensrinivasan :tada: 

/lgtm
/approve

**Comment by naveensrinivasan** [comment]
> Thanks @naveensrinivasan 🎉
> 
> /lgtm /approve

Thank you!

**Pull request merged**
