### PR TITLE
Add ApplySecurityGroupsToLoadBalancer action to controllers role

### LINKED ISSUE #2156: Security Groups on API Server Load Balancer are not reconciled properly
/kind bug

**What steps did you take and what happened:**

Add a new security group to an API Server load balancer.  

This causes CAPA to start throwing error messages that it's missing permissions for `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer`

**What did you expect to happen:**

Security group would be reconciled properly (added or removed accordingly)

**Anything else you would like to add:**

Adding `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer` resolves issue and reconciliation of the load balancers continues as expected.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sedefsavas**
/kind bug

**What this PR does / why we need it**:
To support adding additional security groups to ELB, allowed ApplySecurityGroupsToLoadBalancer action.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2156

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
@enxebre This is for controllers.cluster-api-provider-aws.sigs.k8s.io role, the other is for control-plane role.

**Comment by enxebre** [comment]
>@enxebre This is for controllers.cluster-api-provider-aws.sigs.k8s.io role, the other is for control-plane role.

yeh so if the lb are currently meant to be managed by the infraProvider CRs which rely on `controllers.cluster-api-provider-aws.sigs.k8s.io` do we need `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer` in the control-plane role?

**Comment by sedefsavas** [comment]
@enxebre I mean this PR adds it to the controllers.cluster-api-provider-aws.sigs.k8s.io. 
We can keep track of removing it from the control-plane in another PR, I need to make sure it won't break anything first.

**Comment by randomvariable** [comment]
@enxebre, no you won't need it in your use case.

There's a separate issue for making more fine grained options for when you're externally managed, but can't find it right now.

> We can keep track of removing it from the control-plane in another PR

We need to keep this in the control plane IAM policies as this is part of the AWS Cloud Provider, separate to CAPA.

**Pull request merged**
