### PR TITLE
Apply #3871 "Update LoadBalancerReadyCondition on deletion" to release-1.5

### PR DESCRIPTION
**Pull request by mnitchev**
The LoadBalancerReadyCondition is sometimes explicitly patched and other times it only updates the awsCluster object. Furthermore the condition won't be patched by the patch helper in the AWSClusterReconciler, because it's not in the `patch.WithOwnedConditions` list. This change puts the condition in the list and also updates the condition reason to `Deleted` when the LB is not found. Without setting the condition in that case, the reconciler will set condition to `Deleting` and it will never go back to `Deleted`.

Co-authored-by: Jose Armesto <github@armesto.net>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This is #3871, but for the release-1.5. The original PR could not be backported due to conflicts.

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by AverageMarcus** [comment]
cc @richardcase 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3871 couldn't be cherry picked due to changes in type imports (I think) conflicting. This PR adds the same logic to the 1.5 codebase.

**Comment by dlipovetsky** [comment]
The import grouping needs to be fixed: https://github.com/dlipovetsky/cluster-api-provider-aws/commit/feb6e3236d0eacd003b82a5864d118a562f1d434

I also see the linter complain about a file that isn't touched by this PR: https://github.com/dlipovetsky/cluster-api-provider-aws/commit/2830053ee0f132475b470d1bcdba83057b7baa8c

**Pull request merged**
