### PR TITLE
chore: updated containerd version

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind support

**What this PR does / why we need it**:

An updated to the containerd version due to a dependabot alert.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Updating containerd dependency version.
```

### CODE REVIEW

**Comment by dlipovetsky** [comment]
Actually, are we supposed to update the indirect dependency, or update the direct dependency (in this case, I think that's cluster-api)

On main
```txt
❱ git describe HEAD
v1.2.0-93-g8996bcef
❱ grep "github.com/containerd/containerd" go.mod
	github.com/containerd/containerd v1.5.2 // indirect
❱ go mod graph | grep -e '\w github.com/containerd/containerd@v1.5.2'
sigs.k8s.io/cluster-api-provider-aws github.com/containerd/containerd@v1.5.2
sigs.k8s.io/cluster-api/test@v1.1.0-beta.1 github.com/containerd/containerd@v1.5.2
```

**Comment by pydctw** [comment]
> Actually, are we supposed to update the indirect dependency, or update the direct dependency (in this case, I think that's cluster-api)

Reading @dlipovetsky's comment, agree that we cannot update the indirect dependency as the containerd 1.5.2 will be pulled in anyway as cluster-api indirect dependency.

**Comment by dlipovetsky** [comment]
Fortunately, the test module [just updated](https://github.com/kubernetes-sigs/cluster-api/pull/5972) its dependency. I've [asked](https://kubernetes.slack.com/archives/C8TSNPY4T/p1643061326170700) that it be included in the imminent v1.1.0 release.

**Comment by dlipovetsky** [comment]
The v1.1.0 CAPI release will get this fix in https://github.com/kubernetes-sigs/cluster-api/pull/5973.

**Comment by sedefsavas** [comment]
Thanks @dlipovetsky for following up.
We can close this PR.

**Comment by richardcase** [comment]
Closing this after the discussion

**Pull request closed without merging**
