### PR TITLE
[release-2.3] 🌱 Bump go version to 1.21

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**
/kind support

**What this PR does / why we need it**:
Bump go version to 1.21, required by release tooling in the next minor version.

**Release note**:
```release-note
Bump go version to 1.21
```

### CODE REVIEW

**Comment by richardcase** [comment]
@damdo - i suspect this will solve the issue from the cherry pick in #4801

**Comment by damdo** [comment]
@richardcase  Yes, that's the plan 👍 Should we merge this first and retest the other one?

**Comment by richardcase** [comment]
> @richardcase Yes, that's the plan 👍 Should we merge this first and retest the other one?

Yes i think so

/lgtm
/approve

**Pull request merged**
