### PR TITLE
[wip] Update dependencies for Go 1.12

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:
k8s.io/kubernetes has been updated to Go 1.12, so attempt to do the same here.

Additionally rationalises WORKSPACE with sha256 sums and specified versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by randomvariable** [comment]
This is WIP because the new Gazelle keeps rewriting

```
        "//pkg/cloud/aws/services/awserrors:go_default_library",
        "//pkg/cloud/aws/services/ec2/mock_ec2iface:go_default_library",	
        "//pkg/cloud/aws/services/elb/mock_elbiface:go_default_library",
```
to 
```
        "//vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/ec2/mock_ec2iface:go_default_library",
        "//vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/elb/mock_elbiface:go_default_library",
```

and currently have no idea why.

**Comment by justaugustus** [comment]
Hey @randomvariable -- I was able to successfully test a capz cluster with:
- WORKSPACE
  - gazelle 0.16.0 -> 0.17.0
  - golang 1.11.5 -> 1.12.1
  - golangci-lint -> v1.16.0
  - kind -> 70beb5c9d114574313b4637ca91e41c5fa30bc3d
  - Kubernetes version 1.13.5 -> 1.14.0
- packages
  - containerd 1.2.4 -> 1.2.5 (set constants in config package)

this PR may be helpful for Go 1.12.1: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/168

**Comment by randomvariable** [comment]
@justaugustus thanks for this.

**Comment by randomvariable** [comment]
Formerly closing this. @vincepri is picking this up.

**Pull request closed without merging**
