### PR TITLE
fix: remove unused context imports

### LINKED ISSUE #4546: Broken tests for unused import for cloud/services/{network,ec2} in v2.2.4
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I stood up envtest and ran `go test ./pkg/...` on `v2.2.4` and I got the following failures for:
```
# sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2 [sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2.test]
pkg/cloud/services/ec2/bastion_test.go:20:2: "context" imported and not used
FAIL    sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/ec2 [build failed]

# sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network [sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network.test]
pkg/cloud/services/network/natgateways_test.go:20:2: "context" imported and not used
pkg/cloud/services/network/vpc_test.go:20:2: "context" imported and not used
FAIL    sigs.k8s.io/cluster-api-provider-aws/v2/pkg/cloud/services/network [build failed]
```

**What did you expect to happen:**
No errors on tests

**Anything else you would like to add:**
It looks like [this commit](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4510/commits/43b06c8918b86e08819aec9fec8479aa68659111) on the [Bump CAPI to v1.5.0](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4510) PR, introduced unused imports of `"context"` in:
```
pkg/cloud/services/network/natgateways_test.go
pkg/cloud/services/network/vpc_test.go
pkg/cloud/services/ec2/bastion_test.go
```

That PR got then merged against main, and then got also backported to `release-2.2`, for which a `v2.2.4` got cut today.
At the moment, this is not a problem on `main` as a new PR got merged there which makes use of those previously unused contexts: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4490
Although this still remains an issue on `release-2.2` and on `v2.2.4`.

**Environment:**
- Cluster-api-provider-aws version:  `v2.2.4`
- Kubernetes version: (use `kubectl version`):  local envtest (v1.24`)
- OS (e.g. from `/etc/os-release`): -

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes #4546

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
fix: remove unused context imports
```

### CODE REVIEW

**Comment by Skarlso** [comment]
What the heck. How? :O

**Comment by damdo** [comment]
The failures don't seem to be related WDYT @richardcase

**Comment by richardcase** [comment]
> The failures don't seem to be related WDYT @richardcase

No, these are other issues that have slipped through previously without the proper checks being in place.

Might be worth fixing the linter issues for `rand.Read` in this, wdyt?

**Comment by damdo** [comment]
> 
> > The failures don't seem to be related WDYT @richardcase
> 
> No, these are other issues that have slipped through previously without the proper checks being in place.
> 
> Might be worth fixing the linter issues for rand.Read in this, wdyt?

Fix included

**Comment by richardcase** [comment]
As the `pull-cluster-api-provider-aws-e2e-blocking-release-2-2` is a result of another change and wasn't picked up previously due to lack of PR checks i think we can merge this and follow up on another PR the failing test. I have created #4550 to do the follow up and marked it critical.

/override pull-cluster-api-provider-aws-e2e-blocking-release-2-2
/approve

**Pull request merged**
