### PR TITLE
ISSUE-2414: Add additional linters

### LINKED ISSUE #2414: Enable additional linters
Core cluster-api repo is enabling some additional linters, it'd be good for consistency to enable same linters.

https://github.com/kubernetes-sigs/cluster-api/issues/4622

/help
/good-first-issue
/milestone 0.7.x

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds new go linters 

**Which issue(s) this PR fixes**
Fixes #2414 

**Special notes for your reviewer**:
I used the list from https://github.com/kubernetes-sigs/cluster-api/issues/4622#issuecomment-841440852 + compared currently active linters in CAPI vs CAPA. The following linters are currently excluded: 
```
- dupl
- errcheck
- funlen
- gocritic
- gomnd
- whitespace
```
Let me know if you think you need some of these.

Thanks you 
**Checklist**:
- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
There are couple more PRs open under the cluster-api issue #4622: 
https://github.com/kubernetes-sigs/cluster-api/pull/4624
  exclude-use-default: false

https://github.com/kubernetes-sigs/cluster-api/pull/4631

We can keep an eye on that issue for more changes there and apply the relevant ones here.

/ok-to-test

**Comment by sedefsavas** [comment]
These look relevant for this PR:
https://github.com/kubernetes-sigs/cluster-api/pull/4649
https://github.com/kubernetes-sigs/cluster-api/pull/4624
https://github.com/kubernetes-sigs/cluster-api/pull/4657

Created a separate issue for doc linter: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2428

**Comment by sedefsavas** [comment]
Also: https://github.com/kubernetes-sigs/cluster-api/pull/4697

**Comment by Evalle** [comment]
Linters: 
```   
 - stylecheck
 - errcheck
 - gosec
 ```

should be added via separate PR

**Pull request merged**
