### PR TITLE
[WIP] ✨ Adds NAT gateway reconcilation test case to e2e

### PR DESCRIPTION
**Pull request by bhargavmad**
**What this PR does / why we need it**:

Steps followed:
 - Create a workload cluster
 - Manually delete the NAT gateway
 - Verify if the deleted NAT gateway gets reconciled and if the reconciled NAT gateway works without issues

### CODE REVIEW

**Comment by bhargavmad** [comment]
Hi @vincepri, Can you please port the changes made by #1421(fixes #1413) into the `release-0.4` branch? Thank you.

**Comment by vincepri** [comment]
@bhargavmad We usually don't backport new features to older release branches, is this PR impacted by that bug?

**Comment by bhargavmad** [comment]
> @bhargavmad We usually don't backport new features to older release branches, is this PR impacted by that bug?

@vincepri  Yes. This PR needs those changes. It tests out if the NAT gateway works out fine after reconciliation.

**Comment by vincepri** [comment]
We should rebase this PR on master then instead of release-0.4, are you able to do so?

**Comment by vincepri** [comment]
We really shouldn't backport that feature, given the backport policy we have in place, unless it's a bug and 0.2 is considered broken.

@ncdc thoughts?

**Comment by ncdc** [comment]
I'm 50-50... on the one hand, we're fixing a reconciliation issue (granted, against user error); on the other hand, we're alpha and continuing to backport left and right is more work than we really want to do.

@bhargavmad is there an issue & plan for making sure that release-0.4 and master are roughly at parity for the tests (i.e., get master updated)?

**Comment by bhargavmad** [comment]
> @bhargavmad is there an issue & plan for making sure that release-0.4 and master are roughly at parity for the tests (i.e., get master updated)?

@ncdc There is no issue created as of now, but it is definitely in the plans.

**Comment by bhargavmad** [comment]
It was agreed that the test will be directly written on to master. Waiting for the current e2e code(release-0.4 branch) to be moved onto master, and will then post a new PR against it. Closing now.

**Pull request closed without merging**
