### PR TITLE
[E2E] Enable EventBridge in the tests

### LINKED ISSUE #4090: [E2E] EventBridge feature to be enabled in one of the tests
/kind support
/kind failing-test
/kind flake 

**What steps did you take and what happened:**
In few of the test runs, EventBridge fails to create the rules in the eventbus. Refer [here](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-clusterclass/1627529141182009344/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-5dc575594d-dt72t/manager.log) for details. 
This brings us to the conclusion that EventBridge feature should be enabled only for one of the tests, such that all the tests wont be affected.

**What did you expect to happen:**
EventBridge feature is disabled in E2E tests. As part of this issue, we should reimagine a new/existing E2E to test EventBridge functionality such that other tests won't get affected by it.

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area testing
/kind flake

**What this PR does / why we need it**:
This PR enables the EventBridge feature in E2E tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4090 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
@richardcase its weird that tests are not failing at all now with EventBridge feature enabled 😅

**Comment by Skarlso** [comment]
This thing is ridiculous 🤣🤣

**Comment by Ankitasw** [comment]
Oh it has driven me crazy 😕

**Comment by Skarlso** [comment]
```
                           msg: "rate limit for github api has been reached. Please wait one hour or get a personal API token and assign it to the GITHUB_TOKEN environment variable",
                          stack: [0x1fc9526, 0x1fc871a, 0x13863bb, 0x1386497, 0x1387298, 0x138706a, 0x1386ff0, 0x1fc84f1, 0x1fc703f, 0x1fc5a52, 0x1fc5237, 0x224aa56, 0x224914e, 0x2248fa5, 0x22cd423, 0x22d449b, 0x23a0793, 0x2394eb0, 0x239eca8, 0x23c3e65, 0x4db905, 0x4dadfc, 0xa25727, 0xa35ff4, 0xa39878, 0x470521], 
```

PFF what the hell even.

**Comment by Ankitasw** [comment]
Looks like cluster api is also facing the same https://github.com/kubernetes-sigs/cluster-api/issues/8426

**Comment by Ankitasw** [comment]
I am just running the tests multiple times, to see if the flake has gone now.

**Comment by Ankitasw** [comment]
Looks like the EventBridge flake is gone(last failure was due to some other flake), so it should be ok to enable EventBridge feature in E2E tests.
cc @richardcase @Skarlso

**Comment by Skarlso** [comment]
Yaaay

**Comment by Ankitasw** [comment]
Ok I guess something is wrong with GPU tests 😫 
Will address it in separate PR after finding the cause.

**Comment by Ankitasw** [comment]
Looks like tests are passing now, can we merge this? Will keep an eye on E2E tests for a while till we feel EventBridge is stabilized and not causing flakes.

**Comment by Ankitasw** [comment]
cc @Skarlso @richardcase for final review

**Pull request merged**
