### PR TITLE
Support EC2 instance metadata options for the machine pools launch templates

### LINKED ISSUE #4370: Support EC2 instance metadata options for the machine pools launch templates
/kind feature

**Describe the solution you'd like**

The PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037 added support for metadata options in the `AWSMachine` & `AWSMachineTemplate` specs.
We need to have these EC2 metadata options configurable for machine pools as well.

These options are available via launch template settings for machine pools.

Machine pools (unmanaged or managed) have the following `awsLaunchTemplate` spec field:
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b4596fc1f975d15f8a12896f42586f97bc1144bf/exp/api/v1beta2/awsmachinepool_types.go#L64-L66
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b4596fc1f975d15f8a12896f42586f97bc1144bf/exp/api/v1beta2/awsmanagedmachinepool_types.go#L148-L152

This is the common piece of code creates the launch template for the machine pools:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b4596fc1f975d15f8a12896f42586f97bc1144bf/pkg/cloud/services/ec2/launchtemplate.go#L379-L420

In the function, there is a struct (of type `ec2.RequestLaunchTemplateData`) as returned by the helper function:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b4596fc1f975d15f8a12896f42586f97bc1144bf/pkg/cloud/services/ec2/launchtemplate.go#L444-L504

all we need to do is to set `MetadataOptions` on the launch template to be created:
```go
data.MetadataOptions = &ec2.LaunchTemplateInstanceMetadataOptionsRequest{
	HttpEndpoint:            &httpEndpoint,
	HttpPutResponseHopLimit: &httpPutResponseHopLimit,
	HttpTokens:              &httpTokens,
	InstanceMetadataTags:    &instanceMetadataTags,
}
```

And this would allow us to use the metadata configuration options as documented in the [cluster-api-aws docs](https://cluster-api-aws.sigs.k8s.io/topics/instance-metadata.html) with launch templates for the machine pools.

**Environment:**

- Cluster-api-provider-aws version:  `v2.1.4`
- Kubernetes version: (use `kubectl version`):  `v1.26.5-eks-c12679a`
- OS (e.g. from `/etc/os-release`): [Amazon EKS optimized Amazon Linux](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) 1.26

### PR DESCRIPTION
**Pull request by Fedosin**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds support for EC2 metadata options in the managed and unmanaged AWSMachinePools specs. These options are available via launch template settings for machine pools.

Here is a related [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4037) that adds these options for AWSMachine & AWSMachineTemplate.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4370

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Added support to allow users to configure EC2 instance metadata options for managed and unmanaged MachinePools
```

### CODE REVIEW

**Comment by wyike** [comment]
Did we run the upgrade tests from old capa cluster 2.2 to new capa?
1. 2.2 capa --> cluster1 deployed by 2.2 capa
2. upgrade capa to this new capa
3. upgrade cluster1

**Comment by Fedosin** [comment]
well, this is a backward compatible change. it should not affect any existing deployments, as InstanceMetadataOptions is optional and defaults to nil.

**Comment by muraee** [comment]
it seems this is a duplicate of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4384

**Comment by Fedosin** [comment]
Oh, I didn't notice that... @richardcase asked me to implement this feature, but since it's already done, it makes sense to close this PR.

**Pull request closed without merging**
