### PR TITLE
Update E2E

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Updates the e2e and integration test framework with the latest changes from the release-0.3 branch, and removes v1alpha1 oriented testing.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by detiber** [comment]
@ncdc this should be good to go now. It effectively removes all e2e and integration testing that was done (they were effectively testing v1alpha1-related items anyway :joy:) but brings over the framework and kind changes.

**Comment by ncdc** [comment]
I guess the plan is to copy/paste back some of the code that was deleted if it makes sense in the future, as we get closer to actual testing?

**Comment by detiber** [comment]
> I guess the plan is to copy/paste back some of the code that was deleted if it makes sense in the future, as we get closer to actual testing?

Potentially, but the amount that will need to be replaced is pretty trivial.

**Pull request merged**
