### PR TITLE
Use same golang version everywhere

### PR DESCRIPTION
**Pull request by mkumatag**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:

Use same golang version everywhere

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2736

**Special notes for your reviewer**:

This change will ensure that the same golang version has been used everywhere like building the binaries everywhere including binaries built in the dockerfile, outside.
**Checklist**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
Hi @mkumatag 👋 
Thanks for the PR.
Can we have a feature request/issue created for this in the [repo](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/new/choose) first, then we can go ahead with the proposal.

**Comment by mkumatag** [comment]
> Hi @mkumatag 👋
> Thanks for the PR.
> Can we have a feature request/issue created for this in the [repo](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/new/choose) first, then we can go ahead with the review of proposal.

done

**Comment by mkumatag** [comment]
This approach may not really work because I see some bot is updating the version for the Golang version in the Dockefile, wondering if there a custom way of updating some common place so that same version can be used in both the places makefile and the dockerfile!

**Pull request merged**
