### PR TITLE
Update EKS e2e to use k8s v1.22

### PR DESCRIPTION
**Pull request by pydctw**
**What this PR does / why we need it**:
EKS now supports k8s 1.22. Updated 
* CAPA EKS e2e to use the latest version
* EKS doc

Also, removed the calico related code as discussed in [slack](https://kubernetes.slack.com/archives/CD6U2V71N/p1654785897048359).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by pydctw** [comment]
As suite.go was refactored.
/test pull-cluster-api-provider-aws-e2e

**Comment by richardcase** [comment]
Nice changes @pydctw ...thanks 🎉 

/lgtm
/approve

**Pull request merged**
