### PR TITLE
[WIP][NOT FOR REVIEW] just kicking the tires

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by justaugustus** [comment]
Review goose wants to review:
/honk

**Comment by dims** [comment]
moving to another PR (save this for history)

/close

**Pull request closed without merging**
