### PR TITLE
Add v1alpha3 to v1alpha4 upgrade e2e test

### LINKED ISSUE #2388: Add v1alpha3 to v1alpha4 upgrade e2e test
Add an e2e test for v1alpha3 to v1alpha4 upgrade similar to what core cluster-api is adding [here](https://github.com/kubernetes-sigs/cluster-api/pull/3708) and run a basic scale test to make sure it is functional.

https://github.com/kubernetes-sigs/cluster-api/pull/3708

/help
/good-first-issue
/milestone v0.7.x

### PR DESCRIPTION
**Pull request by yuzhang17**
**What type of PR is this?**

**What this PR does / why we need it**:
Add an e2e test for v1alpha3 to v1alpha4 upgrade.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2388

**Special notes for your reviewer**:

**Checklist**:

**Release [note**:](url)

```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
@yuzhang17 - would you be able to fill in the release note section please?

**Comment by yuzhang17** [comment]
Hi, @sedefsavas Could you give me a hand. How can I test my code? I can't run the test case which I added before I merge my code.

**Comment by richardcase** [comment]
@yuzhang17 - it is possible to run the e2e tests locally against your own AWS account.

**Comment by yuzhang17** [comment]
do-not-merge/release-note-label-needed

**Comment by yuzhang17** [comment]
/do-not-merge/work-in-progress

**Comment by sedefsavas** [comment]
@yuzhang17 do you need help on running the tests locally?

**Comment by yuzhang17** [comment]
> @yuzhang17 do you need help on running the tests locally?

I only have a free tier aws account. But I found it is impossible run the test using a free tier aws account

**Comment by sedefsavas** [comment]
This PR is fixed here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2770

@yuzhang17 you are added as co-author to the new PR.
/close

**Pull request closed without merging**
