### PR TITLE
:running: Fix filters in e2e-conformance.sh

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Fixes an issue with applying filters for retrieving the bastion host in e2e-conformance.sh

### CODE REVIEW

**Comment by ncdc** [comment]
Do you want to run conformance on this?

**Comment by detiber** [comment]
Let's try that again and see if we can get it to finish under the 2h time limit this time...
/test pull-cluster-api-provider-aws-make-conformance

**Comment by detiber** [comment]
One more time, hopefully without a kind flake
/test pull-cluster-api-provider-aws-make-conformance

**Comment by detiber** [comment]
@ncdc conformance test passed, should be good to go now

**Comment by ncdc** [comment]
Thx!
/lgtm

**Pull request merged**
