### PR TITLE
🐛: elbv2: skip adding security groups to NLB in secret regions

### LINKED ISSUE #5029: Secret clouds don't support Security Groups on NLBs
/kind bug

**What steps did you take and what happened:**

Network Load Balancers support for security groups was added around Aug 2023 [1]. Some regions, like the secret regions C2S/SC2S, still don't support security groups for NLBs.

[1] https://aws.amazon.com/blogs/containers/network-load-balancers-now-support-security-groups/

**What did you expect to happen:**

No errors such as 
```
"loadbalancer.go:101 "failed to create LB: err <= InvalidConfigurationRequest: Security groups are not supported for load balancers of type 'network'"
```

**Anything else you would like to add:**

PR to follow.

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by r4f4**
Secret regions don't yet support security groups for NLBs.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

C2S/SC2S regions do not support security groups on Network load balancers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5029 

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fix: do not attach security groups for Network Load Balancers in secret regions.
```

### CODE REVIEW

**Comment by r4f4** [comment]
Openshift e2e results for the public cloud are good (no breakage): https://github.com/openshift/installer/pull/8636

I'm trying to get this changed tested on a secret region.

**Comment by r4f4** [comment]
Update: 
* add a fix for info message with a spurious "%s"
* print a different message for regions that do not support NLB security groups. `loadbalancer.go:1799: Pre-existing NLB %s without security groups, cannot reconcile security groups` might be confusing on those cases.

**Comment by dmc5179** [comment]
I'm an OCP SSA supporting the customers who use the us-iso and us-isob regions. In earlier testing of the new CAPA changes I discovered that, while AWS commercial supports NLBs with security groups, the us-iso and us-isob regions do not. If the openshift-installer attempts to add security groups to an NLB in the iso regions it will fail and error out. I tested this proposed code change in the us-iso regions and found that the openshift-installer successfully provisions the NLBs without security groups.

**Comment by r4f4** [comment]
Now that we've tested it in a secret cloud:
/assign @richardcase

**Review by damdo — COMMENTED** [review]
/lgtm

Thanks!

**Comment by damdo** [comment]
/assign @richardcase @nrb
Would you mind stamping you approval here? TY

**Pull request merged**
