### PR TITLE
Add file and make commands for nightly build

### PR DESCRIPTION
**Pull request by enxebre**
**What type of PR is this?**

**What this PR does / why we need it**:
Set up nightly build.
Follow up for:
https://github.com/kubernetes/test-infra/pull/22546
https://github.com/kubernetes/test-infra/pull/22560

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by enxebre** [comment]
cc @sbueringer @richardcase @sedefsavas @randomvariable

**Comment by randomvariable** [comment]
looks ok to me. i'll defer to @sedefsavas

**Pull request merged**
