### PR TITLE
Bump aws-vpc-cni to v1.15.0

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area release
/kind support

**What this PR does / why we need it**:
This PR bumps aws-vpc-cni to v1.15.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4503 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Bump aws-vpc-cni to v1.15.0
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
PR is ready for review.

**Comment by Skarlso** [comment]
I don't remember at the top of my head, but don't we have to update and tests that are launching aws-vpc-cni?

**Comment by Ankitasw** [comment]
@Skarlso I have executed EKS E2E tests are it passed. We just have to bump and run the test to see if it works fine, but I dont remember if we have any dedicated tests for AWS VPC CNI

**Comment by Skarlso** [comment]
Ah, never mind. I was thinking about `VPC_ADDON_VERSION`.

**Pull request merged**
