### PR TITLE
Update AMIs and Calico

### PR DESCRIPTION
**Pull request by detiber**
- Update containerd to v1.2.5
- Update kubernetes-cni to v0.7.5
- Publish AMIs for Kubernetes v1.13.5 and v1.14.0
- Update machines template to use v1.13.5 by default
- Update Calico to v3.6.0

### CODE REVIEW

**Comment by detiber** [comment]
I did a quick smoke test deployment of both a v1.13.5 and a v1.14.0 cluster and I believe we are good now.

**Comment by detiber** [comment]
The referenced v1.13.5 and v1.14.0 AMIs are already published and live.

**Comment by ncdc** [comment]
Content LGTM. @vincepri are you interested in doing a manual test of this? I know Jason said he did one himself.

**Pull request merged**
