### PR TITLE
fix: apply security groups by ENI rather than instance

### LINKED ISSUE #638: Additional security groups not applied to control plane
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Created a control plane machine with AdditionalSecurityGroups as follows:

```yaml
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: controlplane-0
  namespace: my-cluster
  labels:
    cluster.k8s.io/cluster-name: my-cluster
    set: controlplane
spec:
  versions:
    kubelet: v1.13.3
    controlPlane: v1.13.3
  providerSpec:
    value:
      additionalSecurityGroups:
        - id: sg-1234567
      apiVersion: awsprovider/v1alpha1
      kind: AWSMachineProviderSpec
      instanceType: "t2.medium"
      iamInstanceProfile: "my-profile"
      keyName: "cluster-api-provider-aws.sigs.k8s.io"
```

Saw in logs that control plane reconciliation was looping after:
```
I0308 17:28:05.970023       1 instances.go:407] Attempting to update security groups on instance "i-03a829e5f06e4504f"
```

I added an additional log statement:
```go
if _, err := s.scope.EC2.ModifyInstanceAttribute(input); err != nil {
        // here
	klog.Errorf("failed to modify security groups: %v", err)
	return errors.Wrapf(err, "failed to modify instance %q security groups", instanceID)
}
```

```
E0308 17:28:06.126219       1 instances.go:415] failed to modify security groups: InvalidInstanceID: There are multiple interfaces attached to instance 'i-03a829e5f06e4504f'. Please specify an interface ID for the operation instead.
```

Looks like we need some additional handling, because IIRC, we would need ModifyNetworkInterfaceAttribute once the instance has multiple network interfaces?

**What did you expect to happen:**

Additional security groups applied to control plane

**Environment:**

- Cluster-api-provider-aws version: current master
- Kubernetes version: (use `kubectl version`): 1.13.3
- OS (e.g. from `/etc/os-release`): kind on macOS 10.14.3

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:

Additional security groups are now applied via ec2.ModifyNetworkInterfaceAttribute rather than ec2.ModifyInstanceMetadata in order to support instances with multiple ENIs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #638 

**Release note**:

```release-note
Support adding security groups to instances with multiple network interfaces
```

### CODE REVIEW

**Comment by vincepri** [comment]
@detiber thoughts on putting this into v1alpha1?

**Comment by detiber** [comment]
I don't have any objections to this change as a short term solution, however longer term we'll probably want to consider the possibility of not wanting to apply the same set of security groups to all attached ENIs.

/lgtm

**Comment by detiber** [comment]
@vincepri no objections for me to including in v1alpha1

**Pull request merged**
