### PR TITLE
[WIP] refactor: make events part of the API definition

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Currently created to aid discussion in the next office hours**

This changes the event reasons to be part of the API contract. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Event reasons are now part of the api contract and have guarantees
```

### CODE REVIEW

**Comment by dlipovetsky** [comment]
This is a great idea. Events are critical for usability, particularly understanding what has gone wrong. 

If Events become part of the API, we will want introduce, deprecate reasons, and even experiment with them (in one word, to evolve Events).

How can we evolve Events for users that consume CAPA as a go module, and those who do not?

**Comment by enxebre** [comment]
Is there any particular use case that is driving this? Generally speaking events are not meant to be contractual so I'm just curious

**Comment by richardcase** [comment]
@enxebre - a few people run automation based on events. And so this was to see what it would look like if we made it part of our contract to provider stability.

I'm sat on the fence in regards to this.

**Comment by richardcase** [comment]
We need more discussion on this.

/close

**Pull request closed without merging**
