### PR TITLE
:sparkles: Add flags for leaderElection timeouts

### PR DESCRIPTION
**Pull request by nikParasyr**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Add flags on manager to configure leaseDuration, renewDeadline and RetryPeriod for leader election. Set defaults based on cluster-api. These flags can be useful when the cluster runs on a relatively slow etcd.

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [X] includes documentation
- [X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)

**Release note**:
```release-note
add flags to manager for leaderElection timeouts
```

### CODE REVIEW

**Comment by nikParasyr** [comment]
Not sure whether this should be categorized as :sparkles: or :seedling:

**Comment by nrb** [comment]
@nikParasyr I think ✨ is fine

**Comment by nikParasyr** [comment]
e2e passed but there were a couple of failed runs. Are they flaky or are the defaults not "so sane"?

**Comment by damdo** [comment]
@nikParasyr I don't see leader election churn in the CAPA controller logs for the failed E2E runs:
```
$ curl -sL https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/4845/pull-cluster-api-provider-aws-e2e/1765438070502461440/artifacts/clusters/bootstrap/controllers/capa-controller-manager/capa-controller-manager-6b8f8b488c-kwsbn/manager.log | grep leader

I0306 18:18:11.235696       1 leaderelection.go:250] attempting to acquire leader lease capa-system/controller-leader-elect-capa...
I0306 18:18:11.242312       1 leaderelection.go:260] successfully acquired lease capa-system/controller-leader-elect-capa
I0306 18:18:11.242916       1 recorder.go:104] "events: capa-controller-manager-6b8f8b488c-kwsbn_b073f072-da92-434f-a015-f43ddac83c9f became leader" type="Normal" object={"kind":"Lease","namespace":"capa-system","name":"controller-leader-elect-capa","uid":"fa6fe129-aeb8-4a9a-9c21-f89b48547ad9","apiVersion":"coordination.k8s.io/v1","resourceVersion":"1062"} reason="LeaderElection"
```

Plus I've seen those timeouts in other runs.
IMO unrelated. So PR should be good

/lgtm

**Pull request merged**
