### PR TITLE
feat: Create bastion security group only when bastion is enabled

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What type of PR is this?**
For EC2 clusters, create the bastion security group only if the bastion is enabled. #3028 introduced this feature for EKS clusters.

This repeats the original PR (#3482), which was merged before I added unit tests, and unfortunately had a bug in the implementation. That PR was reverted in #3495.

Special thanks to @pydctw for finding the cause of the bug, and suggesting a fix! :bow: 

The first commit of this PR is the original fix, with the bug. The second commit adds a _failing_  test that confirms the implementation bug , and the final commit fixes the bug. I want to squash the commits before merging.

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
@dkoshkin pointed out that this is a **breaking change**, since today, EC2 clusters with a disabled Bastion have the bastion security group, and users may be relying on its existence. I'd like feedback on this, please!

I've added a unit test that verifies
(a) the correct roles are returned
(b) the default roles are not modified by calls to the function

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [x] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
LGTM, we can squash the commits whenever ready.

**Comment by sedefsavas** [comment]
Also, this is a good feat to backport for v1.5.0 release.

**Comment by Ankitasw** [comment]
LGTM as well.

**Comment by pydctw** [comment]
This was indeed an interesting bug. Thanks for fixing and adding unit tests, @dilyevsky 

/lgtm

**Comment by dlipovetsky** [comment]
Squashed commits.

**Comment by dlipovetsky** [comment]
> Also, this is a good feat to backport for v1.5.0 release.

I didn't realize we had already cut a [1.5 branch](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/release-1.5).

/cherry-pick release-1.5

**Pull request merged**
