### PR TITLE
allow specifying additional ingress rules

### LINKED ISSUE #2798: Allow customisation of node rules
/kind feature

**Describe the solution you'd like**

One of the most common requests we have is to allow customisation of the node security group. In particular, users want to often change the SSH ingress rule when bastion is enabled or not, and either disable or change the node port ruleset.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.7.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/area api
/area networking
/priority important-soon
/milestone v0.8.0

### PR DESCRIPTION
**Pull request by clive-jevons**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Allows specifying additional ingress rules to be added to the generated security groups.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2798

**Special notes for your reviewer**:

**Checklist**:

- [x ] squashed commits
- [ ] includes documentation
- [x ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Added additionalIngressRules section to NetworkSpec allowing the specification of additional ingress rules by security group role
```

### CODE REVIEW

**Comment by shivi28** [comment]
Thanks @clive-jevons for the PR 🎉 , but can you please sign the CLA using instructions given [here]( https://git.k8s.io/community/CLA.md#the-contributor-license-agreement).

**Comment by clive-jevons** [comment]
@shivi28 <- done 😊👍

**Comment by shivi28** [comment]
Hey @[clive-jevons](https://github.com/clive-jevons) are you still working on this?

**Comment by clive-jevons** [comment]
Hi @shivi28 <- not actively, since the related Issue was closed ... if the PR is of any interest, I'll go to the trouble of the rebase, but if there's no more interest in this, then I'd close the PR ;) (Thnx for reaching out 🙏🏻😁)

**Comment by richardcase** [comment]
@clive-jevons - would you be interested in morphing this to solve #392?

**Comment by clive-jevons** [comment]
> @clive-jevons - would you be interested in morphing this to solve #392?

@richardcase <- principally yes, but I'd need more guidance on what an acceptable implementation should look like, seeing as my initial idea didn't seem to resonate with the team ;) 

(Also: sorry for the late reply, was heads-down in getting something finished for my day-time job the last few weeks 😉)

**Pull request closed without merging**
