### PR TITLE
[release-1.5] Bump cluster-api to v1.1.5

### PR DESCRIPTION
**Pull request by sedefsavas**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
#5 34.90   Could not connect to deb.debian.org:80 (199.232.30.132), connection timed out

/test pull-cluster-api-provider-aws-verify-release-1-5

**Comment by Ankitasw** [comment]
@sedefsavas is there a reference where I can see why minSize for MP is reduced to 0(might have overlooked it)?

**Comment by sedefsavas** [comment]
This is ready to review @richardcase

**Pull request merged**
