### PR TITLE
🐛 Fix bastion  and AWSMachinePool connectivity

### LINKED ISSUE #1985: Connectivity between bastions and AWSMachinePool nodes may not work
/kind bug
/help

Breaking out of #1968

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

A check may need to be added to ec2.GetCoreNodeSecurityGroups to ensure that when running in EKS, the bastion security group gets added.

```
if scope.IsEKSManaged() {
   sgRoles = append(sgRoles, infrav1.SecurityGroupEKSNodeAdditional)
}
```

**What did you expect to happen:**
Can connect from bastion to machine pool instance.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by felipeweb**
**What this PR does / why we need it:**

Add missing security groups into node launch template.

Fixes #1985 

I will send another PR to solve #2231. It needs some refactor in Launch template stuff to be reusable between AWSMachinePool  and  AWSManagedMachinePool

### CODE REVIEW

**Comment by randomvariable** [comment]
/ok-to-test
/lgtm
/assign @richardcase 
for approval.

**Comment by richardcase** [comment]
I've kicked off the e2e tests for eks, will approve once they have passed.

**Comment by richardcase** [comment]
The eks e2e test [passed](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/2235/pull-cluster-api-provider-aws-e2e-eks/1356618704820899840)

**Comment by richardcase** [comment]
We should also  extend the e2e tests in the future to ensure that the bastion functionality is covered. Created #2238

**Comment by felipeweb** [comment]
@richardcase  I don't understand if it is falling because are something wrong in the code or it is just a timeout error. could you help me with it?

**Comment by richardcase** [comment]
> I don't understand if it is falling because are something wrong in the code or it is just a timeout error. could you help me with it?

It could be just a timeout. I will run it again and see if it fails at the same place. If it does I will look at the logs. I don't think its something wrong in this change.

**Comment by randomvariable** [comment]
Looks like a flake to me.

**Comment by felipeweb** [comment]
@randomvariable @richardcase  what I need to do about it?

**Comment by randomvariable** [comment]
@felipeweb nothing.

I'll leave to @richardcase to approve, but I think this is good to merge

**Comment by richardcase** [comment]
It looks good to me and eks e2e tests pass. The non-eks e2e tests aren't passing my looks like a flake so:

/approve

**Pull request merged**
