### PR TITLE
Add missing permissions for EKS OIDC provider configuration

### PR DESCRIPTION
**Pull request by codablock**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR adds 3 missing permissions/actions for EKS cluster management, related to OIDC provider association/configuration. Without these, EKS reconciliation fails directly after cluster creation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Add missing permissions for EKS OIDC provider configuration
```

### CODE REVIEW

**Comment by Jacobious52** [comment]
I think this is also missing `DisassociateIdentityProviderConfig` when changing the OIDC config. With only the inclusions in the PR it fails to disassociate and I needed to manually add it

**Comment by codablock** [comment]
@Jacobious52 Thanks for pointing this out. Added it in an additional commit.

**Comment by sedefsavas** [comment]
cc @richardcase do we want to merge this for tomorrow's release?

**Comment by richardcase** [comment]
@sedefsavas - yes that would be great. Be good to run the e2e first though

/test ?

**Comment by richardcase** [comment]
@codablock - Would be good to squash the 2 commits but as the release is today:

/approve

**Pull request merged**
