### PR TITLE
:book: Update AMIs for Kubernetes v1.16.15 and v1.19.1

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold

Going to omnibus this with the v1.19.1 AMIs.

/assign @vincepri

**Review by vincepri — APPROVED** [review]
/approve

**Comment by randomvariable** [comment]
test failure fixed in #1937

**Pull request merged**
