### PR TITLE
Adds an E2E test for using peered VPCs and an internal ELB

### LINKED ISSUE #3249: Create E2E tests for managed infrastructure
/kind feature

**Describe the solution you'd like**
Create additional e2e tests to validate the following use cases for the AWSCluster code base.
- Provision a Cluster with externally managed Security Groups
- Provision a Cluster with internal ELB
- Provision Management and Workload Clusters in peered VPCs

**Anything else you would like to add:**
Some of the functions to support this were added in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3237. I'm finishing up adding security group functions now and have built most of the scaffolding for the test themselves.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by josh-ferrell**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Creates an E2E test for creating clusters in peered VPCs and creating a workload cluster using an internal ELB.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3249

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [X] adds or updates e2e tests

**Release note**:

```release-note
Adds an E2E test that validates clusters in peered VPCs and cluster creation using an internal ELB.
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
@josh-ferrell thank you for the PR.
Personally, I have never worked with peering VPC, so I would let @sedefsavas give feedback here.

**Comment by josh-ferrell** [comment]
@sedefsavas when you get a free moment will you review this PR?

**Comment by sedefsavas** [comment]
This is a great way to do both internal ELB and peering validation at the same time!

One question, instead of creating management cluster's infra, could we have used the ones auto-generated? In that case, we need to do some SDK calls to get the IDs and then do the peering with the workload cluster. Not asking to change the way it is, just curious.

Also, have you confirmed in your local that `DeleteInfrastructure()` is not leaving any resource behind? Not sure if we have the clean up logic in boskos for everything created here.

**Comment by sedefsavas** [comment]
It would be great to have a documentation for deployment in internet-restricted environments, possibly with a diagram of the scenario tested here. Do you want to open an issue for this?

**Comment by josh-ferrell** [comment]
> It would be great to have a documentation for deployment in internet-restricted environments, possibly with a diagram of the scenario tested here. Do you want to open an issue for this?

Technically the workload isn't Internet restricted egress wise, the API server is just on the internal ELB. I've been thinking we need to architect and document a validated airgapped deployment if we don't have one already. I can open an issue to do so.

**Comment by josh-ferrell** [comment]
> This is a great way to do both internal ELB and peering validation at the same time!
> 
> One question, instead of creating management cluster's infra, could we have used the ones auto-generated? In that case, we need to do some SDK calls to get the IDs and then do the peering with the workload cluster. Not asking to change the way it is, just curious.
> 
> Also, have you confirmed in your local that `DeleteInfrastructure()` is not leaving any resource behind? Not sure if we have the clean up logic in boskos for everything created here.

I hadn't thought about using the CAPA created infrastructure to peer but I'm also still learning the SDK so it's now on my list to look into. 

DeleteInfrastructure took some time to get consistent but I think we're well covered. I could add some additional validation and probably will when refactoring the security groups test to use the same setup.

**Pull request merged**
