### PR TITLE
Update calico in e2e tests

### LINKED ISSUE #2435: Update calico in e2e tests
We use calico v3.13.2 for our e2e tests: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2a183f580873ed46aebdbba77da212a3476682aa/test/e2e/data/cni/calico.yaml#L2

We should upgrade this to a more recent version such as 3.18.4, for reasons like `apiextensions.k8s.io/v1beta` is deprecated.

/help
/good-first-issue
/milestone v0.7.x
/priority backlog

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind other

**What this PR does / why we need it**:
Updates Calico version + yaml files in e2e tests. 

**Which issue(s) this PR fixes** 
Fixes #2435 

**Special notes for your reviewer**:

**Checklist**:
- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
/test pull-cluster-api-provider-aws-e2e

If e2e passes, should be safe to go.

**Comment by richardcase** [comment]
The e2e passed so:

/lgtm

(will leave for @randomvariable  to approve)

**Pull request merged**
