### PR TITLE
Update and require CRDv1

### PR DESCRIPTION
**Pull request by h0tbird**
**What this PR does / why we need it**:

- Update all dependencies to v0.17.2, which is Kubernetes v1.17.2
- Update controller-runtime to v0.5.0
- Updates the CRDs to v1.
- Updates kubebuilder-tools to 1.16.4

### CODE REVIEW

**Comment by vincepri** [comment]
@h0tbird is this ready to be reviewed?

**Comment by h0tbird** [comment]
@vincepri not yet, this `pull-cluster-api-provider-aws-test` is failing. I am trying to reproduce it locally but it seems to work:
```
 controllers git:(crdv1) go test
Running Suite: Controller Suite
===============================
Random Seed: 1582049244
Will run 38 of 38 specs

I0218 19:07:29.291703   87647 awscluster_controller.go:70]  "msg"="Cluster Controller has not yet set OwnerRef" "awsCluster"="foo" "namespace"="default"
••••••••••••••••••••••••••••••••••••••

Ran 38 of 38 Specs in 5.253 seconds
SUCCESS! -- 38 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	sigs.k8s.io/cluster-api-provider-aws/controllers	6.107s
```
I can use some help to understand what is going on.

**Comment by detiber** [comment]
I believe the test failure is from using an older version of the controller-runtime binaries used by `envtest`. I believe @vincepri did a bit of work in the cluster-api repo to pull down newer binaries.

**Comment by h0tbird** [comment]
Thank you @detiber, I finally was able to reproduce the error by running `./scripts/ci-test.sh`.
I have updated to `kubebuilder-tools-1.16.4` which provides the right `kube-apiserver` binary for the tests.

**Comment by randomvariable** [comment]
/lgtm
Looks pretty much the same as CAPVs.

**Pull request merged**
