### PR TITLE
:running: AWS SDK updated to v1.31.3, tag NAT gateway on creation

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Updates the AWS SDK version to v1.13.3.
This has the newer EC2 API that allows us to tag NAT gateways on creation, removing
one API call

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
/approve
holding lgtm for e2e run to finish

**Comment by randomvariable** [comment]
Timed out hitting the defaulting webhook

**Comment by detiber** [comment]
/lgtm

Only e2e failure is a known flake

**Pull request merged**
