### PR TITLE
:bug: Remove empty patches key in config/crd/kustomization.yaml

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Fixes issue when generating components using kustomize

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by chuckha** [comment]
If you run `kustomize edit fix` in a dir with kustomization.yaml it will make some additional changes.

See https://github.com/kubernetes-sigs/kustomize/issues/1429

**Comment by chuckha** [comment]
I did something like 

```
cd config
for i in $(find . -type f -name kustomization.yaml -exec dirname {} \;); do cd $i && kustomize edit fix && cd -; done
```

but YMMV. `kustomize edit fix` is a bit rough.

**Comment by vincepri** [comment]
This change is already in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1047/files, I'll rebase

/lgtm

**Pull request merged**
