### PR TITLE
🌱 bump aws sdk version

### PR DESCRIPTION
**Pull request by stefanmcshane**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Requested change to reduce the size of #4906

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
 Bump aws-sdk-go to v1.51
```

### CODE REVIEW

**Comment by stefanmcshane** [comment]
/test pull-cluster-api-provider-aws-verify

`make verify-modules` works locally without error

**Comment by AndiDog** [comment]
`failed: No matching PR type indicator found in title.` – please go through the checklist in the PR template

**Comment by AndiDog** [comment]
`apidiff` differences look fine since only new SDK function signatures were added, AFAICS. Only the the PR formalities must be fixed, I think.

/lgtm

**Comment by stefanmcshane** [comment]
Made all the necessary changes @AndiDog. Let me know if you need anything else 😄

**Comment by AndiDog** [comment]
The commit contains lots of unrelated changes. Probably a rebase mistake?

**Comment by damdo** [comment]
Thank you for this PR @stefanmcshane 
Could you please rebase your PR against main?
TY

**Comment by AndiDog** [comment]
/lgtm

but must be rebased

**Comment by richardcase** [comment]
I'd love to get this in and backported:

/cherrypick release-2.4

**Comment by richardcase** [comment]
@stefanmcshane - would you be able to rebase this and then i will approve.

**Comment by richardcase** [comment]
Thanks @stefanmcshane.

/test ?

**Comment by richardcase** [comment]
Just in case:

/test pull-cluster-api-provider-aws-e2e-eks

**Comment by richardcase** [comment]
/lgtm
/approve

Until the e2e passes:

/hold

**Comment by richardcase** [comment]
The e2e passed so:

/unhold

**Pull request merged**
