### PR TITLE
Fix the broken link in the doc

### PR DESCRIPTION
**Pull request by mkumatag**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Fix the broken link in the doc

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
Hey @mkumatag. Thanks for the PR.
Assigning is not required as the reviewers are already assigned to your PR (bot just gives an example)
/unassign @neolit123 
/lgtm

**Comment by mkumatag** [comment]
> Hey @mkumatag. Thanks for the PR.
> Assigning is not required as the reviewers are already assigned to your PR (bot just gives an example)

This is coming from here - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4a14a37be7caf0b9239a59431d0a73fafece23e3/OWNERS_ALIASES#L8, because we have [sig-cluster-lifecycle-leads](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4a14a37be7caf0b9239a59431d0a73fafece23e3/OWNERS#L4) as approvers. Anyways thanks for unassigning `neolit123` from the PR.
> /unassign @neolit123
> /lgtm

**Comment by Ankitasw** [comment]
> This is coming from here -
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4a14a37be7caf0b9239a59431d0a73fafece23e3/OWNERS_ALIASES#L8
> 
> , because we have [sig-cluster-lifecycle-leads](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/4a14a37be7caf0b9239a59431d0a73fafece23e3/OWNERS#L4) as approvers. Anyways thanks for unassigning `neolit123` from the PR.

@mkumatag yes he is one of the approvers, but there is no need to assign, there are other approvers as well in the same file, so they will approve as per the availability

**Pull request merged**
