### PR TITLE
[E2E] Add check that the pod list is not empty.

### PR DESCRIPTION
**Pull request by Skarlso**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Adding a check that ensures that the pod list isn't empty. The for loop after it wouldn't error if there would be no pods.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
@Skarlso tests are failing, could you PTAL?

**Comment by Skarlso** [comment]
Yeah I'll work on this today.

**Comment by Skarlso** [comment]
Interestingly enough for whatever reason, the coredns pod doesn't get an ip address.

```
 STEP: checking if pod ip address is ipv6 based: aws-node-x5594:2600:1f14:a9f:8a04:195f:dd40:db95:653a
STEP: checking if pod ip address is ipv6 based: coredns-657694c6f4-k78sp: 
```

Luckily, the aws-node does, so... it's enough to check that one.

**Comment by Skarlso** [comment]
Oh of course, because I'm not waiting for them to have an IP address at all. 🤦

**Comment by Skarlso** [comment]
```
STEP: checking if pods list is empty: 0
```

What in tarnation? OH!!! 🤦  The label selector is incorrect.

**Comment by Skarlso** [comment]
The label is now `k8s-app=aws-node` instead of `app=aws-node`. :D lovely. :D

**Comment by Skarlso** [comment]
Finally!!!!!!!!!!!!!!! :D

```
STEP: checking if pods list is empty: 1
STEP: checking if pod ip address is ipv6 based: aws-node-dngtq/2600:1f13:9b5:e004:981c:66d2:21f9:ef92
STEP: Deleting cluster eks-nodes-1c16wy
STEP: Waiting for cluster eks-nodes-1c16wy to be deleted
• [SLOW TEST:1496.124 seconds] 
```

**Comment by Skarlso** [comment]
@richardcase If you so please. :D

**Comment by richardcase** [comment]
Nicely done @Skarlso , bravo 🎉 

Let's wait for the e2e to pass, but it would be good to squash the changes....especially as they are for 1 file :)

**Comment by Skarlso** [comment]
Yep will do that once the tests pass :)))

**Comment by Ankitasw** [comment]
New commit looks like rebased changes.
/lgtm

**Pull request merged**
