### PR TITLE
feat: add support for taints for managed machine pools

### LINKED ISSUE #2399: Add taints support to AWSManagedMachinePool
/kind feature
/area provider/eks
/priority important-soon
/milestone v0.7.0
/help
/good-first-issue

**Describe the solution you'd like**
EKS managed nodegroups supports node taints and we should add support for this to CAPA and expose this via `AWSManagedMachinePool`.

**Anything else you would like to add:**
We need to handle this for both [creation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/bc14da8fedc9b23c97261b93fedfdb7ad2a6ef99/pkg/cloud/services/eks/nodegroup.go#L171) and [update](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/bc14da8fedc9b23c97261b93fedfdb7ad2a6ef99/pkg/cloud/services/eks/nodegroup.go#L333) of a EKS node pool.

The AWS SDK will need to be updated so that the [CreateNodeGroup](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#EKS.CreateNodegroup) and [UpdateNodegroupConfig](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#EKS.UpdateNodegroupConfig) have the taints field available on the input

**Environment:**

- Cluster-api-provider-aws version: 0.6.5

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This adds support for specifying taints on the `AWSManagedMachinePool` that will translate into taints being set on the nodes of the the EKS node group that is created.

It also supports updating the taints for a node group.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2399 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits

**Release note**:
```release-note
Taints supported on EKS node groups created via AWSmanagedMachinePool 
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
I didn't realize most of this was related to AWS SDK version bump, I could have gotten to it sooner =)

LGTM after rebase.

**Comment by richardcase** [comment]
Whilst doing extra testing:

/hold

**Comment by richardcase** [comment]
Local tests worked so:

/unhold

**Pull request merged**
