### PR TITLE
add events for AWS cloud service failures

### PR DESCRIPTION
**Pull request by sadysnaat**
**What this PR does / why we need it**:
This PR adds events to AWS cloud service failures 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sadysnaat** [comment]
@detiber this is the new PR for cloud events changes https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1512

**Comment by randomvariable** [comment]
LGTM so far, pending linting.

**Comment by sadysnaat** [comment]
@randomvariable liniting done.

**Comment by randomvariable** [comment]
Cool, thx. Are you done and want to remove the WIP or have you got some more to do?

**Comment by sadysnaat** [comment]
Done with changes removed [WIP]

**Comment by randomvariable** [comment]
Great, if you could also squash the commits, we can get this through final review.

**Comment by sadysnaat** [comment]
Squash done, please have a review :)

**Comment by randomvariable** [comment]
Apologies @sadysnaat , could you rebase and squash again, so sorry!

**Comment by sadysnaat** [comment]
No worries @randomvariable, rebase squash done. Please have a review :)

**Pull request merged**
