### PR TITLE
Restructure repository / cleanup

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR is an effort to cleanup the repository structure, in particular:
- Removes the `aws` portion from `pkg/cloud/aws/...` packages, which seems redundant.
- Gives machine and cluster scopes their own package under `pkg/cloud/scope`.
- Moves the control plane locker helper functions under `ClusterScope`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
@vincepri any reason to not switch up to the kubebuilder v2 directory layout in the process as well? I don't see any particular reason we need to keep /pkg around.

**Comment by vincepri** [comment]
I am not sure if we should remove pkg/..., maybe we can promote the controllers up later and match kubebuilder v2, but it seems like a much bigger change

**Comment by vincepri** [comment]
@ncdc @detiber Is this good to go?

**Pull request merged**
