### PR TITLE
Fixes node join for v1.13

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Fixes the error on node join where file and bootstrapToken are mutually exclusive.

/assign @chuckha

### CODE REVIEW

**Comment by detiber** [comment]
Will rebase once https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/439 merges

**Comment by chuckha** [comment]
what's up with that merge commit? will that get squashed?

**Comment by vincepri** [comment]
Does this also include changes that were in #431 ?

**Comment by chuckha** [comment]
@vincepri yep!

**Comment by detiber** [comment]
rebased

**Pull request merged**
