### PR TITLE
Scope nodeRef to workload cluster

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR makes sure that NodeRef is set only in case the manager is running on the workload cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
lgtm, but I'd like to give some time for community review.

@rudoi @sethp-nr

**Comment by rudoi** [comment]
👍 from me

**Comment by sethp-nr** [comment]
We're not using anything requiring cross-cluster nodeRefs to work, and that does seem really fraught to us. 👍 from me as well.

**Pull request merged**
