### PR TITLE
update manifest to match latest release

### PR DESCRIPTION
**Pull request by mweibel**
**What type of PR is this?**
/kind cleanup

(no idea if this is the right type TBH)

**What this PR does / why we need it**:
Adds missing update to the repositories' manifest.yaml

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
Thanks for the fix.

/ok-to-test

/lgtm
/approve

**Comment by mweibel** [comment]
hm, not sure why that test doesn't work :/

**Comment by sedefsavas** [comment]
@meghanajangi apidiff target is not working. Could you take a look?

**Comment by sedefsavas** [comment]
Failures not related to this PR.

**Comment by meghanajangi** [comment]
> link

Checking the apidiff issue

**Pull request merged**
