### PR TITLE
Bump to golangci-lint v1.45.2

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- Bump to golangci-lint v1.45.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:
```
Bump to golangci-lint v1.45.2
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
Hey @Prajyot-Parab, thanks for the PR. JFYI, we have dependabot configured which will take care of these version bumps.
/lgtm

**Comment by Ankitasw** [comment]
@Prajyot-Parab could you please rebase this PR, so that we can merge it?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab could you please rebase this PR, so that we can merge it?

Done.

**Comment by Ankitasw** [comment]
@Prajyot-Parab can you please run target `make modules` locally?

**Comment by Ankitasw** [comment]
@Prajyot-Parab can you push a blank commit, looks like netlify deploy is still processing even after 5 hrs

**Pull request merged**
