### PR TITLE
Renaming kubernetes.io/cluster tag to use EKS cluster name

### PR DESCRIPTION
**Pull request by knabben**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
This PR changes the tag kubernetes.io/cluster/ to have the same EKS cluster name as the other objects, instead of the CAPI cluster name.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3572

**Special notes for your reviewer**:
1. Adding IAMAUTH mocker with mockgen
2. Increasing the coverage of EKS module for createCluster, this test will guarantee no regressions in the tag.

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by faiq** [comment]
I think you want to change this to use KubernetesClusterName as well https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/cluster.go#L365

**Comment by knabben** [comment]
> I think you want to change this to use KubernetesClusterName as well https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/cluster.go#L365

At this point, if we do this change the ELB will stop to work again since EKS is not using the CAPI name in the CCM configuration.

**Comment by faiq** [comment]
> I think you want to change this to use KubernetesClusterName as well https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/eks/cluster.go#L365

> At this point, if we do this change the ELB will stop to work again since EKS is not using the CAPI name in the CCM configuration.

Yes, the function I sent you should use `KubernetesClusterName`, not `Name` and keep the other tags as they are in main. (I authored the original change to get the Load Balancers to work.)

This should address the inconsistencies described in #3572.

**Comment by sedefsavas** [comment]
/lgtm
cc @richardcase for another review. 
We can cherry pick this one to release-1.5 too? Looks important enough.

**Comment by richardcase** [comment]
@sedefsavas - yes lets cherry pick this for 1.5.

/approve

**Comment by Skarlso** [comment]
Ah, nice, this will make MY PR smaller now since you added the mock for the IAM one for create cluster. :)

**Comment by Skarlso** [comment]
Hey @knabben!

It looks like this is breaking the upgrade flow test. Would you mind taking a look at this error:

```
E0713 19:35:41.930286 1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane eks-upgrade-onnuy2/eks-upgrade-sijk09-control-plane: checking owner of eks-upgrade-onnuy2_eks-upgrade-sijk09-control-plane is eks-upgrade-sijk09: %!w()" "name"="eks-upgrade-sijk09-control-plane" "namespace"="eks-upgrade-onnuy2" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="AWSManagedControlPlane"
```

In this run: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3568/pull-cluster-api-provider-aws-e2e-eks/1547298125415190528

**Comment by Skarlso** [comment]
Never mind. I think it's my fault, I haven't merged in this PR apparently in another PR I was running. 🤦 I thought I did, but apparently I didn't.

**Comment by Skarlso** [comment]
```
E0714 05:23:46.831908       1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane eks-upgrade-vkundt/eks-upgrade-pupqgg-control-plane: checking owner of eks-upgrade-vkundt_eks-upgrade-pupqgg-control-plane is eks-upgrade-pupqgg: %!w(<nil>)" "name"="eks-upgrade-pupqgg-control-plane" "namespace"="eks-upgrade-vkundt" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="AWSManagedControlPlane"
```

So it's still the same problem even after merging this PR.

**Pull request merged**
