### PR TITLE
🌱 Add conditions for the reconcile delete workflow

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Adding conditions for the reconcile delete workflow

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1867

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold
for CAPI version v0.3.9

**Comment by fabriziopandini** [comment]
/hold cancel
rebase on top of CAPI v0.3.9

**Comment by gab-satchi** [comment]
thanks @fabriziopandini 

/lgtm

**Comment by randomvariable** [comment]
@fabriziopandini needs a rebase unfortunately.

**Comment by fabriziopandini** [comment]
@randomvariable no problem!
done

**Comment by randomvariable** [comment]
@fabriziopandini oof, looks like some nil pointers in the tests

**Pull request merged**
