### PR TITLE
Backports

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Backports from master for release-0.3

**Release note**:
```release-note
NONE
```

/hold

### CODE REVIEW

**Comment by chuckha** [comment]
that ci test is an expected failure. number of commits match how far behind release-0.3 is. Looks good to me. feel free to ping me if you need sign off after you remove the hold 👍

**Comment by detiber** [comment]
The purpose of my hold was to avoid auto-merging (to retain merge commit) since I was hoping to workaround the CI issue by creating a branch for the PR vs just merging master. Removing the hold since it obviously did not work :joy:

/cancel hold
/cc @chuckha

**Comment by detiber** [comment]
Manually merging to preserve individual commits

**Pull request merged**
