### PR TITLE
:seedling: Update Go version to 1.22.6

### PR DESCRIPTION
**Pull request by nrb**
**What type of PR is this?**

/kind support

**What this PR does / why we need it**:

Updates to Go 1.22 in order to account for updated Go module toolchain behaviors.

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
Should we update the go version in the other places as well? 

- https://github.com/search?q=repo%3Akubernetes-sigs%2Fcluster-api-provider-aws%201.21&type=code

**Review by damdo — COMMENTED** [review]
I already included it in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5061/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R23

But if we want to do that early that's ok too

/lgtm

**Comment by nrb** [comment]
> Should we update the go version in the other places as well?

Will update some of these, but fwiw the go.mod can be left alone unless we're using [Go 1.22-specific features](https://tip.golang.org/doc/go1.22#language).

**Comment by damdo** [comment]
It looks like this is now blocking other PRs as the [verify job is permafailing](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5088/pull-cluster-api-provider-aws-verify/1821115926821474304#) until this merges. cc. @nrb

**Comment by nrb** [comment]
@damdo @richardcase Updated Go version in all the relevant places I could find. Also bumped to the latest patch release.

**Pull request merged**
