### PR TITLE
Backport to release-0.3: Fix errant formatting (#802)

### PR DESCRIPTION
**Pull request by sethp-nr**
move the backtic where it belongs, and linkify the Kubernetes issue.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by chuckha** [comment]
/lgtm
/approve

d

**Comment by detiber** [comment]
/close
closing to try and reset prow

**Pull request merged**
