### PR TITLE
Only enable IPv6 if it's already enabled in the config

### PR DESCRIPTION
**Pull request by Skarlso**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3912

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
/lgtm

until tests passes
/hold

**Comment by Ankitasw** [comment]
cc @richardcase for final approval

**Comment by Ankitasw** [comment]
cc @richardcase @dlipovetsky for review

**Comment by Jacobious52** [comment]
Any change for a accelerated 2.0.3 bump with this fix? It has stopped reconciliation of all of our clusters, blocking creation and deletion of clusters as well.

**Comment by Skarlso** [comment]
@Jacobious52 hello. There a couple of things if I recall that need to be present right now in a release but we'll try to squeeze one out. :)

**Comment by scott-thomas-charter** [comment]
Any chance getting 2.0.3 pushed soon with this resolution. We are stuck on cluster creation and deletion and hoping to avoid creating a custom image.

**Comment by Skarlso** [comment]
@scott-thomas-charter We are actually planning to do a release in the coming week so yes. Hopefully if our milestone is finished we can release this soon.

**Pull request merged**
