### PR TITLE
netlify: Attempt to resolve build speed issues

### LINKED ISSUE #2680: Netlify not building
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

PRs are failing Netlify tests. Not sure why.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2680 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by karuppiah7890** [comment]
The issue is just that the build takes a lot of time? https://app.netlify.com/sites/kubernetes-sigs-cluster-api-provider-aws/deploys/611f75e8a8716c00074d90f2#L224-L228

So, 13 mins is high? And it allows the build to complete above time limit but fails the build? 🤔 

In this PR I noticed the time to be around 11 mins. What's the time limit on the account's builds?

**Comment by randomvariable** [comment]
@karuppiah7890 It's about 15 minutes. So previously, it processed a bunch of directories separately. gen-api-crd-docs has a slow initialisation time, so doing it this way saves about 10% from local testing. There isn't a way of increasing the netlify time limit without paying more i think?

**Comment by karuppiah7890** [comment]
Makes sense! The increase of time - yeah, I noticed the time and payments stuff when I was searching about issues around build time

**Pull request merged**
