### PR TITLE
🌱 Add addtional linters

### PR DESCRIPTION
**Pull request by tech-geek29**
**What this PR does / why we need it:**

Part of our ongoing effort to enable more linters to take the human equation out of enforcing and catching minor issues.
This enables the exportloopref, ifshort, and nilerr linters.

- errcheck
- exportloopref
- godot
- gosec
- importas
- ifshort 
- nilerr
- stylecheck
- whitespace

This PR also removes `golint` linter as it is deprecated.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Related #2471

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
LGTM after rebase.

**Comment by tech-geek29** [comment]
> LGTM after rebase.

Rebase done!

**Comment by sedefsavas** [comment]
Thanks @tech-geek29 
/lgtm
/approve

**Pull request merged**
