### PR TITLE
:seedling: Re-enables multi-az in e2e tests

### LINKED ISSUE #1806: Re-enable multi-AZ e2e testing
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
With #1803 and #1805 merged, should be possible to re-enable multi-AZ in e2e testing.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by gab-satchi**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1806 

/hold to run e2e tests
/test pull-cluster-api-provider-aws-e2e

### CODE REVIEW

**Comment by randomvariable** [comment]
@gab-satchi looks like these are going to fail. Didn't reach ready in time.

**Comment by gab-satchi** [comment]
yeah it's strange. I'll try locally and see how quickly it reaches ready. I've got numbers from the previous changes so should be able to compare

**Comment by randomvariable** [comment]
Given the load on prow, maybe foolish to assume this is going to work this week :(

**Comment by gab-satchi** [comment]
ah okay. Tried it locally and it's just as fast now as it was with just one az. Used `us-west-2` to try to be more in line with prow. we can pick up next week

**Comment by randomvariable** [comment]
Need to unpick some stuff here

```
E0710 19:35:36.339315       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster test-lz2r85/test-infra-mfid39: failed to disassociate Elastic IP \"35.155.18.50\" with allocation ID \"eipalloc-0e50150d21685a4c2\": Still associated with association ID \"eipassoc-0fd56114be5a129ea\"" "controller"="awscluster" "name"="test-infra-mfid39" "namespace"="test-lz2r85"
I0710 19:35:36.340624       1 awscluster_controller.go:140] controllers/AWSCluster "msg"="Reconciling AWSCluster delete" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" 
E0710 19:35:41.124090       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster test-lz2r85/test-infra-mfid39: failed to disassociate Elastic IP \"35.155.18.50\" with allocation ID \"eipalloc-0e50150d21685a4c2\": Still associated with association ID \"eipassoc-0fd56114be5a129ea\"" "controller"="awscluster" "name"="test-infra-mfid39" "namespace"="test-lz2r85"
I0710 19:35:41.125948       1 awscluster_controller.go:140] controllers/AWSCluster "msg"="Reconciling AWSCluster delete" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" 
E0710 19:35:45.137514       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster test-lz2r85/test-infra-mfid39: failed to disassociate Elastic IP \"35.155.18.50\" with allocation ID \"eipalloc-0e50150d21685a4c2\": Still associated with association ID \"eipassoc-0fd56114be5a129ea\"" "controller"="awscluster" "name"="test-infra-mfid39" "namespace"="test-lz2r85"
I0710 19:35:45.139845       1 awscluster_controller.go:140] controllers/AWSCluster "msg"="Reconciling AWSCluster delete" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" 
E0710 19:35:49.069948       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster test-lz2r85/test-infra-mfid39: failed to disassociate Elastic IP \"35.155.18.50\" with allocation ID \"eipalloc-0e50150d21685a4c2\": Still associated with association ID \"eipassoc-0fd56114be5a129ea\"" "controller"="awscluster" "name"="test-infra-mfid39" "namespace"="test-lz2r85"
I0710 19:35:49.071801       1 awscluster_controller.go:140] controllers/AWSCluster "msg"="Reconciling AWSCluster delete" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" 
E0710 19:35:53.033702       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster test-lz2r85/test-infra-mfid39: failed to disassociate Elastic IP \"35.155.18.50\" with allocation ID \"eipalloc-0e50150d21685a4c2\": Still associated with association ID \"eipassoc-0fd56114be5a129ea\"" "controller"="awscluster" "name"="test-infra-mfid39" "namespace"="test-lz2r85"
I0710 19:35:53.034551       1 awscluster_controller.go:140] controllers/AWSCluster "msg"="Reconciling AWSCluster delete" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" 
E0710 19:35:57.049823       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error deleting network for AWSCluster test-lz2r85/test-infra-mfid39: failed to disassociate Elastic IP \"35.155.18.50\" with allocation ID \"eipalloc-0e50150d21685a4c2\": Still associated with association ID \"eipassoc-0fd56114be5a129ea\"" "controller"="awscluster" "name"="test-infra-mfid39" "namespace"="test-lz2r85"
I0710 19:35:57.051370       1 awscluster_controller.go:140] controllers/AWSCluster "msg"="Reconciling AWSCluster delete" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" 
I0710 19:36:01.369315       1 eips.go:158] controllers/AWSCluster "msg"="released ElasticIP" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" "allocation-id"="eipalloc-0e50150d21685a4c2" "eip"="35.155.18.50"
I0710 19:36:01.607703       1 eips.go:158] controllers/AWSCluster "msg"="released ElasticIP" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" "allocation-id"="eipalloc-0eb95949f4d06b3a2" "eip"="35.155.50.129"
I0710 19:36:01.888662       1 eips.go:158] controllers/AWSCluster "msg"="released ElasticIP" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" "allocation-id"="eipalloc-062827b53ca6b2a28" "eip"="52.10.123.152"
I0710 19:36:02.204729       1 gateways.go:103] controllers/AWSCluster "msg"="Detached internet gateway from VPC" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" "internet-gateway-id"="igw-0bf8e3efd30072f0b" "vpc-id"="vpc-0b671dc2790eb3734"
I0710 19:36:02.375095       1 gateways.go:115] controllers/AWSCluster "msg"="Deleted internet gateway in VPC" "awsCluster"="test-infra-mfid39" "cluster"="test-3sav2m" "namespace"="test-lz2r85" "internet-gateway-id"="igw-0bf8e3efd30072f0b" "vpc-id"="vpc-0b671dc2790eb3734"
I0710 19:36:22.909503       1 awscluster_controller.go:79] controllers/AWSCluster "msg"="Cluster Controller has not yet set OwnerRef" "awsCluster"="test-infra-ikoy5l" "namespace"="test-oqg61k" 
I0710 19:36:22.922162       1 awscluster_controller.go:79] controllers/AWSCluster "msg"="Cluster Controller has not yet set OwnerRef" "awsCluster"="test-infra-ikoy5l" "namespace"="test-oqg61k" 
I0710 19:36:22.949257       1 awscluster_controller.go:166] controllers/AWSCluster "msg"="Reconciling AWSCluster" "awsCluster"="test-infra-ikoy5l" "cluster"="test-4r31hk" "namespace"="test-oqg61k" 
I0710 19:36:27.853780       1 gateways.go:132] controllers/AWSCluster "msg"="Created internet gateway for VPC" "awsCluster"="test-infra-ikoy5l" "cluster"="test-4r31hk" "namespace"="test-oqg61k" "vpc-id"="vpc-0420111f56444fcae"
I0710 19:36:28.025569       1 gateways.go:147] controllers/AWSCluster "msg"="attached internet gateway to VPC" "awsCluster"="test-infra-ikoy5l" "cluster"="test-4r31hk" "namespace"="test-oqg61k" "internet-gateway-id"="igw-00f6fc828701323d0" "vpc-id"="vpc-0420111f56444fcae"
E0710 19:36:28.434860       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster test-oqg61k/test-infra-ikoy5l: failed to create one or more IP addresses for NAT gateways: failed to allocate Elastic IP: AddressLimitExceeded: The maximum number of addresses has been reached.\n\tstatus code: 400, request id: bac5e6d4-402e-4962-861d-eb8fd07900e1" "controller"="awscluster" "name"="test-infra-ikoy5l" "namespace"="test-oqg61k"
I0710 19:36:28.436937       1 awscluster_controller.go:166] controllers/AWSCluster "msg"="Reconciling AWSCluster" "awsCluster"="test-infra-ikoy5l" "cluster"="test-4r31hk" "namespace"="test-oqg61k" 
E0710 19:36:29.755516       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster test-oqg61k/test-infra-ikoy5l: failed to create one or more IP addresses for NAT gateways: failed to allocate Elastic IP: AddressLimitExceeded: The maximum number of addresses has been reached.\n\tstatus code: 400, request id: ae785d93-92e3-4886-87de-40ea86698ff8" "controller"="awscluster" "name"="test-infra-ikoy5l" "namespace"="test-oqg61k"
I0710 19:36:29.756815       1 awscluster_controller.go:166] controllers/AWSCluster "msg"="Reconciling AWSCluster" "awsCluster"="test-infra-ikoy5l" "cluster"="test-4r31hk" "namespace"="test-oqg61k" 
E0710 19:36:31.054105       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster test-oqg61k/test-infra-ikoy5l: failed to create one or more IP addresses for NAT gateways: failed to allocate Elastic IP: AddressLimitExceeded: The maximum number of addresses has been reached.\n\tstatus code: 400, request id: a004978b-e09b-4bb4-a6a4-158ff24b1090" "controller"="awscluster" "name"="test-infra-ikoy5l" "namespace"="test-oqg61k"
I0710 19:36:31.054991       1 awscluster_controller.go:166] controllers/AWSCluster "msg"="Reconciling AWSCluster" "awsCluster"="test-infra-ikoy5l" "cluster"="test-4r31hk" "namespace"="test-oqg61k" 
E0710 19:36:32.299590       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile network for AWSCluster test-oqg61k/test-infra-ikoy5l: failed to create one or more IP addresses for NAT gateways: failed to allocate Elastic IP: AddressLimitExceeded: The maximum number of addresses has been reached.\n\tstatus code: 400, request id: 02758b79-99ed-4325-a4ec-de94c42c5ff5" "controller"="awscluster" "name"="test-infra-ikoy5l" "namespace"="test-oqg61k"
```

**Comment by randomvariable** [comment]
Looking at the logs, lots of limits being hit. I wonder if the AWS janitor hasn't been running successfully.
Posted in Slack at https://kubernetes.slack.com/archives/C7J9RP96G/p1594643991354200

**Comment by gab-satchi** [comment]
Is there a 5 EIP limit for CI accounts as well? I've hit the limit on some local tests as well now that we allocate a NAT gw per AZ, any test creating more than one cluster in a 3 az environment fails.

**Comment by randomvariable** [comment]
@gab-satchi ah, yes! will need to reduce parallelisation then.

**Comment by randomvariable** [comment]
After discussion with @gab-satchi , going to pivot to deduping tests, ensuring we're not hitting limits etc... all in the new clusterctl e2e tests.
/close

**Pull request closed without merging**
