### PR TITLE
:bug: fix: create ingress rules from all load balancers

### LINKED ISSUE #4865: SecondaryControlPlaneLoadbalancer ingress rules not applied
/kind bug

**What steps did you take and what happened:**
Ingress rules specified in the secondary load balancer are not applied.

**What did you expect to happen:**
All ingress rules to be applied.

**Anything else you would like to add:**
The following cluster spec:
```
	awsCluster := &capa.AWSCluster{
		Spec: capa.AWSClusterSpec{
			ControlPlaneLoadBalancer: &capa.AWSLoadBalancerSpec{
				Name:             ptr.To("internal"),
				LoadBalancerType: capa.LoadBalancerTypeNLB,
				Scheme:           &capa.ELBSchemeInternal,
				AdditionalListeners: []capa.AdditionalListenerSpec{
					{
						Port:     22623,
						Protocol: capa.ELBProtocolTCP,
					},
				},
				IngressRules: []capa.IngressRule{
					{
						Description: "Machine Config Server internal traffic from cluster",
						Protocol:    capa.SecurityGroupProtocolTCP,
						FromPort:    22623,
						ToPort:      22623,
						CidrBlocks:  []string{"10.0.0.0/16"},
					},
				},
			},
                       SecondaryControlPlaneLoadBalancer = &capa.AWSLoadBalancerSpec{
			        Name:                   ptr.To("external"),
			        LoadBalancerType:       capa.LoadBalancerTypeNLB,
			        Scheme:                 &capa.ELBSchemeInternetFacing,
			        IngressRules: []capa.IngressRule{
				     {
					     Description: "Kubernetes API Server traffic for public access",
					     Protocol:    capa.SecurityGroupProtocolTCP,
					     FromPort:    6443,
					     ToPort:      6443,
					     CidrBlocks:  []string{"0.0.0.0/0"},
				     },
                               },
			},
		},
	}

```
The allow-all on 6443 rules won't be applied to the security group.

**Environment:**

- Cluster-api-provider-aws version: main @ b2bebfb80d58f488b8e54c957c1f5070bfc03dc2
- Kubernetes version: (use `kubectl version`): 1.29
- OS (e.g. from `/etc/os-release`): RHCOS

### PR DESCRIPTION
**Pull request by r4f4**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Makes sure that ingress rules from all load balancers are created.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4865 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Fixed a bug where ingress rules specified in the secondary load balancer were not applied to the security group.
```

### CODE REVIEW

**Comment by nrb** [comment]
Looks like there's a lint fix needed. Also, could you please add a release note for the fix?

Otherwise, it looks good, thanks!

**Comment by r4f4** [comment]
Update: fixed linting issues, commit message issue and added a release note.

**Comment by Ankitasw** [comment]
Since this is an api-change, shall we wait for v1beta3 to take this change?

**Comment by vincepri** [comment]
@Ankitasw It shouldn't impact v1beta3 as far as I can tell, the code is mostly cleaned up here and an older function deprecated, which should be backward compatible

**Pull request merged**
