### PR TITLE
Make EKS conversion tests run and fix failing conversion tests

### LINKED ISSUE #3023: EKS conversion tests not failing upon missing conversions
EKS Bootstrap package's conversion tests are not failing when there are conversion issues although the conversion tests are in place.

/kind bug
/triage accepted

### PR DESCRIPTION
**Pull request by pydctw**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
EKS API conversion tests were silently exiting with panic due to an incorrect webhook config path.

This PR enables the tests and fixed failing conversion tests in v1alpha3 and v1alpha4.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3023

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:
```release-note
Make EKS conversion tests run and fix failing conversions
```

### CODE REVIEW

**Comment by pydctw** [comment]
The log shows that EKS API conversion tests failed to run. It shows ok but actually exiting due to panic as mentioned in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3032.
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-aws-test/1470879475473321984#1:build-log.txt%3A654
```
ok  	sigs.k8s.io/cluster-api-provider-aws/bootstrap/eks/api/v1alpha3	0.093s
ok  	sigs.k8s.io/cluster-api-provider-aws/bootstrap/eks/api/v1alpha4	0.072s
```

Compared to main API conversion tests
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-aws-test/1470879475473321984#1:build-log.txt%3A271
```
ok  	sigs.k8s.io/cluster-api-provider-aws/api/v1alpha3	81.737s
=== RUN   TestFuzzyConversion
=== RUN   TestFuzzyConversion/for_AWSCluster
=== RUN   TestFuzzyConversion/for_AWSCluster/spoke-hub-spoke
...
```

**Comment by pydctw** [comment]
assign @richardcase

**Comment by pydctw** [comment]
After enabling tests, conversion tests were failing with a nil pointer error.
```
=== RUN   TestFuzzyConversion
--- FAIL: TestFuzzyConversion (1.79s)

Process finished with the exit code 1
=== RUN   TestFuzzyConversion/for_EKSConfig
    --- FAIL: TestFuzzyConversion/for_EKSConfig (1.79s)
=== RUN   TestFuzzyConversion/for_EKSConfig/spoke-hub-spoke
        --- PASS: TestFuzzyConversion/for_EKSConfig/spoke-hub-spoke (1.79s)
=== RUN   TestFuzzyConversion/for_EKSConfig/hub-spoke-hub
        --- FAIL: TestFuzzyConversion/for_EKSConfig/hub-spoke-hub (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x203cc13]

goroutine 33041 [running]:
testing.tRunner.func1.2({0x21849e0, 0x3214150})
	/usr/local/opt/go/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/opt/go/libexec/src/testing/testing.go:1212 +0x218
panic({0x21849e0, 0x3214150})
	/usr/local/opt/go/libexec/src/runtime/panic.go:1038 +0x215
sigs.k8s.io/cluster-api-provider-aws/bootstrap/eks/api/v1alpha4.(*EKSConfig).ConvertTo(0xc000d971e0, {0x2566b30, 0xc0005e1860})
	/Users/wkwon/go/src/github.com/pydctw/cluster-api-provider-aws/bootstrap/eks/api/v1alpha4/conversion.go:44 +0x153
sigs.k8s.io/cluster-api/util/conversion.FuzzTestFunc.func1.2(0xc0001aca80)
	/Users/wkwon/go/pkg/mod/sigs.k8s.io/cluster-api@v1.0.1-0.20211111175208-4cc2fce2111a/util/conversion/conversion.go:244 +0x35f
testing.tRunner(0xc0005e0820, 0xc0005db560)
	/usr/local/opt/go/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:1306 +0x35a
```

**Comment by pydctw** [comment]
EKS conversion test is running now.
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3033/pull-cluster-api-provider-aws-test/1470941831687573504#1:build-log.txt%3A713

```
=== RUN   TestFuzzyConversion
=== RUN   TestFuzzyConversion/for_EKSConfig
=== RUN   TestFuzzyConversion/for_EKSConfig/spoke-hub-spoke
=== RUN   TestFuzzyConversion/for_EKSConfig/hub-spoke-hub
=== RUN   TestFuzzyConversion/for_EKSConfigTemplate
=== RUN   TestFuzzyConversion/for_EKSConfigTemplate/spoke-hub-spoke
=== RUN   TestFuzzyConversion/for_EKSConfigTemplate/hub-spoke-hub
--- PASS: TestFuzzyConversion (23.28s)
    --- PASS: TestFuzzyConversion/for_EKSConfig (14.65s)
        --- PASS: TestFuzzyConversion/for_EKSConfig/spoke-hub-spoke (7.40s)
        --- PASS: TestFuzzyConversion/for_EKSConfig/hub-spoke-hub (7.25s)
    --- PASS: TestFuzzyConversion/for_EKSConfigTemplate (8.63s)
        --- PASS: TestFuzzyConversion/for_EKSConfigTemplate/spoke-hub-spoke (3.47s)
        --- PASS: TestFuzzyConversion/for_EKSConfigTemplate/hub-spoke-hub (5.16s)
PASS
```

**Comment by richardcase** [comment]
Thanks for fixing this @pydctw . It was passing locally when we ran the tests so fixing this great.

/lgtm
/approve

**Pull request merged**
