### PR TITLE
 refactor: Makes specs for cloud package conformant to a standard naming convention

### PR DESCRIPTION
**Pull request by tasdikrahman**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Makes the specs inside the cloud/service/network package conformant to one type of naming convention

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #3198

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
I think we slightly deviated from what was expected here.
We were talking about the testcase naming conventions, not function naming convention. As mentioned in the description of the issue, we would use any of the naming convention listed [here](https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea) and would be consistent around whole repo.

**Comment by sedefsavas** [comment]
@Ankitasw I don't see much benefit from adopting that convention, see my comment [on the issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3198#issuecomment-1215427081)

Cluster API repo also uses camel case, and I think it is readable. WDYT?

**Comment by Ankitasw** [comment]
@sedefsavas Yes we can stick to camel case, but this PR just introduce camel case of functions, not for the actual testcase names, which was the intent of the issue.

**Comment by sedefsavas** [comment]
Sample PRs on the issue does the same, so issues has a problem: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3160
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3091

/lgtm
/approve

**Pull request merged**
