### PR TITLE
Promote sethp-nr and rudoi to reviewers

### PR DESCRIPTION
**Pull request by vincepri**
**What this PR does / why we need it**:
This PR adds @sethp-nr and @rudoi to project reviewers 🎉 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by vincepri** [comment]
/hold 

1 week timeout for lazy consensus

**Comment by detiber** [comment]
Big +1 from me

**Comment by chuckha** [comment]
a big lim(x->∞) cos(1/x)

**Comment by sethp-nr** [comment]
4bff7878e3f52998
Aw, thanks y'all

**Comment by ashish-amarnath** [comment]
+1 from me too!

**Comment by rudoi** [comment]
😭 thanks everyone!

**Pull request merged**
