### PR TITLE
Bump AWS SDK Go and AWS VPC CNI

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/area release

**What this PR does / why we need it**:
This PR bumps AWS SDK Go to v1.43.29 and amazon VPC CNI to v1.10.3 and fixes the mock generate errors.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3411 

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by sedefsavas** [comment]
aws vpc cni is only used for EKS, no need to run tests for CAPA-managed clusters.

/lgtm
/approve

**Comment by Ankitasw** [comment]
> aws vpc cni is only used for EKS, no need to run tests for CAPA-managed clusters.

This PR also contains version bump of aws sdk, that's the reason I chose to run E2E test.

**Comment by sedefsavas** [comment]
> > aws vpc cni is only used for EKS, no need to run tests for CAPA-managed clusters.
> 
> This PR also contains version bump of aws sdk, that's the reason I chose to run E2E test.

ACK, patch release should not cause an issue.

**Pull request merged**
