### PR TITLE
✨ Add Spot instances support

### PR DESCRIPTION
**Pull request by alexander-demichev**
**What this PR does / why we need it**:
Add a new field to API - `SpotMarketOptions`, then use it to create spot instance by initializing an `InstanceMarketOptionsRequest` and passing it to `RunInstances()`

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/559
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200330-spot-instances.md

Huge thanks to @JoelSpeed for making it possible!

### CODE REVIEW

**Comment by alexander-demichev** [comment]
Yes, tested on a real cluster, and yes it's similar to openshift

**Comment by randomvariable** [comment]
Looks like the CRDs need to be regenerated

`make generate-go` should do it.

**Comment by JoelSpeed** [comment]
/lgtm cancel
@alexander-demichev You need to implement conversion from the v1alpha2 to v1alpha3 types. Take a look at the way this was done in the azure implementation for inspiration (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/559/files)

**Comment by alexander-demichev** [comment]
@JoelSpeed done and CI works now

**Comment by randomvariable** [comment]
Great, thanks!

/approve

**Pull request merged**
