### PR TITLE
:bug: Workaround for https://bugs.launchpad.net/cloud-init/+bug/1888822

### LINKED ISSUE #1839: cloud-init v20.2-45-g5f7825e2-0ubuntu1~18.04.1 never runs /etc/secret-userdata.txt
/kind bug

**What steps did you take and what happened:**
Build OSS CAPA AMI Ubuntu 1804 using image builder for Kubernetes v1.18.3
If you're in US-East-1, here's an AMI: `ami-0e1906e4df51041c4`

Run through quickstart guide for CAPA.
Run 
clusterctl config cluster manager --kubernetes-version 1.18.3 > tmp.yaml
Add 
```
      ami:
        id: ami-0e1906e4df51041c4
```
To all of the `AWSMachineTemplate`

Deploy cluster.  cloud-init fails on first control plane, nothing happens after that.

Check: `/etc/secret-userdata.txt` *does* exist.
Check: `/var/lib/cloud/instance/user-data.txt` *does* reference that file.
Check: cloud-init *did* run twice (it was restarted from the unitial script)
FAIL: `/var/lib/cloud/instance/user-data.txt.i` *does not* resolve `/etc/secret-userdata.txt` into it.

**What did you expect to happen:**
Second run of cloud-init should properly resolve the secret-userdata and execute it properly.

**Anything else you would like to add:**
This makes me :sob: how long it took to figure out this was what was happening.

**Environment:**

- Cluster-api-provider-aws version: `us.gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller:v0.5.5-rc.0`
- Kubernetes version: (use `kubectl version`): Image is v1.18.3
- OS (e.g. from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:
As per @oddbloke's suggestion, adding a #cloud-boothook line to the boothook script allows cloud-init v20.2 to correctly interpret the boothook.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1839

### CODE REVIEW

**Comment by ncdc** [comment]
/lgtm

Does it work? 😄

**Comment by ncdc** [comment]
We can run conformance, which will run against the older AMIs that don't have the newer cloud-init with the regression, so that would confirm this doesn't break older AMIs at least. But it won't confirm it works with the newer cloud-init.

**Comment by ncdc** [comment]
Actually I think e2e should be sufficient? We just need a real cluster to be created, right?

**Comment by randomvariable** [comment]
lol, it works locally once i unborked my tilt. running either conformance or e2e would work.

**Comment by detiber** [comment]
/approve

looks like the e2e made it past cluster bootstrapping

**Comment by randomvariable** [comment]
*yells at testenv*

/test pull-cluster-api-provider-aws-test

**Pull request merged**
