### PR TITLE
[releasev0.6] Bump CAPI version to v0.3.25

### PR DESCRIPTION
**Pull request by sedefsavas**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Bump cluster-api version to v0.3.25
```

### CODE REVIEW

**Comment by sedefsavas** [comment]
Looks like deletion failed, retesting.



/test pull-cluster-api-provider-aws-e2e-eks-release-0-6

**Comment by richardcase** [comment]
@sedefsavas - i just looked at the logs and it appears the capa-controller is still trying to reconcile the AWSManagedMachinePool even after the delete for the cluster has been received. I can look into fixing this prior to the release.

**Comment by richardcase** [comment]
@sedefsavas - shall we close this now v0.6 isn't supported?

**Pull request closed without merging**
