### PR TITLE
External cloud provider e2e test without CSI

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1475

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Add external cloud provider end-to-end test
```

### CODE REVIEW

**Comment by yuzhang17** [comment]
/do-not-merge/work-in-progress

**Comment by randomvariable** [comment]
/hold

for after we've sorted out resources.

**Comment by sedefsavas** [comment]
/close

External CCM does not work without CSI even after setting `--external-cloud-volume-plugin: aws`, which  is a fallback mechanism that allows a legacy, in-tree cloudprovider to be used for volume plugins even when an external cloud controller manager is being used. 

And given that the in-tree codes will be removed in Kubernetes v1.23, we will test CCM with CSI.

**Comment by sedefsavas** [comment]
cc @Ankitasw

**Pull request closed without merging**
