### PR TITLE
PROPOSAL: Maintainers and reviewer changes

### PR DESCRIPTION
**Pull request by richardcase**
/hold

**What type of PR is this?**
/kind support

**What this PR does / why we need it**:

Make the following changes to maintainers & reviewers:

- @Skarlso moves to maintainer from reviewer
- @Ankitasw moves to maintainer from reviewer
- @AverageMarcus moves to reviewer

**Let me or @sedefsavas know if you want to become a reviewer**

This change will be on hold for approximately 1 week before its merged.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
<3 <3 <3 <3

Massive thank you! :)

**Comment by richardcase** [comment]
Lazy consensus until 19th October 2022

**Comment by Ankitasw** [comment]
Very well deserved @Skarlso its always been a pleasure working with you.

**Comment by Skarlso** [comment]
Thank you, Ankita! I really appreciate your words. 😊😊😊❤️

**Comment by Ankitasw** [comment]
Thank you for the proposal @richardcase. It has always been great working with CAPA and you folks 🙏

**Comment by richardcase** [comment]
Just to echo what has been added in Slack for posterity against this change:

- @Ankitasw has been a consistent contributor of changes and reviews over the last year and has shown great commitment to the project, personally as a maintainer it has made my life easier, so thank you Ankita :pray:
- @Skarlso has made significant contributions in both reviews and new features (like ipv6) this year...thank you Gergely

You have both helped to push CAPA forward and i think as maintainers you will continue to make a significant impact and improvement on this project.

**Comment by sedefsavas** [comment]
Thanks @Ankitasw and @Skarlso for all the commitment and great work to keep CAPA healthy!! 🙏

Very happy to see that CAPA is growing stronger with more maintainers.

**Comment by Ankitasw** [comment]
@richardcase Thanks a lot for updating the Contributing guidelines so precisely 👏 This looks quite neat and helpful 😄

**Comment by fabriziopandini** [comment]
/lgtm
Congrats!

**Comment by richardcase** [comment]
Lazy consensus is up so:

/unhold
/approve

**Pull request merged**
