### PR TITLE
drop /v2/ from api/tests/docs

### PR DESCRIPTION
**Pull request by yastij**
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>

**What type of PR is this?** 

/kind bug
/kind regression

**What this PR does / why we need it**: This PR fixes what was missed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3867 

**Which issue(s) this PR fixes**:  Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
/lgtm
/hold
until tests passes.

**Comment by richardcase** [comment]
Looks good to me as well, thanks @yastij. Subject to both e2e passing (we can unhold when they do):

/approve

**Comment by sbueringer** [comment]
Thank you very much!
/lgtm

**Pull request merged**
