### PR TITLE
Rename references to the default branch to main

### PR DESCRIPTION
**Pull request by randomvariable**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Renames references to the default branch to main.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #1782 
Corresponding test-infra PR kubernetes/test-infra#21832

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

/hold

Cannot be merged before the branch is actually renamed.

### CODE REVIEW

**Comment by sedefsavas** [comment]
We will also need to change CI jobs after renaming.

**Comment by randomvariable** [comment]
> We will also need to change CI jobs after renaming.
Yup, have filed https://github.com/kubernetes/test-infra/pull/21832

**Comment by sedefsavas** [comment]
> > We will also need to change CI jobs after renaming.
> 
> Yup, have filed [kubernetes/test-infra#21832](https://github.com/kubernetes/test-infra/pull/21832)

Thanks, there is some overlap with this PR: https://github.com/kubernetes/test-infra/pull/21451

I can combine them.

**Pull request merged**
