### PR TITLE
fix for AMI build to detect Amazon Linux

### LINKED ISSUE #978: Amazon Linux AMI build skipping `configure cloud-init` in Ansible playbook
/kind bug

**What steps did you take and what happened:**
`packer build -only=amazon-2 packer.json`

```
  amazon-2: TASK [common : configure cloud-init on amazon-linux] ***************************
    amazon-2: skipping: [default]
```

This results in a user `centos` being created and you can't login as `ec2-user` and must login as `centos`

**What did you expect to happen:**
```
   amazon-2: TASK [common : configure cloud-init on amazon-linux] ***************************
    amazon-2: changed: [default]
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

### PR DESCRIPTION
**Pull request by aaroniscode**
**What this PR does / why we need it**:
The AMI build process doesn't recognize Amazon Linux properly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #978 

**Special notes for your reviewer**:
`ansible_distribution_major_version` is `2`. I think you may have wanted `ansible_distribution_release` which is `NA` but I didn't see any reason why that was necessary. Can add it if there is.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by randomvariable** [comment]
You need to add a
`Signed-off-by: Aaron Miller <blah@vmware.com>` line to your commit, but otherwise /lgtm

**Comment by ncdc** [comment]
> You need to add a Signed-off-by: Aaron Miller blah@vmware.com line to your commit

I'm pretty sure all that's required is signing the CLA

**Comment by chuckha** [comment]
the sign-off was required on heptio open source projects but not for kubernetes

**Pull request merged**
