### PR TITLE
Streamline Ginkgo variables

### LINKED ISSUE #3390: Streamline GINKGO variables usage in Makefile target
/kind feature

**Describe the solution you'd like**
Our e2e tests are using a mix of E2E_FOCUS and GINKGO_SKIP that are feeding into GINKGO_ARGS.

```bash
ifdef E2E_FOCUS
	override GINKGO_ARGS += -focus="$(E2E_FOCUS)"
endif
...
ifdef GINKGO_SKIP
	override GINKGO_ARGS += -skip "$(GINKGO_SKIP)"
endif
```

It will be great to define GINKGO_FOCUS (replace E2E_FOCUS) and GINKGO_SKIP as separate variables to be consistent with other providers and make it easier to use them in test-infra.

For example, test-e2e make target can be defined as follow.
```bash
# CURRENT
$(GINKGO) -tags=e2e $(GINKGO_ARGS)...

# DESIRED
$(GINKGO) -tags=e2e -focus="$(GINKGO_FOCUS)" -skip="$(GINKGO_SKIP)" $(GINKGO_ARGS)...
```

**Anything else you would like to add:**
Some jobs need to be modified in https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws with this change.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by photra**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Streamlining Ginkgo variables in Makefile to improve consistency with other providers and allowing easier usage in `test-infra`

**Which issue(s) this PR fixes**:
Fixes #3390 

**Special notes for your reviewer**:
None

**Checklist**:

- [X] squashed commits
- [X] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Ankitasw** [comment]
@photra thanks for the PR 🎉 
Have you tested this locally with the GINKGO_FOCUS env var while running E2E tests? For eg., something like:

> make test-e2e GINKGO_FOCUS = "\\[Cluster API Framework\\]"

**Comment by photra** [comment]
Hi @Ankitasw 😄, I attempted to run it locally, but did not have the credentials so I couldn't. What should I do to properly run tests locally?

**Comment by Ankitasw** [comment]
Also, as part of this issue, you may also have to change the prow settings in test-infra, for eg. [this](https://github.com/kubernetes/test-infra/blob/5d7904c716ebb63b5dcab224af4f9907ba7b1b10/config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-presubmits.yaml#L191) is one such place which needs correction.

**Comment by photra** [comment]
@Ankitasw I set up have an AWS account, but I'm running into some limits when running e2e tests. What can I do to resolve this, or perhaps there is another way to test? Any help would be appreciated!

Additionally, thank you for the reminder! I also submitted a pending PR in `test-infra` to update jobs for later merging when we are done with this PR.

**Comment by photra** [comment]
Also, I noticed the following on line 332 when reviewing the build log:

`time hack/tools/bin/ginkgo -tags=e2e -focus="""" -skip="""" -stream -progress -v -trace -p ./test/e2e/suites/unmanaged/... -- -config-path="/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/data/e2e_conf.yaml" -artifacts-folder="/logs/artifacts" --data-folder="/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/data" -use-existing-cluster="false"`

It looks like there are double quotes in the e2e testing command (`-focus=""""` and `-skip=""""`). Do you think this is the root cause for our test failure?

**Comment by Ankitasw** [comment]
@photra Yes I think you would run into resource quota issues with free AWS account, I will try it out and let you know 🙂 

> It looks like there are double quotes in the e2e testing command (-focus="""" and -skip=""""). Do you think this is the root cause for our test failure?

I have not debugged the test but let me check that as well.

**Comment by Ankitasw** [comment]
The tests works fine for me with below command:

> make test-e2e GINKGO_FOCUS="\[Cluster API Framework\]"

Also, I am retriggerring the tests as test failure looks unrelated to this change.

/test pull-cluster-api-provider-aws-e2e

**Comment by Ankitasw** [comment]
/lgtm
/hold
until tests passes.

**Comment by Ankitasw** [comment]
/unhold
cc @sedefsavas @richardcase for approval

**Pull request merged**
