### PR TITLE
[WIP] Embed example templates into clusterawsadm

### LINKED ISSUE #299: Remove requirement for GNU Make, envsubst & gettext for end-user experience
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Part of #276 

Having gettext, envsubst and GNU Make installed is unusual for end-user
software, and it's extra things that will need to be 
`brew/apt/dnf` installed, as Make in particular is not installed
by default on all systems.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Removes gettext by starting to embed the templates into `clusterawsadm`.

User will run the following to create their examples:

```
clusterawsadm alpha config init --cluster-name default --ssh-key-name default --control-plane-instance-type t3.medium <etc...>
```

Which will write the same outputs as before.

Also moving the examples to a top-level `/examples` directory for better visibility. Don't think they need to live under `/cmd/clusterctl/examples`

These files are used by a Bazel rule to generate a go file with the files zipped into a Go virtual file stream which is then used by the CLI to generate the examples as rendered Go templates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #299 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

This PR will require changes to e2e, so will wait for #606 before completion.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by randomvariable** [comment]
Actually agree on this.

Only doing CLI flags as equivalents of the environment variables as used by envsubst in `generate-yaml.sh`.

What behaviour do we want to keep, and what should be jettisoned. 

Don't see the point, for example of having the instance type env vars when we as cluster api devs can use kustomize patches for our workflows, and an end user should be expected to inspect and edit the cluster and machine yamls.

**Comment by randomvariable** [comment]
How about separate commands for cluster, machine and provider components, but with the machine command, you can pass in `--cluster-config cluster.yaml` and it will generate machine.yamls with the same cluster name and ssh key?

**Comment by chuckha** [comment]
so the CLI might look something like this:

```
clusterawsadm alpha config init cluster
clusterawsadm alpha config init machine --cluster-config cluster.yaml
clusterawsadm alpha config init provider-components
```

What would cluster.yaml look like?

**Comment by randomvariable** [comment]
Was thinking of exposing the user to the real cluster object at this stage rather than present a clusterawsadm abstraction, but using the cluster object as a hint for some of the fields for new machines.

**Comment by chuckha** [comment]
ah so, the output of `clusterawsadm alpha config init cluster` would be fed into `clusterawsadm alpha config init machine --cluster-config cluster.yaml` ?

**Comment by ashish-amarnath** [comment]
That's how I thought this would work. This will be kinda guiding the user through the steps to help them understand what they are getting and what is all under their control.

**Comment by randomvariable** [comment]
Yup, that's exactly it.

**Comment by vincepri** [comment]
/milestone Next

Feel free to change if necessary.

**Comment by randomvariable** [comment]
The underlying issue is v1alpha1

Going to finish this one before #612 .

**Comment by detiber** [comment]
closing, we can reconsider down the line.

/close

**Pull request closed without merging**
