### PR TITLE
🌱 Updated Bastion-AMI os version to Ubuntu 18.04 from Ubuntu 16.04

### PR DESCRIPTION
**Pull request by LochanRn**
**What this PR does / why we need it**:

CAPA Bastion nodes use Ubuntu 16.04 os version. This is two years old and have security vulnerability.  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by LochanRn** [comment]
I have signed the CLA/ linuxfoundation certificate

**Comment by detiber** [comment]
@LochanRn would it make sense to go ahead and rev them to 20.04?

**Comment by jzhoucliqr** [comment]
I think it makes sense, since capa already have 20.04 images.

**Comment by LochanRn** [comment]
Sure, makes sense. I will update the PR with 20.04 images.

**Comment by LochanRn** [comment]
I signed it

**Pull request closed without merging**
