### PR TITLE
feat: Tag for CCM the security group provided as an override for the "sg-lb" security group role

### LINKED ISSUE #3481: Unmanaged SecurityGroups should also get tagged for CCM
/kind feature

**Describe the solution you'd like**
When using an unmanaged `SecurityGroup` for `[spec.network.securityGroupOverrides.lb](http://spec.network.securitygroupoverrides.lb/)` CAPA should tag it with `kubernetes.io/cluster/<cluster-name>` so that CCM can create ELBs for `LoadBalancer` `Services` without requiring users to tag the `SecurityGroup` themselves.

**Anything else you would like to add:**
When an instance has multiple SecurityGroups attached, CCM requires 1 of them to be tagged https://github.com/kubernetes/cloud-provider-aws/blob/8d2f0fd2b1b574bde3239a344bd0a9a4f244cdb0/pkg/providers/v1/aws.go#L4479-L4485

Currently managed `SecurityGroups` are already tagged with the required `kubernetes.io/cluster` tag. **Unmanaged** Subnets are also already tagged. It would not be a stretch for CAPA to also tag the SecurityGroup.

[Originally discussed in Slack.](https://kubernetes.slack.com/archives/CD6U2V71N/p1652814232505389)

**Environment:**

- Cluster-api-provider-aws version: 
[v1.4.1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v1.4.1)
- Kubernetes version: (use `kubectl version`): 
v1.22.8
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What type of PR is this?**
/kind feature 

**What this PR does / why we need it**:
Tag for CCM the security group provided as an override for the "sg-lb" security group role. This tag is required for the CCM to choose the subnet to deploy an ELB. Note that CAPA already adds this tag to an existing subnet (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2715).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3481

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by dlipovetsky** [comment]
If CAPA applies the CCM tag to a user-owned security group on cluster create, should it remove the tag on cluster delete?

If it should remove the tag, then this PR is not complete, because it doesn't remove the tag.

**Comment by dlipovetsky** [comment]
I rebased on main because #3843 merged.

**Comment by dlipovetsky** [comment]
> > If CAPA applies the CCM tag to a user-owned security group on cluster create, should it remove the tag on cluster delete?
> 
> I would say it should undo the action it took on delete.

Would you say the same for subnets and route tables, then? Because we currently do not undo the action for subnets.


> But, do you think we can have multiple CAPA clusters using the same SG in this scenario?

I suppose it is possible, although I'm not sure it would be a good idea. The `lb` SG has one inbound rule for every ELB backing a LoadBalancer Service. It has one outbound rule that allows all traffic.

**Comment by dlipovetsky** [comment]
/hold cancel

#3843 merged.

**Comment by richardcase** [comment]
> Would you say the same for subnets and route tables, then? Because we currently do not undo the action for subnets.

As a guiding principle it would be good to undo changes we have made, so yes. But I'm wondering why didn't do that in the first place. Was it because we just didn't think of it or was there a specific reason.

I agree it does need further discussion. Do you think we delay v2.0.0 until we decide this, or can we push this change to the next API version bump to give us more time?

**Comment by Ankitasw** [comment]
To not delay the v2.0.0 release, can we somehow document this and put this PR on hold for next API version?

**Comment by dlipovetsky** [comment]
This PR does not remove the CCM tag from user-owned resources. As I explain in https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3854, not removing the tag on cluster delete prevents use of the resource in future clusters.

CAPA needs to either remove the CCM tag on cluster delete, or not apply it at all.

I'm going to close this PR. We can open a new one, if needed, once we have consensus on #3854.

**Pull request closed without merging**
