### PR TITLE
Update references following Flatcar GitHub org rename

### PR DESCRIPTION
**Pull request by johananl**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

The flatcar-linux GitHub organization is being renamed to "flatcar". This PR updates all references accordingly.

Upstream issue: https://github.com/flatcar-linux/Flatcar/issues/836

I'm opening this PR in advance to allow quick merging once the rename occurs. I'll mark it as on hold in the meantime.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

**Special notes for your reviewer**: None

**Checklist**:

- [x] squashed commits

## TODO (after the rename)

- [x] Run `go mod tidy` and ensure correct update of `go.sum`.
- [x] Run `make generate`.
- [x] Verify everything compiles and runs.
- [x] Verify tests are passing.
- [x] Verify CI is green.

### CODE REVIEW

**Comment by johananl** [comment]
/hold

(see description for explanation)

**Comment by Ankitasw** [comment]
/retitle [WIP] Update references following Flatcar GitHub org rename

**Comment by johananl** [comment]
PR is ready for merging.

/unhold

**Comment by johananl** [comment]
/retitle Update references following Flatcar GitHub org rename

**Pull request merged**
