### PR TITLE
Refactor AMI commands and publish AMIs in book

### LINKED ISSUE #2088: Create a PR when a new kubernetes release is detected
/kind feature

**Describe the solution you'd like**
To automate the process of publishing AMIs, we need a job to create an entry in the `AMI-version.yaml` corresponding to the newly released kubernetes versions. As part of that process, we need a job to create a PR whenever a new kubernetes version is detected.

**Anything else you would like to add:**
More detailed information on the process is added in the issue #1982 and the [Google doc](https://docs.google.com/document/d/142YzzRj2H_OWEUE03Vrw3D-XpDCWM8RviFGHT5-RBxo/edit?usp=sharing) here

**Environment:**
n/a

### PR DESCRIPTION
**Pull request by randomvariable**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Fixes #2088 

* Converts clusterawsadm AMI commands to library functions
* Adds TypeMeta API Machinery to AMI output for versioned programmatic consumption
* Creates a lambda function to periodically update AMI listing to an S3 bucket every hour
* Adds a Javascript table to the book to display the latest published AMIs dynamically
* Adds --source-region parameter to copy AMIs across regions

image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [X] squashed commits
- [X] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
`clusterawsadm  ami` commands now support `--source-region` to copy AMIs across regions
`clusterawsadm ami` commands now output versioned AWSAMIList and AWSAMI resources to stdout
```

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold

need to change the JS

**Comment by randomvariable** [comment]
/unhold

CloudFront distribution set up for https.

**Comment by sedefsavas** [comment]
@randomvariable If the last commit I pushed is ok, I will LGTM.

**Comment by randomvariable** [comment]
Thanks!

**Comment by randomvariable** [comment]
Have updated.

**Pull request merged**
