### PR TITLE
Add elasticloadbalancing:SetSubnets to cloudformation

### PR DESCRIPTION
**Pull request by tobiasgiese**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

We should add the IAM role `elasticloadbalancing:SetSubnets` to the cloudformation templates and `clusterawsadm` as we are using it during reconciliation (thanks to @seanschneeweiss for finding the lines in the code):

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2d96288354dee44e60710048652267e2bf3e8c12/pkg/cloud/services/elb/loadbalancer.go#L113-L123

Otherwise the following error will occur:

```
failed to reconcile load balancer" err=<
    failed to set subnets for apiserver load balancer '...-apiserver': AccessDenied: User: arn:aws:sts::xxx:assumed-role/... is not authorized to perform: elasticloadbalancing:SetSubnets on resource: arn:aws:elasticloadbalancing:... because no identity-based policy allows the elasticloadbalancing:SetSubnets action
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
action required
A new required permission must be added to your controllers policy by running clusterawsadm bootstrap iam create-cloudformation-stack again (or can manually add elasticloadbalancing:SetSubnets permission to controllers policy).
```

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by roehrijn** [comment]
@tobiasgiese, you showed me a snipped from the docs where the `SetSubnets` permission was also missing. We should also adapt the docs I guess. WDYT?

**Comment by tobiasgiese** [comment]
> @tobiasgiese, you showed me a snipped from the docs where the `SetSubnets` permission was also missing. We should also adapt the docs I guess. WDYT?

You can find the rendered book [via the netlify deployment of this PR](https://deploy-preview-4357--kubernetes-sigs-cluster-api-provider-aws.netlify.app/topics/iam-permissions.html#ec2-provisioned-kubernetes-clusters).
But tbh, I just checked it and had to push a fix, as I added the IAM roles to the wrong controllers. It's looking good now. Thanks for the hint :)

**Comment by enxebre** [comment]
Is there an audited list somwhere of the iam required for the controller in different scenarios so consumers can follow principle of least privilege? If not should we create one?

**Comment by tobiasgiese** [comment]
> Is there an audited list somwhere of the iam required for the controller in different scenarios so consumers can follow principle of least privilege? If not should we create one? Related #4342

It's documented [in the book under IAM Permissions](https://deploy-preview-4357--kubernetes-sigs-cluster-api-provider-aws.netlify.app/topics/iam-permissions.html).

**Pull request merged**
