### PR TITLE
fix: use provided NodeRegistrationOptions as base

### LINKED ISSUE #822: KubeletExtraArgs not propagating through to kubeadm config
/kind bug

**What steps did you take and what happened:**

Created a controlplane Machine with the following init configuration:
```yaml
init:
    nodeRegistration:
        kubeletExtraArgs:
            network-plugin: "cni"
            cni-conf-dir: "/etc/cni/net.d"
            cni-bin-dir: "/opt/cni/bin"
            node-ip: {{  ds.meta_data.local_ipv4 }}
```

Went to see logs via `kubectl logs` and got an i/o timeout, discovered it was AWS VPC CNI related. That CNI requires the above extra args, so took a look at `/tmp/kubeadm.yaml` and:

```yaml
nodeRegistration:
  criSocket: /var/run/containerd/containerd.sock
  kubeletExtraArgs:
    cloud-provider: aws
```

No extra args. :sob:

**What did you expect to happen:**

The extra args make it to kubeadm.yaml.

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): 1.13.7
- OS (e.g. from `/etc/os-release`): ubuntu

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:
This uses the provided Init/Join configurations' NodeRegistration as a base. If there is no provided NodeRegistration, this effectively functions the same as before, starting with a blank NodeRegistrationOptions and executing the funcOpts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #822 

**Release note**:

```release-note
Fixes bug where provided NodeRegistration is not honored
```

### CODE REVIEW

**Comment by ncdc** [comment]
Do you want to add a test that confirms if you start with a non-empty base, it uses that instead of throwing it away?

**Comment by ncdc** [comment]
@rduoi thanks for the quick addition of the new test case - you rock!

**Comment by rudoi** [comment]
> Do you want to add a test that confirms if you start with a non-empty base, it uses that instead of throwing it away?

@ncdc added!

**Comment by chuckha** [comment]
/approve

thanks for the fix! 🙏

**Pull request merged**
