### PR TITLE
🐛 ROSA: Fix autoRepair default value

### PR DESCRIPTION
**Pull request by serngawy**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The PR change the machinePool.AutoRepair default value to true as the default value of nodePool.AutoRepair at the OCM API [here](https://api.openshift.com/#/default/get_api_clusters_mgmt_v1_clusters__cluster_id__node_pools) is true. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [X ] squashed commits
- [ ] includes documentation
- [ X] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Changing the ROSAMachienPool AutoRepair default value to true. 
```

### CODE REVIEW

**Comment by muraee** [comment]
/lgtm
please update the release notes to indicate the behavior change

**Comment by nrb** [comment]
Will approve once there's a release note.

**Comment by serngawy** [comment]
just to clarify, where should release note should be added ?

**Comment by damdo** [comment]
@serngawy  In this pull request description, where you typed `None`

**Pull request merged**
