### PR TITLE
bastion: Fix bastion code to always lookup via tags

### PR DESCRIPTION
**Pull request by phyber**
**What this PR does / why we need it**: Fixes bastion reconciliation after manually deleting in AWS console

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #165

**Special notes for your reviewer**: This fixes things so bastion lookup always happens via instance tags, fixing the reconciliation.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vincepri** [comment]
@phyber Can you provide an example on why this is needed? Wouldn't the ID be sufficient in case we need to reconcile?

**Comment by vincepri** [comment]
This was actually fixed in #219 I believe, the bastion instance describe filters now has a state filter.

CC @randomvariable

**Comment by phyber** [comment]
I not sure that #219 fixes it. In the flow where Go was panicking, `describeBastionInstance` would describe the bastion via `InstanceIfExists`. This would return that it had found the instance, even if it was Terminated. And reconciliation would not happen. After an hour, the terminated instance would disappear from AWS and Go would now panic. This is probably due to `InstanceIfExists` returning `nil` for the error if it doesn't find the instance.

Removing the `InstanceIfExists` call and just getting the bastion by filtering on tags allowed the bastion to be reconciled if it was Terminated as `describeBastionInstance` knows how to deal with the terminated instance if it finds it via filtering on tags.

Arguably, I could have fixed up the `InstanceIfExists` call to check the `State` of the instance it's about to return, so that if it finds a `shutting-down` or `terminated` instance it returns that it found nothing (I actually think this should still be done).

However, due to other conversations I was under the impression that we were wanting to use the instance tags to find instances rather than relying on the instance IDs, so I opted for the solution here, to remove the check for `InstanceID` and just rely on the tags.

**Pull request merged**
