### PR TITLE
🌱 Add basic unit test for EKS `AWSManagedControlPlaneReconciler`

### PR DESCRIPTION
**Pull request by AndiDog**
**What type of PR is this?**

/kind support

**What this PR does / why we need it**:

The EKS reconciliation was not covered in unit tests at all, making it hard to contribute changes with confidence. So like for `AWSCluster` reconciliation, I added a similar type of test that checks the basic creation of a cluster and the expected AWS API calls.

For now, the only test is for `AWSManagedControlPlane creation with managed VPC`, but more can be added more easily after this PR, since I'm making the controller testable.

This meant to fix a few small things along the way, such as version parsing which ignored errors or panicked until now.

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [x] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
This is really helpful @AndiDog, could you please add what all tests have you covered as part of description? It would be helpful in the review.

**Comment by AndiDog** [comment]
@Ankitasw Added some more description, but really it's "just" about making the controller testable and adding a basic test `AWSManagedControlPlane creation with managed VPC`. I didn't want to blow up the PR size by adding much more. Adding more tests will be much easier after this.

**Comment by richardcase** [comment]
Thanks @AndiDog. This is really helpful and as a base it will enable us to improve our test coverage on the EKS side. From my side:

/approve

**Pull request merged**
