### PR TITLE
🏃‍♂️ Update cloudbuild to Go 1.16

### PR DESCRIPTION
**Pull request by sbueringer**
**What type of PR is this?**

**What this PR does / why we need it**:

This PR updates the cloudbuild to use an image with Go 1.16. For more context see https://github.com/kubernetes-sigs/cluster-api/issues/4383.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold

Let's merge this once we move to v1alpha4

**Comment by randomvariable** [comment]
If you rebase, that should appease netlify.

**Comment by sbueringer** [comment]
Done, netlify should be happy now.

**Pull request merged**
