### PR TITLE
Add optional v1alpha4 and self-hosted management cluster tests

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What type of PR is this?**

/kind failing-test
/area testing

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #2788 
Part of #2793 

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests
- [x] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by randomvariable** [comment]
I don't think increasing the other timeouts was needed. All of the test failure is in waiting for the new CAPA deployment to work.

Also, a quick way to do a focus test is to change `ginkgo.Describe` to `ginkgo.FDescribe`. This does seem to work as intended now.

We really need the logs from the failed deployment to progress any further. The trick @sbueringer used to get CAPI to capture the logs / resources doesn't seem to be working here either ( https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2833/files#diff-dea35878305c9433431c403c381e4b9da30fd93e421bffe231e10bc7e1936bb2R187-R188 combined with https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2833/files#diff-a8c373107120a1dab4c23cac001fa264916db24290ba014b467fc1f8132dcab8R11-R13 )

**Comment by randomvariable** [comment]
> I am able to replicate locally. After the upgrade, all deployment machines come up but MachineDeployment is not being reconciled hence never detects scaling up is successful.

Is that a separate issue to the one that keeps showing up?
> "reason": "ProgressDeadlineExceeded",
> [1]             "message": "ReplicaSet \"capa-controller-manager-7bd56cd58\" has timed out progressing."

**Comment by sedefsavas** [comment]
Thanks, will check out that.

/test pull-cluster-api-provider-aws-e2e

**Comment by randomvariable** [comment]
Yeah, the bucket is empty during the test run. I think something is deleting the S3 image. Maybe it's a lambda or some security thing deleting any object made publicly readable.

Will probably need to create an S3 bucket policy that allows members of the AWS account to read, but not set publicly readable. Might have to check if this is what is happening with k8s infra / sig testing folk.

**Pull request merged**
