### PR TITLE
Add CCM tag to routing tables

### PR DESCRIPTION
**Pull request by Skarlso**
/kind feature

**What this PR does / why we need it**:

Add CCM tag to routing tables.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3532

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by dlipovetsky** [comment]
I think this might be incomplete.

Since we already apply the tag to existing subnets, and, as of #3844, we will apply the tag to existing (i.e. override) security groups, then we also want to apply the tag to user-created route tables.

However, this PR does not apply the tag to user-created route tables, only ones created by CAPA.

**Comment by Skarlso** [comment]
Thank you @dlipovetsky! I will create a follow up PR.

**Pull request merged**
