### PR TITLE
Add upgrade to main test

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:

This PR adds upgrade to Kubernetes main branch test.
It tests both KCP and MachineDeployment upgrade.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [X] adds or updates e2e tests

**Release note**:

```release-note
Add upgrade to Kubernetes main test
```

### CODE REVIEW

**Comment by randomvariable** [comment]
PTAL, and remove the WIP when it's successful

**Comment by sedefsavas** [comment]
@randomvariable  This was failing due to quay was down.

**Pull request merged**
