### PR TITLE
🐛 Correct typos in AWSManagedControlPlane types

### PR DESCRIPTION
**Pull request by MarcusNoble**
Completed https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2083 (generated CRD yaml)

FYI: @windayski

/cc @randomvariable

### CODE REVIEW

**Comment by sedefsavas** [comment]
/lgtm
Shall we hold all api related changes until we merge v1alpha4 PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121
I already created v1alpha4 types, rebasing doesn't add these changes to v1alpha4, it is manual, so we may miss api related changes.

**Comment by MarcusNoble** [comment]
This change doesn't affect the API itself, just a typo in the generated docs so I don't mind either way. I was just looking to get #2083 closed off. :)

**Comment by sedefsavas** [comment]
Yes, what I mean was the api package changes, because v1alpha4 is the exact copy of v1alpha3 package. When I rebase to this change, it will not be populated in v1alpha4 directory.
This is a small change so it is fine, this is more of a general comment.

**Comment by MarcusNoble** [comment]
Sorry, yes, I see what you mean now. (Still waking up 😆)

I'm happy with whatever. If you want I can hold off on this and update it after the v1alpha4 are in or we can just look at adding it directly into your PR and close off thise and #2083?

**Comment by randomvariable** [comment]
@sedefsavas why don't you rebase your PR on top of this one, and we'll just do one PR?

**Comment by sedefsavas** [comment]
Done. Closing this.

**Comment by sedefsavas** [comment]
Can't close this =)
Ready to be closed.

**Pull request closed without merging**
