### PR TITLE
[E2E] Increase service quota for VPC

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind failing-test
/kind regression

**What this PR does / why we need it**:
This PR increases service quota for VPC to 25, as current quota is not sufficient for running E2E tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [X] adds or updates e2e tests

### CODE REVIEW

**Comment by richardcase** [comment]
Not entirely convinced we need to do this, especially as i think we limit test parallelization to 20. Shall we see how the e2e go without this for a while?

**Comment by Ankitasw** [comment]
Sure will close this for now
/

**Comment by richardcase** [comment]
Until e2e pass:

/hold

**Comment by richardcase** [comment]
And also:

/lgtm
/approve

**Comment by Ankitasw** [comment]
> Until e2e pass:
> 
> /hold

I think this wont happen still as quota will increase gradually 😅

**Comment by Ankitasw** [comment]
I would unhold this, and see how gradually it solves our issue and take action as and when required.

/unhold

**Pull request merged**
