### PR TITLE
Update Calico to v3.24.1

### PR DESCRIPTION
**Pull request by killianmuldoon**
Update Calico to v3.24.1. May be related to failures in #4173 

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by Ankitasw** [comment]
Still failing 😢

**Comment by killianmuldoon** [comment]
I'll dive into the logs once the job is finished :thinking:

**Comment by killianmuldoon** [comment]
It looks like the `kube-system/ebs-csi-controller-7547b54cd9-8zkqm` pod can't be evicted because of its `PodDisruptionBudget`

I think it must be related to the changes in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4147 updating the ebs-csi, but I'm not certain.

**Comment by Ankitasw** [comment]
> I think it must be related to the changes in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4147 updating the ebs-csi, but I'm not certain.

I will take a look at that and test in the other test PR.

**Comment by killianmuldoon** [comment]
Passed after the changes to the ebs-csi yaml. @Ankitasw do you want to make those changes in your PR and I can revert this to just being a CNI update?

Honestly I'm not certain which of the changes had the impact - I made two. You might want to check which one is actually responsible in the fix (or I can do that in a different PR if you'd prefer).

**Comment by Ankitasw** [comment]
Thankyou for finding the root cause @killianmuldoon I will raise a separate PR with this change.

**Comment by Ankitasw** [comment]
@killianmuldoon looks like the test passed, you can revert the ebs-csi changes, and this PR would be good to go.

**Comment by killianmuldoon** [comment]
Glad to hear it! I've reverted that change on this PR.

**Pull request merged**
