### PR TITLE
Persist network information

### PR DESCRIPTION
**Pull request by praveenghuge**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2563

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by shivi28** [comment]
Hey @praveenghuge Thanks for the PR. 🎉 
Just few suggestions:
1. For the `Release notes` section in PR description you can put `NONE` for minor changes that you don't want to add in release notes( https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.6.6).
2. Reviewers will pick PR for review, so there is no need to assign reviewers manually.

/ok-to-test

**Comment by sedefsavas** [comment]
@praveenghuge we need to set the ID way before this point and doing the change in reconcileVPC() required some logical changes.
Closing this PR in favor of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2566

**Pull request closed without merging**
