### PR TITLE
🌱 [PROPOSAL]: Move Andidog to maintainer

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This change moves @AndiDog from reviewer to maintainer. There will be lazy concensus and this will merge after the CAPA office hours on Monday 22nd if there are no objections.

/cc @dlipovetsky @Ankitasw @nrb  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Move AndiDog to maintainer status.
```

### CODE REVIEW

**Comment by richardcase** [comment]
Thank you @AndiDog for your commitment to this project.

**Comment by nrb** [comment]
+1 from me, thanks for all your time @AndiDog!

**Comment by cnmcavoy** [comment]
+1 from me.

**Comment by AndiDog** [comment]
/lgtm

Thank you!

**Pull request merged**
