### PR TITLE
chore: Bump CAPI to v1.3.1

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind support

**What this PR does / why we need it**:

- This PR bumps CAPI to v1.3.1. 
- It also update golang version to 1.19.4, lint errors introduced are also fixed here.
- CAPI uses Ginkgo V2 APIs, hence this PR migrates CAPA to use Ginkgo V2 and changes introduced by it are also fixed.
- Update k8s version in unmanaged E2E tests to v1.25.3. EKS supports only till k8s v1.24, so tests for EKS has not been updated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] adds or updates e2e tests

### CODE REVIEW

**Comment by Skarlso** [comment]
/lgtm

Looks like tests are okay with this one now.

**Comment by Ankitasw** [comment]
@Skarlso yes the test runs are fine but the problem is junit reports are not segregated now:
Screen Shot 2022-12-14 at 2 04 58 PM
as it used to be in Ginkgo v1:
Screen Shot 2022-12-14 at 2 04 58 PM
Trying to figure this out now.

**Comment by Ankitasw** [comment]
Since v1.3.1 is out, I would correct the existing errors and bump to latest version in this PR

**Comment by Ankitasw** [comment]
Running tests one final time.

/test pull-cluster-api-provider-aws-e2e
/test pull-cluster-api-provider-aws-e2e-eks
/test pull-cluster-api-provider-aws-e2e-clusterclass
/test pull-cluster-api-provider-aws-e2e-blocking
/test pull-cluster-api-provider-aws-e2e-conformance

**Comment by Ankitasw** [comment]
@Skarlso would need your help in review/lgtm again 😄 after tests passes.

**Comment by Skarlso** [comment]
Uh, well, those failed spectacularly. :D

**Comment by Ankitasw** [comment]
Triggerred again 🤞

**Comment by Ankitasw** [comment]
Going to leave eks gc tests as its not tested periodically.

**Comment by Ankitasw** [comment]
PR is ready for review.

**Pull request merged**
