### PR TITLE
🌱 Add comments for VersionNumber field in AWSLaunchTemplate

### LINKED ISSUE #1986: Version field in AWSLaunchTemplate spec is missing comments/validation
/kind feature
/help
/good-first-issue

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Add validation and/or comments to version field in AWSLaunchTemplate spec

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1986

### CODE REVIEW

**Comment by shysank** [comment]
Assigned membership in [CNCF - VMware Inc](https://identity.linuxfoundation.org/content/cncf-vmware-inc)

**Comment by richardcase** [comment]
Thanks @shysank 

After you change the descriptions on the api types you need to run `make generate` so that the openapi definition is updated. The test is failing due to that as it does a diff.

**Comment by richardcase** [comment]
`VersionNumber` has no effect if set, its only set from the SDK. So no validation is required. Makes me think this is more for status and not spec. But thats outside the scope of this issue.

/lgtm

**Review by richardcase — APPROVED** [review]

**Comment by randomvariable** [comment]
Yeah, possibly moving to Status makes sense, as we can always query for it? But out of scope as you say.

/approve

**Pull request merged**
