### PR TITLE
🐛capi's local-overrides.py can't find a kustomization.yaml

### PR DESCRIPTION
**Pull request by mytunguyen**
**What this PR does / why we need it**:

To fix CAPI's `local-overrides.py`, otherwise it will try to do 
```
kustomize build ../cluster-api-provider-aws/config
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/projects/cluster-api-provider-aws/config'
```

### CODE REVIEW

**Comment by detiber** [comment]
/ok-to-test
/approve
/assign @fabriziopandini 

@mytunguyen we should work on getting you org membership, I'm happy to sponsor: https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by vincepri** [comment]
/hold

This issue should be fixed by #1575

**Comment by fabriziopandini** [comment]
I confirm this issue is going to be fixed by #1575

**Comment by mytunguyen** [comment]
Oh! Perfect. Thanks for confirming.

@detiber Thanks!! I'll find a second sponsor

**Pull request closed without merging**
