### PR TITLE
Cleanup certificates package

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vince@vincepri.com>

**What this PR does / why we need it**:
Cleanup the certificate package.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

**Special notes for your reviewer**:
None

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by vincepri** [comment]
Not sure why `gofmt` is erroring, the formatting looks fine and if ran locally it works fine.

**Comment by vincepri** [comment]
Using `gofmt -s` but it reports no changes locally. Maybe it's a different version?

**Comment by randomvariable** [comment]
I'll test a few linter theories out in a little while if you don't mind waiting a bit.

**Comment by randomvariable** [comment]
#242 should sort you out.

**Pull request closed without merging**
